import type { AdminAccount, Employee, AttendanceRecord, EmployeeRequest, Settings, Location, EscapeEvent } from "@/types";
import { getDeviceFingerprint, getDeviceId, getDeviceLabel } from "@/lib/device";
import { compressProfileImageDataUrl } from "@/lib/imageCompression";
import { employeeAvatarUrl } from "@/lib/avatarUrl";
import { persistPwaSession, clearPwaSession, restorePwaSession } from "@/lib/pwaSession";

const CANONICAL_API_URL = "https://hadir-api.abunizar963.workers.dev";
const configuredApiUrl = String(import.meta.env.VITE_API_URL || "").trim().replace(/\/$/, "");
const API_URL = import.meta.env.PROD ? "" : (configuredApiUrl || CANONICAL_API_URL);
export const backendEnabled = true;
export const MAX_AVATAR_BYTES = 10 * 1024 * 1024;
export const MAX_STORED_AVATAR_BYTES = 100 * 1024;
type RoleHint = "admin" | "employee";
const ADMIN_TOKEN_KEY = "hadir.api.token.admin";
const EMPLOYEE_TOKEN_KEY = "hadir.api.token.employee";
const EMPLOYEE_SESSION_KEY = "hadir.session";
const MANAGER_SESSION_KEY = "hadir.manager_session";
function readStoredJson<T>(key: string): T | null { if (typeof window === "undefined") return null; try { const raw = localStorage.getItem(key); return raw ? (JSON.parse(raw) as T) : null; } catch { return null; } }
function hasEmployeeSession(): boolean { const session = readStoredJson<{ employeeId?: string }>(EMPLOYEE_SESSION_KEY); return Boolean(session?.employeeId); }
function hasManagerSession(): boolean { const session = readStoredJson<{ accountId?: string; role?: string }>(MANAGER_SESSION_KEY); return Boolean(session?.accountId || session?.role); }
function tokenForRole(role: RoleHint): string { if (typeof window === "undefined") return ""; return localStorage.getItem(role === "admin" ? ADMIN_TOKEN_KEY : EMPLOYEE_TOKEN_KEY) || ""; }
function activeRole(): RoleHint | undefined { if (hasManagerSession()) return "admin"; if (hasEmployeeSession()) return "employee"; if (tokenForRole("admin")) return "admin"; if (tokenForRole("employee")) return "employee"; return undefined; }
function token(): string { const role = activeRole(); return role ? tokenForRole(role) : ""; }
function clearRoleSession(role: RoleHint): void { if (typeof window === "undefined") return; localStorage.removeItem(role === "admin" ? ADMIN_TOKEN_KEY : EMPLOYEE_TOKEN_KEY); if (role === "admin") localStorage.removeItem(MANAGER_SESSION_KEY); else localStorage.removeItem(EMPLOYEE_SESSION_KEY); }
function persistToken(role: RoleHint, value: string): void { if (typeof window === "undefined") return; const opposite: RoleHint = role === "admin" ? "employee" : "admin"; clearRoleSession(opposite); clearPwaSession(opposite); localStorage.setItem(role === "admin" ? ADMIN_TOKEN_KEY : EMPLOYEE_TOKEN_KEY, value); void persistPwaSession(value, role); }
export function validateAvatarDataUrl(value: unknown): string | null { if (value == null || value === "") return null; if (typeof value !== "string" || !value.startsWith("data:image/")) throw new Error("صورة الموظف غير صالحة."); const comma = value.indexOf(","); if (comma < 0) throw new Error("صيغة صورة الموظف غير صالحة."); const base64 = value.slice(comma + 1); const padding = base64.endsWith("==") ? 2 : base64.endsWith("=") ? 1 : 0; const bytes = Math.max(0, Math.floor(base64.length * 3 / 4) - padding); if (bytes > MAX_AVATAR_BYTES) throw new Error("حجم صورة الموظف الأصلية يجب ألا يتجاوز 10 ميغابايت."); return value; }
async function prepareAvatar(value: unknown): Promise<string | null> { const validated = validateAvatarDataUrl(value); if (!validated) return null; const compressed = await compressProfileImageDataUrl(validated, { maxWidth: 512, maxHeight: 512, quality: 0.78, type: "image/webp", maxBytes: MAX_STORED_AVATAR_BYTES }); const comma = compressed.indexOf(","); if (comma < 0) throw new Error("تعذر تجهيز صورة الموظف."); const base64 = compressed.slice(comma + 1); const padding = base64.endsWith("==") ? 2 : base64.endsWith("=") ? 1 : 0; const bytes = Math.max(0, Math.floor(base64.length * 3 / 4) - padding); if (bytes > MAX_STORED_AVATAR_BYTES) throw new Error("تعذر ضغط صورة الموظف إلى أقل من 100 كيلوبايت."); return compressed; }
function dataUrlToBlob(dataUrl: string): Blob { const comma = dataUrl.indexOf(","); if (comma < 0) throw new Error("صيغة الصورة المضغوطة غير صالحة."); const header = dataUrl.slice(0, comma); const base64 = dataUrl.slice(comma + 1); const mime = /^data:([^;]+);base64$/i.exec(header)?.[1] || "image/webp"; const binary = atob(base64); const bytes = new Uint8Array(binary.length); for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index); return new Blob([bytes], { type: mime }); }
function isTransientNetworkError(error: unknown): boolean { if (error instanceof DOMException && error.name === "AbortError") return true; if (!(error instanceof Error)) return false; return error.message === "Failed to fetch" || error.message === "Load failed" || error.message === "NetworkError when attempting to fetch resource." || error.message.startsWith("تعذر الاتصال بخادم حاضر ("); }
async function waitForOnline(timeoutMs = 30000): Promise<void> { if (typeof window === "undefined" || typeof navigator === "undefined" || navigator.onLine !== false) return; await new Promise<void>((resolve) => { let settled = false; const finish = () => { if (settled) return; settled = true; window.removeEventListener("online", finish); window.clearTimeout(timer); resolve(); }; const timer = window.setTimeout(finish, timeoutMs); window.addEventListener("online", finish, { once: true }); }); }
async function waitForVisible(timeoutMs = 15000): Promise<void> { if (typeof document === "undefined" || document.visibilityState === "visible") return; await new Promise<void>((resolve) => { let settled = false; const finish = () => { if (settled) return; settled = true; document.removeEventListener("visibilitychange", finish); window.clearTimeout(timer); resolve(); }; const timer = window.setTimeout(finish, timeoutMs); document.addEventListener("visibilitychange", finish, { once: true }); }); }
async function request<T>(path: string, init: RequestInit = {}, roleHint?: RoleHint): Promise<T> { const headers = new Headers(init.headers); if (!(init.body instanceof FormData) && !headers.has("content-type")) headers.set("content-type", "application/json"); const role = roleHint || activeRole(); const authToken = role ? tokenForRole(role) : token(); if (authToken) headers.set("authorization", `Bearer ${authToken}`); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 20000); try { const response = await fetch(`${API_URL}${path}`, { ...init, headers, signal: controller.signal, credentials: "include", cache: "no-store" }); const data: unknown = await response.json().catch(() => ({})); if (!response.ok) { const error = data as { error?: unknown }; throw new Error(typeof error.error === "string" ? error.error : `فشل الاتصال بالخادم (${response.status})`); } return data as T; } catch (error) { if (error instanceof DOMException && error.name === "AbortError") throw new Error("انتهت مهلة الاتصال بخادم حاضر. سيتم إعادة المحاولة تلقائيًا عند عودة الاتصال."); if (error instanceof TypeError || (error instanceof Error && (error.message === "Failed to fetch" || error.message === "Load failed" || error.message === "NetworkError when attempting to fetch resource."))) throw new Error(`تعذر الاتصال بخادم حاضر (${API_URL || window.location.origin}). تحقق من اتصال الإنترنت وCloudflare Worker.`); throw error; } finally { window.clearTimeout(timeout); } }
async function requestWithRetry<T>(path: string, init: RequestInit = {}, attempts = 5, roleHint?: RoleHint): Promise<T> { let lastError: unknown; for (let attempt = 1; attempt <= attempts; attempt += 1) { try { await waitForOnline(); await waitForVisible(); return await request<T>(path, init, roleHint); } catch (error) { lastError = error; if (!isTransientNetworkError(error) || attempt >= attempts) break; const baseDelay = Math.min(8000, 750 * (2 ** (attempt - 1))); const jitter = Math.floor(Math.random() * 350); await new Promise((resolve) => window.setTimeout(resolve, baseDelay + jitter)); } } throw lastError instanceof Error ? lastError : new Error("تعذر الاتصال بخادم حاضر."); }
export async function backendLogin(username: string, password: string) { const data = await requestWithRetry<{ token: string; user: AdminAccount; kind: "admin" | "employee" }>("/api/auth/login", { method: "POST", body: JSON.stringify({ username: username.trim(), password }) }, 3); if (data.kind !== "admin") throw new Error("هذا الحساب موظف وليس حساب إدارة"); persistToken("admin", data.token); return data.user; }
export async function backendEmployeeLogin(username: string, password: string) { if (typeof window === "undefined") throw new Error("تسجيل الدخول متاح من المتصفح فقط."); const deviceId = getDeviceId(); const fingerprint = await getDeviceFingerprint(); const data = await requestWithRetry<{ token: string; user: Employee; kind: "admin" | "employee" }>("/api/auth/login", { method: "POST", body: JSON.stringify({ username: username.trim(), password, deviceId, deviceLabel: getDeviceLabel(), deviceFingerprint: fingerprint }) }, 3); if (data.kind !== "employee") throw new Error("هذا الحساب إداري وليس حساب موظف"); persistToken("employee", data.token); return data.user; }
export async function registerEmployeePasskey() { const options = await request<any>("/api/device/passkey/registration/options", {}, "employee"); const { startRegistration } = await import("@simplewebauthn/browser"); const credential = await startRegistration({ optionsJSON: options }); return request<{ verified: boolean }>("/api/device/passkey/registration/verify", { method: "POST", body: JSON.stringify(credential) }, "employee"); }
export async function getEmployeeDeviceStatus() { return request<{ bound: boolean; passkeyCount: number; deviceLabel: string | null }>("/api/device/status", {}, "employee"); }
export async function bootstrapBackend() { const data = await requestWithRetry<{ token: string; bootstrap: boolean }>("/api/bootstrap"); if (!data.bootstrap) throw new Error("تم إعداد حساب المالك مسبقًا"); persistToken("admin", data.token); return data; }
export async function createBootstrapOwner(input: { name: string; username: string; password: string }) { const data = await requestWithRetry<{ token: string; user: AdminAccount; kind: "admin" }>("/api/bootstrap/owner", { method: "POST", body: JSON.stringify(input) }); persistToken("admin", data.token); return data.user; }
export async function backendLogout(role?: RoleHint) { const resolved = role || activeRole(); if (!resolved) return; try { await requestWithRetry<{ ok: boolean }>("/api/auth/logout", { method: "POST", body: JSON.stringify({}) }, 2, resolved); } finally { clearRoleSession(resolved); clearPwaSession(resolved); } }
export async function backendMe(roleHint?: RoleHint) { const role = roleHint || activeRole(); if (!role) return (await restorePwaSession()) as { user: AdminAccount | Employee }; try { return await requestWithRetry<{ user: AdminAccount | Employee }>("/api/me", {}, 5, role); } catch (error) { try { return (await restorePwaSession(role)) as { user: AdminAccount | Employee }; } catch { throw error; } } }

export async function getBackendEmployees() { return requestWithRetry<Employee[]>("/api/employees", {}, "admin"); }
export async function createBackendEmployee(input: Partial<Employee> & { pin?: string }) { return requestWithRetry<Employee>("/api/employees", { method: "POST", body: JSON.stringify(input) }, "admin"); }
export async function updateBackendEmployee(id: string, input: Partial<Employee> & { pin?: string }) { return requestWithRetry<Employee>(`/api/employees/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(input) }, "admin"); }
export async function deleteBackendEmployee(id: string) { return requestWithRetry<{ ok: boolean }>(`/api/employees/${encodeURIComponent(id)}`, { method: "DELETE" }, "admin"); }

export async function getBackendAttendance(limit = 500): Promise<AttendanceRecord[]> { return requestWithRetry<AttendanceRecord[]>(`/api/attendance?limit=${encodeURIComponent(Math.min(Math.max(Math.floor(limit), 1), 500))}`, {}, "employee"); }
export async function createBackendAttendance(input: Partial<AttendanceRecord>): Promise<{ ok: boolean; record?: AttendanceRecord }> { return requestWithRetry<{ ok: boolean; record?: AttendanceRecord }>("/api/attendance", { method: "POST", body: JSON.stringify(input) }, "employee"); }
export async function getBackendRequests(_scope?: "employee" | "all"): Promise<EmployeeRequest[]> { return requestWithRetry<EmployeeRequest[]>("/api/requests", {}, activeRole()); }
export async function createBackendRequest(input: Omit<EmployeeRequest, "id" | "status" | "createdAt"> | Partial<EmployeeRequest>): Promise<{ ok: boolean; id?: string; status?: string }> { return requestWithRetry<{ ok: boolean; id?: string; status?: string }>("/api/requests", { method: "POST", body: JSON.stringify(input) }, "employee"); }
export async function updateBackendRequest(id: string, status: "approved" | "rejected"): Promise<{ ok: boolean; status: string }> { return requestWithRetry<{ ok: boolean; status: string }>(`/api/requests/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ status }) }, "admin"); }
export async function getBackendAudit(limit = 500): Promise<EscapeEvent[]> { return requestWithRetry<EscapeEvent[]>(`/api/audit?limit=${encodeURIComponent(Math.min(Math.max(Math.floor(limit), 1), 2000))}`, {}, "admin"); }
export async function getBackendSettings(): Promise<Settings> { return requestWithRetry<Settings>("/api/settings", {}, "admin"); }
export async function updateBackendSettings(input: Partial<Settings>): Promise<{ ok: boolean }> { return requestWithRetry<{ ok: boolean }>("/api/settings", { method: "PUT", body: JSON.stringify(input) }, "admin"); }
export async function saveBackendSettings(input: Settings): Promise<{ ok: boolean }> { return updateBackendSettings(input); }
export async function getBackendEmployeeProfile(): Promise<Employee> { const data = await backendMe("employee"); return data.user as Employee; }
export async function getBackendEmployeeLocation(): Promise<{ location: Location }> { const employee = await getBackendEmployeeProfile(); const locations = await requestWithRetry<Location[]>("/api/locations", {}, "employee"); const selected = (employee.locationId ? locations.find((location) => String(location.id) === String(employee.locationId)) : null) || locations.find((location) => String(location.id) === "main") || locations[0]; if (!selected) throw new Error("لا يوجد موقع عمل محفوظ."); return { location: selected }; }
