name = "hadir"
compatibility_date = "2026-08-21"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hadir"
database_id = "REPLACE_WITH_D1_DATABASE_ID"

[[r2_buckets]]
binding = "PROFILE_IMAGES"
bucket_name = "hadir-profile-images"
