name = "hadir-api"
main = "src/index.ts"
compatibility_date = "2026-08-19"

[vars]
APP_ORIGIN = "*"

[secrets]
required = ["JWT_SECRET", "OWNER_USERNAME", "OWNER_PASSWORD"]

[[d1_databases]]
binding = "DB"
database_name = "Hadir"
database_id = "c9a96776-fcaa-4ae0-befa-b8c5a9345ebe"

[observability]
enabled = true
