import { sendUserPush } from "./push";
type Env = { DB: D1Database; JWT_SECRET?: string; APP_ORIGIN?: string; OWNER_RECOVERY_CODE?: string; PROFILE_IMAGES?: R2Bucket; VAPID_PUBLIC_KEY?: string; VAPID_PRIVATE_KEY?: string; VAPID_SUBJECT?: string };
const original = (await import("./recovery")).default;
const uid = () => crypto.randomUUID();
const SESSION_COOKIE = "hadir_session";
const SESSION_MAX_AGE = 60 * 60 * 24 * 365 * 5;
const json = (data: unknown, status = 200, origin = "*") => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": origin, "access-control-allow-credentials": "true", "access-control-allow-headers": "content-type, authorization, x-device-id", "access-control-allow-methods": "GET,POST,PATCH,PUT,DELETE,OPTIONS", "cache-control": "no-store" } });
function requestOrigin(req: Request, env: Env) { const configured = String(env.APP_ORIGIN || "").trim().replace(/\/$/, ""); const incoming = String(req.headers.get("origin") || "").trim().replace(/\/$/, ""); return configured || incoming || "*"; }
function withSessionCookie(response: Response, token: string | null, origin = "*"): Response {
  const headers = new Headers(response.headers);
  headers.set("cache-control", "no-store");
  headers.set("access-control-allow-origin", origin);
  headers.set("access-control-allow-credentials", "true");
  headers.set("access-control-allow-headers", "content-type, authorization, x-device-id");
  headers.set("access-control-allow-methods", "GET,POST,PATCH,PUT,DELETE,OPTIONS");
  if (token) headers.set("set-cookie", `${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; Max-Age=${SESSION_MAX_AGE}; HttpOnly; Secure; SameSite=None`);
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}
async function actorFromOriginal(req: Request, env: Env) { const url = new URL(req.url); url.pathname = "/api/me"; url.search = ""; const probe = await original.fetch(new Request(url, { method: "GET", headers: req.headers }), env, {} as ExecutionContext); if (!probe.ok) return null; return (await probe.json().catch(() => ({})) as any).user || null; }
async function ensureWorkflowSchema(db: D1Database) { await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'info',read_at TEXT,created_at TEXT NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id,created_at DESC)"),db.prepare("CREATE TABLE IF NOT EXISTS push_subscriptions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,endpoint TEXT NOT NULL UNIQUE,p256dh TEXT NOT NULL,auth TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions(user_id)")]); }
async function notify(db: D1Database, userId: string, title: string, message: string, type = "info", env?: Env, url = "/") {
  const id = uid(); const now = new Date().toISOString();
  await db.prepare("INSERT INTO notifications(id,user_id,title,message,type,created_at) VALUES(?,?,?,?,?,?)").bind(id, userId, title, message, type, now).run();
  if (!env) return;
  const rows = await db.prepare("SELECT id,endpoint,p256dh,auth FROM push_subscriptions WHERE user_id=?").bind(userId).all<any>();
  for (const row of rows.results || []) {
    const result = await sendUserPush(env, { endpoint: String(row.endpoint), keys: { p256dh: String(row.p256dh), auth: String(row.auth) } }, { title, body: message, url, type, tag: `hadir-${type}` });
    if (result.status === 404 || result.status === 410) await db.prepare("DELETE FROM push_subscriptions WHERE id=?").bind(row.id).run().catch(()=>undefined);
  }
}
function avatarKey(employeeId: string) { return `employees/${employeeId}/avatar.webp`; }
const EARTH_RADIUS_METERS = 6371000;
function coordinate(value: unknown) { const n = Number(value); return Number.isFinite(n) ? Number(n.toFixed(7)) : NaN; }
function distanceMeters(aLat: number, aLng: number, bLat: number, bLng: number) { const lat1=aLat*Math.PI/180,lat2=bLat*Math.PI/180,dLat=(bLat-aLat)*Math.PI/180,dLng=(bLng-aLng)*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return Number((EARTH_RADIUS_METERS*2*Math.atan2(Math.sqrt(Math.min(1,Math.max(0,h))),Math.sqrt(1-Math.min(1,Math.max(0,h))))).toFixed(2)); }
async function currentEmployeeLocation(db: D1Database, employeeId: string) { const employee=await db.prepare("SELECT id,job_number AS jobNumber,name,location_id AS locationId,status FROM employees WHERE id=? AND status='active' LIMIT 1").bind(employeeId).first<any>(); if(!employee)return null; const rows=await db.prepare("SELECT id,name,lat,lng,radius_meters AS radiusMeters FROM locations ORDER BY name").all<any>(); const list=rows.results||[]; const selected=(employee.locationId?list.find((x:any)=>String(x.id)===String(employee.locationId)):null)||list.find((x:any)=>String(x.id)==="main")||list[0]; if(!selected)return null; const lat=coordinate(selected.lat),lng=coordinate(selected.lng),radius=Number(Number(selected.radiusMeters).toFixed(2)); if(!Number.isFinite(lat)||!Number.isFinite(lng)||!Number.isFinite(radius)||radius<=0)return null; return {employee,location:{id:String(selected.id),name:String(selected.name||"الموقع"),lat,lng,radiusMeters:radius}}; }
async function handleAttendance(req: Request, env: Env, actor: any, origin: string) {
  if (actor?.role !== "staff") return json({error:"الموظف فقط يستطيع تسجيل الحضور"},403,origin);
  if (req.method === "GET") { const limit=Math.min(Math.max(Number(new URL(req.url).searchParams.get("limit")||100),1),500); const rows=await env.DB.prepare("SELECT id,employee_id AS employeeId,job_number AS jobNumber,employee_name AS employeeName,type,timestamp,lat,lng,distance_meters AS distanceMeters,device_id AS deviceId,ip,qr_code AS qrCode,location_id AS locationId FROM attendance WHERE employee_id=? ORDER BY timestamp DESC LIMIT ?").bind(actor.id,limit).all<any>(); return json(rows.results||[],200,origin); }
  if (req.method !== "POST") return json({error:"الطريقة غير مدعومة"},405,origin);
  const b=await req.json().catch(()=>({})) as any; const type=String(b.type||""); if(type!=="check-in"&&type!=="check-out")return json({error:"نوع الحضور غير صحيح"},400,origin);
  const lat=coordinate(b.lat),lng=coordinate(b.lng); if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)return json({error:"إحداثيات GPS غير صالحة"},400,origin);
  const fresh=await currentEmployeeLocation(env.DB,actor.id); if(!fresh)return json({error:"لا يوجد موقع عمل صالح محفوظ في D1"},409,origin);
  const distance=distanceMeters(lat,lng,fresh.location.lat,fresh.location.lng); if(distance>fresh.location.radiusMeters)return json({error:`أنت خارج نطاق موقع العمل. المسافة ${distance} م، والنطاق ${fresh.location.radiusMeters} م.`},403,origin);
  const last=await env.DB.prepare("SELECT type,timestamp FROM attendance WHERE employee_id=? ORDER BY timestamp DESC LIMIT 1").bind(actor.id).first<any>(); if(last?.type===type)return json({error:type==="check-in"?"تم تسجيل الحضور بالفعل":"تم تسجيل الانصراف بالفعل"},409,origin);
  if(type==="check-out"&&last?.type!=="check-in")return json({error:"لا يمكن تسجيل الانصراف قبل تسجيل الحضور"},409,origin);
  const deviceId=String(req.headers.get("x-device-id")||b.deviceId||"unknown").trim()||"unknown"; const ip=req.headers.get("CF-Connecting-IP")||"unknown"; const id=uid(); const timestamp=new Date().toISOString(); await env.DB.prepare("INSERT INTO attendance(id,employee_id,job_number,employee_name,type,timestamp,lat,lng,distance_meters,device_id,ip,qr_code,location_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,actor.id,fresh.employee.jobNumber,fresh.employee.name,type,timestamp,lat,lng,distance,deviceId,ip,String(b.qrCode||""),fresh.location.id).run(); await env.DB.prepare("INSERT INTO audit(id,employee_id,job_number,actor_name,action,result,reason,timestamp,device_id,ip,lat,lng,distance_meters) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(uid(),actor.id,fresh.employee.jobNumber,fresh.employee.name,type,"success",null,timestamp,deviceId,ip,lat,lng,distance).run().catch(()=>undefined); return json({ok:true,record:{id,employeeId:actor.id,jobNumber:fresh.employee.jobNumber,employeeName:fresh.employee.name,type,timestamp,lat,lng,distanceMeters:distance,deviceId,ip,qrCode:String(b.qrCode||""),locationId:fresh.location.id}},201,origin);
}
export default { async fetch(req: Request, env: Env, ctx: ExecutionContext) {
 const origin=requestOrigin(req,env); if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":origin,"access-control-allow-credentials":"true","access-control-allow-headers":"content-type, authorization, x-device-id","access-control-allow-methods":"GET,POST,PATCH,PUT,DELETE,OPTIONS","access-control-max-age":"86400"}});
 if(!env.DB)return json({ok:false,error:"D1 binding DB غير موجود"},503,origin);
 await ensureWorkflowSchema(env.DB); const url=new URL(req.url); const path=url.pathname.replace(/\/$/,"")||"/"; const actor=await actorFromOriginal(req,env);
 if(path==="/api/auth/login"&&req.method==="POST"){const response=await original.fetch(req,env,ctx);const clone=response.clone();const data=await clone.json().catch(()=>({})) as any;return withSessionCookie(response, response.ok&&typeof data.token==="string"?data.token:null, origin);}
 if(path==="/api/bootstrap/owner"&&req.method==="POST"){const response=await original.fetch(req,env,ctx);const clone=response.clone();const data=await clone.json().catch(()=>({})) as any;return withSessionCookie(response, response.ok&&typeof data.token==="string"?data.token:null, origin);}
 const avatarMatch=path.match(/^\/api\/employees\/([^/]+)\/avatar$/);
 if(avatarMatch && req.method==="POST") {
   if(!env.PROFILE_IMAGES)return json({ok:false,error:"R2 binding PROFILE_IMAGES غير موجود"},503,origin);
   if(!actor || !["owner","manager"].includes(actor.role)) return json({error:"المالك أو المدير فقط"},403,origin);
   const employeeId=decodeURIComponent(avatarMatch[1]); const employee=await env.DB.prepare("SELECT id,avatar FROM employees WHERE id=? LIMIT 1").bind(employeeId).first<any>(); if(!employee)return json({error:"EMPLOYEE_NOT_FOUND"},404,origin);
   const contentType=req.headers.get("content-type")||""; if(!contentType.toLowerCase().includes("multipart/form-data"))return json({error:"MULTIPART_FORM_DATA_REQUIRED"},415,origin);
   const form=await req.formData();const file=form.get("file");if(!(file instanceof File))return json({error:"IMAGE_FILE_REQUIRED"},400,origin);if(file.type!=="image/webp")return json({error:"WEBP_REQUIRED"},415,origin);if(file.size===0||file.size>100*1024)return json({error:"IMAGE_TOO_LARGE",maxBytes:100*1024},413,origin);
   const key=avatarKey(employeeId);await env.PROFILE_IMAGES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:"image/webp",cacheControl:"private, max-age=31536000, immutable"},customMetadata:{employeeId}});try{await env.DB.prepare("UPDATE employees SET avatar=? WHERE id=?").bind(key,employeeId).run();}catch(error){await env.PROFILE_IMAGES.delete(key).catch(()=>undefined);return json({error:"AVATAR_DB_UPDATE_FAILED",detail:error instanceof Error?error.message:String(error)},500,origin);}return json({ok:true,key,size:file.size,contentType:"image/webp"},200,origin);
 }
 if(avatarMatch&&req.method==="GET"){if(!env.PROFILE_IMAGES)return json({ok:false,error:"R2 binding PROFILE_IMAGES غير موجود"},503,origin);if(!actor)return json({error:"غير مصرح"},401,origin);const employeeId=decodeURIComponent(avatarMatch[1]);if(actor.role==="staff"&&actor.id!==employeeId)return json({error:"غير مصرح"},403,origin);const row=await env.DB.prepare("SELECT avatar FROM employees WHERE id=? LIMIT 1").bind(employeeId).first<{avatar:string|null}>();if(!row)return json({error:"EMPLOYEE_NOT_FOUND"},404,origin);if(!row.avatar)return new Response(null,{status:404,headers:{"access-control-allow-origin":origin}});const object=await env.PROFILE_IMAGES.get(row.avatar);if(!object)return new Response(null,{status:404,headers:{"access-control-allow-origin":origin}});const headers=new Headers({"access-control-allow-origin":origin,"access-control-allow-credentials":"true","cache-control":"private, max-age=300"});object.writeHttpMetadata(headers);headers.set("etag",object.httpEtag);return new Response(object.body,{status:200,headers});}
 if(avatarMatch&&req.method==="DELETE"){if(!env.PROFILE_IMAGES)return json({ok:false,error:"R2 binding PROFILE_IMAGES غير موجود"},503,origin);if(!actor||!["owner","manager"].includes(actor.role))return json({error:"المالك أو المدير فقط"},403,origin);const employeeId=decodeURIComponent(avatarMatch[1]);const row=await env.DB.prepare("SELECT avatar FROM employees WHERE id=? LIMIT 1").bind(employeeId).first<{avatar:string|null}>();if(!row)return json({error:"EMPLOYEE_NOT_FOUND"},404,origin);if(row.avatar)await env.PROFILE_IMAGES.delete(row.avatar);await env.DB.prepare("UPDATE employees SET avatar=NULL WHERE id=?").bind(employeeId).run();return json({ok:true},200,origin);}
 if(path==="/api/push/public-key"&&req.method==="GET"){ return json({configured:Boolean(String(env.VAPID_PUBLIC_KEY||"").trim()),publicKey:String(env.VAPID_PUBLIC_KEY||"").trim()||null},200,origin); }
if(path==="/api/push/subscription"&&(req.method==="POST"||req.method==="DELETE")){
  if(!actor)return json({error:"غير مصرح"},401,origin);
  if(req.method==="DELETE"){ const b=await req.json().catch(()=>({})) as any; const endpoint=String(b.endpoint||"").trim(); if(endpoint) await env.DB.prepare("DELETE FROM push_subscriptions WHERE user_id=? AND endpoint=?").bind(actor.id,endpoint).run(); else await env.DB.prepare("DELETE FROM push_subscriptions WHERE user_id=?").bind(actor.id).run(); return json({ok:true},200,origin); }
  const b=await req.json().catch(()=>({})) as any; const subscription=b.subscription||b; const endpoint=String(subscription.endpoint||"").trim(); const p256dh=String(subscription?.keys?.p256dh||"").trim(); const auth=String(subscription?.keys?.auth||"").trim(); if(!endpoint||!p256dh||!auth)return json({error:"اشتراك Push غير صالح"},400,origin);
  if(!/^https:\/\//i.test(endpoint))return json({error:"عنوان Push غير صالح"},400,origin);
  const now=new Date().toISOString(); await env.DB.prepare("INSERT INTO push_subscriptions(id,user_id,endpoint,p256dh,auth,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,updated_at=excluded.updated_at").bind(uid(),actor.id,endpoint,p256dh,auth,now,now).run(); return json({ok:true},200,origin);
}
 if(path==="/api/attendance")return handleAttendance(req,env,actor,origin);
 if(path==="/api/audit"&&req.method==="GET"){if(!actor||!["owner","manager","supervisor"].includes(actor.role))return json({error:"غير مصرح"},403,origin);const limit=Math.min(Math.max(Number(url.searchParams.get("limit")||500),1),2000);const rows=await env.DB.prepare("SELECT id,employee_id AS employeeId,job_number AS jobNumber,actor_name AS actorName,action,result,reason,timestamp,device_id AS deviceId,ip,lat,lng,distance_meters AS distanceMeters FROM audit ORDER BY timestamp DESC LIMIT ?").bind(limit).all<any>();return json(rows.results||[],200,origin);}
 if(path==="/api/settings"&&req.method==="GET"){if(!actor||!["owner","manager","supervisor"].includes(actor.role))return json({error:"غير مصرح"},403,origin);const rows=await env.DB.prepare("SELECT key,value FROM settings ORDER BY key").all<any>();const out:any={};for(const r of rows.results||[]){try{out[r.key]=JSON.parse(r.value)}catch{out[r.key]=r.value}}return json(out,200,origin);}
 if(path==="/api/settings"&&req.method==="PUT"){if(!actor||!["owner","manager"].includes(actor.role))return json({error:"المالك أو المدير فقط"},403,origin);const b=await req.json().catch(()=>({})) as Record<string,unknown>;const entries=Object.entries(b).filter(([k])=>k!=="ownerPasswordHash");for(const [key,value] of entries)await env.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,JSON.stringify(value)).run();return json({ok:true},200,origin);}
 if(path==="/api/locations"&&req.method==="GET"){if(!actor||!["owner","manager","supervisor","staff"].includes(actor.role))return json({error:"غير مصرح"},403,origin);const rows=await env.DB.prepare("SELECT id,name,lat,lng,radius_meters AS radiusMeters FROM locations ORDER BY name").all<any>();return json(rows.results||[],200,origin);}
 if(path==="/api/locations"&&req.method==="PUT"){if(!actor||!["owner","manager"].includes(actor.role))return json({error:"المالك أو المدير فقط"},403,origin);const b=await req.json().catch(()=>({})) as any;const id=String(b.id||uid()),name=String(b.name||"").trim(),lat=coordinate(b.lat),lng=coordinate(b.lng),radiusMeters=Number(Number(b.radiusMeters).toFixed(2));if(!name||!Number.isFinite(lat)||!Number.isFinite(lng)||!Number.isFinite(radiusMeters)||radiusMeters<=0)return json({error:"بيانات الموقع غير صحيحة"},400,origin);await env.DB.prepare("INSERT INTO locations(id,name,lat,lng,radius_meters) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,lat=excluded.lat,lng=excluded.lng,radius_meters=excluded.radius_meters").bind(id,name,lat,lng,radiusMeters).run();return json({ok:true,location:{id,name,lat,lng,radiusMeters}},200,origin);}
 if(path.startsWith("/api/locations/")&&req.method==="DELETE"){if(!actor||!["owner","manager"].includes(actor.role))return json({error:"المالك أو المدير فقط"},403,origin);const id=decodeURIComponent(path.slice("/api/locations/".length));await env.DB.prepare("UPDATE employees SET location_id=NULL WHERE location_id=?").bind(id).run();await env.DB.prepare("DELETE FROM locations WHERE id=?").bind(id).run();return json({ok:true},200,origin);}
 if(path==="/api/notifications"&&req.method==="GET"){if(!actor)return json({error:"غير مصرح"},401,origin);const rows=await env.DB.prepare("SELECT id,user_id AS userId,title,message,type,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100").bind(actor.id).all();return json(rows.results||[],200,origin);}
 if(path==="/api/notifications/read"&&req.method==="POST"){if(!actor)return json({error:"غير مصرح"},401,origin);const b=await req.json().catch(()=>({})) as any;if(b.id)await env.DB.prepare("UPDATE notifications SET read_at=? WHERE id=? AND user_id=?").bind(new Date().toISOString(),String(b.id),actor.id).run();else await env.DB.prepare("UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL").bind(new Date().toISOString(),actor.id).run();return json({ok:true},200,origin);}
 const requestMatch=path.match(/^\/api\/requests\/([^/]+)$/);const confirmMatch=path.match(/^\/api\/requests\/([^/]+)\/confirm$/);
 if(path==="/api/requests"&&req.method==="GET"){if(!actor||!["owner","manager","supervisor","staff"].includes(actor.role))return json({error:"غير مصرح"},401,origin);const rows=actor.role==="staff"?await env.DB.prepare("SELECT id,employee_id AS employeeId,employee_name AS employeeName,job_number AS jobNumber,type,reason,status,created_at AS createdAt FROM requests WHERE employee_id=? ORDER BY created_at DESC LIMIT 200").bind(actor.id).all():await env.DB.prepare("SELECT id,employee_id AS employeeId,employee_name AS employeeName,job_number AS jobNumber,type,reason,status,created_at AS createdAt FROM requests ORDER BY created_at DESC LIMIT 500").all();return json(rows.results||[],200,origin);}
 if(path==="/api/requests"&&req.method==="POST"){if(!actor||actor.role!=="staff")return json({error:"الموظف فقط يستطيع إنشاء الطلب"},403,origin);const b=await req.json().catch(()=>({})) as any;const type=String(b.type||b.requestType||"");if(!["permission","leave","checkout"].includes(type))return json({error:"نوع الطلب غير صحيح"},400,origin);const employee=await env.DB.prepare("SELECT job_number AS jobNumber,name FROM employees WHERE id=? AND status='active' LIMIT 1").bind(actor.id).first<any>();if(!employee)return json({error:"الموظف غير موجود"},404,origin);const id=uid();await env.DB.prepare("INSERT INTO requests(id,employee_id,employee_name,job_number,type,reason,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(id,actor.id,employee.name,employee.jobNumber,type,String(b.reason||""),"pending",new Date().toISOString()).run();const admins=await env.DB.prepare("SELECT id FROM admin_accounts WHERE active=1 AND role IN ('owner','manager')").all<any>();for(const a of admins.results||[])await notify(env.DB,a.id,"طلب موظف جديد",`${employee.name} أرسل طلب ${type==="permission"?"استئذان":type==="leave"?"إجازة":"انصراف"}.`,"info");return json({ok:true,id,status:"pending"},201,origin);}
 if(requestMatch&&req.method==="PATCH"){if(!actor||!["owner","manager"].includes(actor.role))return json({error:"غير مصرح"},403,origin);const id=requestMatch[1];const b=await req.json().catch(()=>({})) as any;const status=String(b.status||"");if(!["approved","rejected"].includes(status))return json({error:"حالة غير صحيحة"},400,origin);const r=await env.DB.prepare("SELECT employee_id AS employeeId FROM requests WHERE id=? AND status='pending' LIMIT 1").bind(id).first<any>();if(!r)return json({error:"الطلب غير موجود أو تمت مراجعته"},409,origin);await env.DB.prepare("UPDATE requests SET status=? WHERE id=? AND status='pending'").bind(status,id).run();await notify(env.DB,r.employeeId,status==="approved"?"تمت الموافقة":"تم رفض الطلب",status==="approved"?"تمت الموافقة من قبل المدير أو المالك، يمكنك الآن تأكيد العملية.":"تم رفض طلبك من قبل المدير أو المالك.",status==="approved"?"success":"warning");return json({ok:true,status},200,origin);}
 if(confirmMatch&&req.method==="POST"){if(!actor||actor.role!=="staff")return json({error:"غير مصرح"},403,origin);const id=confirmMatch[1];const result=await env.DB.prepare("UPDATE requests SET status='confirmed' WHERE id=? AND employee_id=? AND status='approved'").bind(id,actor.id).run();if(!result.meta.changes)return json({error:"لا يمكن التأكيد قبل موافقة المدير"},403,origin);return json({ok:true,status:"confirmed"},200,origin);}
 const response=await original.fetch(req,env,ctx); return response;
}};