export type AttendanceShift = { start: Date; end: Date; isWorkDay: boolean; kind: "ADMIN" | "ROTATION" };
const DAY_MS = 86_400_000;
const DEFAULT_TZ = "Asia/Damascus";
function parts(date: Date, tz: string) { const p = new Intl.DateTimeFormat("en-US", { timeZone: tz, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(date); const get=(t:string)=>p.find(x=>x.type===t)?.value||""; return {year:Number(get("year")),month:Number(get("month")),day:Number(get("day")),weekday:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(get("weekday")),hour:Number(get("hour"))%24,minute:Number(get("minute"))}; }
export function dateKey(date: Date, tz = DEFAULT_TZ) { const p=parts(date,tz); return `${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`; }
function dayNumber(day:string){return Date.UTC(Number(day.slice(0,4)),Number(day.slice(5,7))-1,Number(day.slice(8,10)))/DAY_MS;}
function addDays(day:string,n:number){return new Date((dayNumber(day)+n)*DAY_MS).toISOString().slice(0,10);}
function wallClockAsUtc(date:Date,tz:string){const p=parts(date,tz);return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute);}
export function localDateTime(day:string,value:string|null|undefined,tz=DEFAULT_TZ){
  const m=/^(\d{1,2}):(\d{2})$/.exec(String(value||""));
  const h=Math.min(23,Math.max(0,Number(m?.[1]??9))),minute=Math.min(59,Math.max(0,Number(m?.[2]??0)));
  const wallTime=Date.UTC(Number(day.slice(0,4)),Number(day.slice(5,7))-1,Number(day.slice(8,10)),h,minute);
  const offsets=new Set<number>();
  for(const delta of [-36,-12,0,12,36]){const probe=new Date(wallTime+delta*60*60*1000);offsets.add(Math.round((wallClockAsUtc(probe,tz)-Math.floor(probe.getTime()/60000)*60000)/60000));}
  const candidates=[...offsets].map(offset=>new Date(wallTime-offset*60000));
  const exact=candidates.filter(candidate=>wallClockAsUtc(candidate,tz)===wallTime);
  if(exact.length)return exact.sort((a,b)=>a.getTime()-b.getTime())[0];
  // If the configured wall time is skipped by a DST gap, move forward by the gap.
  const after=candidates.map(candidate=>({candidate,wall:wallClockAsUtc(candidate,tz)})).filter(item=>item.wall>wallTime).sort((a,b)=>(a.wall-b.wall)||(a.candidate.getTime()-b.candidate.getTime()));
  return after[0]?.candidate||candidates[0]||new Date(wallTime);
}
function validTime(value:unknown){return /^(\d{1,2}):(\d{2})$/.test(String(value||""));}
function workDays(employee:any){try{const parsed=JSON.parse(String(employee.workDaysJson||"[]"));if(Array.isArray(parsed)){const values=[...new Set(parsed.map(Number).filter((n:number)=>Number.isInteger(n)&&n>=0&&n<=6))];if(values.length)return values;}}catch{}return[0,1,2,3,4];}
function rotationShiftForDay(employee:any,periodStartDay:string,tz:string):AttendanceShift{const time=employee.workStartTime||"09:00";const start=localDateTime(periodStartDay,time,tz);const on=Math.max(1,Math.floor(Number(employee.rotationDaysOn??4)));const end=localDateTime(addDays(periodStartDay,on),time,tz);return{start,end,isWorkDay:true,kind:"ROTATION"};}
export function getAttendanceShift(employee:any,instant=new Date(),tz=DEFAULT_TZ):AttendanceShift{const kind=String(employee?.scheduleType||"ADMIN").trim().toUpperCase();if(kind==="ROTATION"){const startDay=String(employee.rotationStartDate||"").slice(0,10),on=Math.max(1,Math.floor(Number(employee.rotationDaysOn??4))),off=Math.max(0,Math.floor(Number(employee.rotationDaysOff??4)));if(!/^\d{4}-\d{2}-\d{2}$/.test(startDay)||!validTime(employee.workStartTime)||on+off<=0)return{start:instant,end:instant,isWorkDay:false,kind:"ROTATION"};const firstStart=localDateTime(startDay,employee.workStartTime,tz);if(instant.getTime()<firstStart.getTime())return{start:firstStart,end:firstStart,isWorkDay:false,kind:"ROTATION"};const targetDay=dateKey(instant,tz),diff=Math.floor(dayNumber(targetDay)-dayNumber(startDay)),cycle=on+off,cycleIndex=Math.floor(diff/cycle),cycleDay=diff-cycleIndex*cycle,periodStartDay=addDays(startDay,cycleIndex*cycle),shift=rotationShiftForDay(employee,periodStartDay,tz);if(cycleDay<on)return shift;if(cycleDay===on&&instant.getTime()<shift.end.getTime())return shift;const nextStart=localDateTime(addDays(periodStartDay,cycle),employee.workStartTime,tz);return{start:nextStart,end:nextStart,isWorkDay:false,kind:"ROTATION"};}
const today=dateKey(instant,tz),yesterday=addDays(today,-1);for(const day of [today,yesterday]){const start=localDateTime(day,employee.workStartTime||"09:00",tz),rawEnd=localDateTime(day,employee.workEndTime||"16:00",tz),end=rawEnd.getTime()<=start.getTime()?localDateTime(addDays(day,1),employee.workEndTime||"16:00",tz):rawEnd;if(workDays(employee).includes(parts(start,tz).weekday)&&instant.getTime()>=start.getTime()&&instant.getTime()<=end.getTime()+60000)return{start,end,isWorkDay:true,kind:"ADMIN"};}const start=localDateTime(today,employee.workStartTime||"09:00",tz),endTime=employee.workEndTime||"16:00",rawEnd=localDateTime(today,endTime,tz),end=rawEnd.getTime()<=start.getTime()?localDateTime(addDays(today,1),endTime,tz):rawEnd;return{start,end,isWorkDay:workDays(employee).includes(parts(start,tz).weekday),kind:"ADMIN"};}
export function getAttendanceShiftForDay(employee:any,day:string,tz=DEFAULT_TZ):AttendanceShift{const kind=String(employee?.scheduleType||"ADMIN").trim().toUpperCase();if(kind==="ROTATION"){const startDay=String(employee.rotationStartDate||"").slice(0,10),on=Math.max(1,Math.floor(Number(employee.rotationDaysOn??4))),off=Math.max(0,Math.floor(Number(employee.rotationDaysOff??4)));if(!/^\d{4}-\d{2}-\d{2}$/.test(startDay)||on+off<=0)return{start:localDateTime(day,employee.workStartTime,tz),end:localDateTime(day,employee.workEndTime,tz),isWorkDay:false,kind:"ROTATION"};const diff=Math.floor(dayNumber(day)-dayNumber(startDay));if(diff<0)return{start:localDateTime(day,employee.workStartTime,tz),end:localDateTime(day,employee.workEndTime,tz),isWorkDay:false,kind:"ROTATION"};const cycle=on+off,cycleIndex=Math.floor(diff/cycle),cycleDay=diff-cycleIndex*cycle,periodStartDay=addDays(startDay,cycleIndex*cycle),period=rotationShiftForDay(employee,periodStartDay,tz);return{...period,isWorkDay:cycleDay<on};}const start=localDateTime(day,employee.workStartTime||"09:00",tz),rawEnd=localDateTime(day,employee.workEndTime||"16:00",tz),end=rawEnd.getTime()<=start.getTime()?localDateTime(addDays(day,1),employee.workEndTime||"16:00",tz):rawEnd;return{start,end,isWorkDay:workDays(employee).includes(parts(start,tz).weekday),kind:"ADMIN"};}
