import { dateKey, getAttendanceShiftForDay, localDateTime } from "./attendance-period";
type Env={DB:D1Database;APP_ORIGIN?:string};
const TZ="Asia/Damascus";const DAY_MS=86400000;
type Status="PRESENT"|"LATE"|"ABSENT"|"REST"|"LEAVE"|"PERMISSION"|"NOT_STARTED"|"INVALID";
type Employee={id:string;name:string;jobNumber:string;status:string;scheduleType:string;workStartTime:string|null;workEndTime:string|null;workDaysJson:string|null;rotationStartDate:string|null;rotationDaysOn:number|null;rotationDaysOff:number|null;gracePeriodMinutes:number|null;isVip:number|null};
type Stored={employeeId:string;status:string;checkInAt:string|null;checkOutAt:string|null;scheduleType:string};
const HEAD={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"GET, OPTIONS","cache-control":"no-store"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...HEAD}});
const dayNumber=(d:string)=>Date.UTC(+d.slice(0,4),+d.slice(5,7)-1,+d.slice(8,10))/DAY_MS;
const addDays=(d:string,n:number)=>new Date((dayNumber(d)+n)*DAY_MS).toISOString().slice(0,10);
const local=(d:string,t:string|null|undefined)=>localDateTime(d,t,TZ);
function workDays(e:Employee){try{const v=JSON.parse(e.workDaysJson||"[]");if(Array.isArray(v)){const a=[...new Set(v.map(Number).filter((n:number)=>Number.isInteger(n)&&n>=0&&n<=6))];if(a.length)return a;}}catch{}return[0,1,2,3,4];}
function weekday(d:string){return new Date(dayNumber(d)*DAY_MS).getUTCDay();}
function shiftForDay(e:Employee,d:string){const s=getAttendanceShiftForDay(e,d,TZ);return s.kind==="ADMIN"?{...s,isWorkDay:workDays(e).includes(weekday(d))}:s;}
export async function handleDailyStatus(req:Request,env:Env,actor:any){
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:HEAD});if(req.method!=="GET")return json({error:"الطريقة غير مدعومة"},405);if(!actor||!["owner","manager","supervisor"].includes(String(actor.role)))return json({error:"غير مصرح"},403);
 const u=new URL(req.url),q=String(u.searchParams.get("date")||"").trim(),day=/^\d{4}-\d{2}-\d{2}$/.test(q)?q:dateKey(new Date(),TZ),next=addDays(day,1),dayStart=local(day,"00:00"),dayEnd=local(next,"00:00"),from=local(addDays(day,-8),"00:00"),to=local(addDays(day,9),"00:00");
 try{
  const er=await env.DB.prepare("SELECT e.id,e.name,e.job_number AS jobNumber,e.status,e.schedule_type AS scheduleType,e.work_start_time AS workStartTime,e.work_end_time AS workEndTime,e.work_days_json AS workDaysJson,e.rotation_start_date AS rotationStartDate,e.rotation_days_on AS rotationDaysOn,e.rotation_days_off AS rotationDaysOff,e.grace_period_minutes AS gracePeriodMinutes,e.is_vip AS isVip FROM employees e WHERE e.status='active' OR EXISTS (SELECT 1 FROM attendance a WHERE a.employee_id=e.id AND a.timestamp>=? AND a.timestamp<?) ORDER BY e.name").bind(dayStart.toISOString(),dayEnd.toISOString()).all<Employee>();
  const ar=await env.DB.prepare("SELECT id,employee_id AS employeeId,type,timestamp FROM attendance WHERE timestamp>=? AND timestamp<? ORDER BY timestamp ASC").bind(from.toISOString(),to.toISOString()).all<any>();
  const rr=await env.DB.prepare("SELECT employee_id AS employeeId,type,status,start_date AS startDate,end_date AS endDate,created_at AS createdAt FROM requests WHERE status IN ('approved','confirmed') AND type IN ('leave','permission')").all<any>();
  const employees=er.results||[],events=ar.results||[],requests=rr.results||[];const by=new Map<string,any[]>();for(const r of events){const id=String(r.employeeId||"");if(id){const a=by.get(id)||[];a.push(r);by.set(id,a);}}
  const active=(r:any)=>{const s=String(r.startDate||r.createdAt||"").slice(0,10),e=String(r.endDate||r.startDate||r.createdAt||"").slice(0,10);return s<=day&&day<=e;};const leave=new Set(requests.filter((r:any)=>String(r.type).toLowerCase()==="leave"&&active(r)).map((r:any)=>String(r.employeeId)));const permission=new Set(requests.filter((r:any)=>String(r.type).toLowerCase()==="permission"&&active(r)).map((r:any)=>String(r.employeeId)));
  const now=new Date(),today=dateKey(now,TZ);const result=employees.map(e=>{const id=String(e.id),s=shiftForDay(e,day);let cin:any=null,cout:any=null;if(s.isWorkDay){const list=by.get(id)||[];const pe=list.filter(r=>{const t=Date.parse(String(r.timestamp));return Number.isFinite(t)&&t>=s.start.getTime()&&t<=s.end.getTime()&&(!(day===today)||t<=now.getTime());});cin=pe.find(r=>String(r.type)==="check-in")||null;cout=[...pe].reverse().find(r=>String(r.type)==="check-out")||null;if(!cin){const hist=events.filter(r=>String(r.employeeId)===id).filter(r=>{const t=Date.parse(String(r.timestamp));return Number.isFinite(t)&&t>=s.start.getTime()&&t<=s.end.getTime()&&(!(day===today)||t<=now.getTime());});cin=hist.find(r=>String(r.type)==="check-in")||null;cout=cout||[...hist].reverse().find(r=>String(r.type)==="check-out")||null;}}
   let status:Status;if(leave.has(id))status="LEAVE";else if(permission.has(id))status="PERMISSION";else if(!s.isWorkDay)status="REST";else if(day===today&&now.getTime()<s.start.getTime())status="NOT_STARTED";else if(cin){const grace=Math.max(0,Number.isFinite(Number(e.gracePeriodMinutes))?Number(e.gracePeriodMinutes):10);status=s.kind==="ROTATION"?"PRESENT":(Date.parse(String(cin.timestamp))>s.start.getTime()+grace*60000?"LATE":"PRESENT");}else status="ABSENT";
   return{attendanceDay:day,employeeId:id,employeeName:String(e.name||""),jobNumber:String(e.jobNumber||""),status,scheduleType:String(e.scheduleType||"ADMIN").toUpperCase(),checkInAt:cin?.timestamp||null,checkOutAt:cout?.timestamp||null,scheduledStart:s.start?.toISOString()||null,scheduledEnd:s.end?.toISOString()||null};});
  const computedAt=new Date().toISOString();if(result.length){const sr=await env.DB.prepare("SELECT employee_id AS employeeId,status,check_in_at AS checkInAt,check_out_at AS checkOutAt,schedule_type AS scheduleType FROM daily_attendance_status WHERE attendance_day=?").bind(day).all<Stored>();const old=new Map((sr.results||[]).map(r=>[String(r.employeeId),r]));const changed=result.filter(r=>{const p=old.get(r.employeeId);return !p||p.status!==r.status||String(p.checkInAt||"")!==String(r.checkInAt||"")||String(p.checkOutAt||"")!==String(r.checkOutAt||"")||p.scheduleType!==r.scheduleType;});if(changed.length)await env.DB.batch(changed.map(r=>env.DB.prepare("INSERT INTO daily_attendance_status(attendance_day,employee_id,status,check_in_at,check_out_at,schedule_type,computed_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(attendance_day,employee_id) DO UPDATE SET status=excluded.status,check_in_at=excluded.check_in_at,check_out_at=excluded.check_out_at,schedule_type=excluded.schedule_type,computed_at=excluded.computed_at").bind(r.attendanceDay,r.employeeId,r.status,r.checkInAt,r.checkOutAt,r.scheduleType,computedAt)));}
  const counts=result.reduce<Record<string,number>>((a,r)=>{a[r.status]=(a[r.status]||0)+1;return a;},{});return json({attendanceDay:day,timezone:TZ,computedAt,total:result.length,counts,employees:result});
 }catch(error){console.error("daily-status canonical failed",error);return json({error:"تعذر قراءة حالة الدوام من D1"},500);}
}