type Env = { DB: D1Database };
const TZ = "Asia/Damascus";
const json = (data: unknown, status = 200, origin = "*") => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": origin, "access-control-allow-credentials": "true", "access-control-allow-headers": "content-type, authorization, x-device-id", "access-control-allow-methods": "GET,POST,PATCH,PUT,DELETE,OPTIONS", "cache-control": "no-store" } });
function coordinate(value: unknown) { const n = Number(value); return Number.isFinite(n) ? Number(n.toFixed(7)) : NaN; }
const EARTH_RADIUS_METERS = 6371000;
function distanceMeters(aLat: number, aLng: number, bLat: number, bLng: number) { const lat1=aLat*Math.PI/180,lat2=bLat*Math.PI/180,dLat=(bLat-aLat)*Math.PI/180,dLng=(bLng-aLng)*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;const safe=Math.min(1,Math.max(0,h));return Number((EARTH_RADIUS_METERS*2*Math.atan2(Math.sqrt(safe),Math.sqrt(1-safe))).toFixed(2)); }
function parts(date: Date) { const p=new Intl.DateTimeFormat("en-US",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(date); const get=(t:string)=>p.find(x=>x.type===t)?.value||""; return {year:Number(get("year")),month:Number(get("month")),day:Number(get("day")),weekday:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(get("weekday")),hour:Number(get("hour"))%24,minute:Number(get("minute"))}; }
function dayKey(date: Date) { const p=parts(date); return `${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`; }
function offsetMinutes(day:string) { const noon=new Date(`${day}T12:00:00Z`); const p=parts(noon); return Math.round((Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute)-noon.getTime())/60000); }
function localDateTime(day:string,time:string|null|undefined) { const m=/^(\d{1,2}):(\d{2})$/.exec(String(time||"")); const h=Number(m?.[1]||9),minute=Number(m?.[2]||0); return new Date(Date.UTC(Number(day.slice(0,4)),Number(day.slice(5,7))-1,Number(day.slice(8,10)),Math.min(23,Math.max(0,h)),Math.min(59,Math.max(0,minute)))-offsetMinutes(day)*60000); }
function workDays(employee:any) { try { const parsed=JSON.parse(String(employee.workDaysJson||"[]")); if(Array.isArray(parsed)){ const values=[...new Set(parsed.map(Number).filter((n:number)=>Number.isInteger(n)&&n>=0&&n<=6))]; if(values.length)return values; } } catch {} return [0,1,2,3,4]; }
function rotationActive(employee:any,date:Date) { const start=String(employee.rotationStartDate||"").slice(0,10); const on=Math.max(1,Math.floor(Number(employee.rotationDaysOn??4))); const off=Math.max(0,Math.floor(Number(employee.rotationDaysOff??2))); if(!/^\d{4}-\d{2}-\d{2}$/.test(start))return false; const localDay=dayKey(date); const diff=Math.floor((Date.parse(`${localDay}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`))/86400000); if(!Number.isFinite(diff)||diff<0)return false; return (diff%(on+off))<on; }
function currentShift(employee:any,now:Date) {
  const kind=String(employee.scheduleType||"ADMIN").trim().toUpperCase();
  const today=dayKey(now); const yesterday=new Date(now.getTime()-86400000); const candidates=[today,dayKey(yesterday)];
  for(const day of candidates){
    const d=localDateTime(day,employee.workStartTime); const endTime=String(employee.workEndTime||""); const startMinutes=(()=>{const m=/^(\d{1,2}):(\d{2})$/.exec(String(employee.workStartTime||""));return m?Number(m[1])*60+Number(m[2]):9*60;})(); const endMinutes=(()=>{const m=/^(\d{1,2}):(\d{2})$/.exec(endTime);return m?Number(m[1])*60+Number(m[2]):16*60;})(); const overnight=endMinutes<=startMinutes; const end=new Date(d.getTime()+((overnight?endMinutes+1440:endMinutes)-startMinutes)*60000); const localDate=new Date(`${day}T00:00:00Z`); const active=kind==="ROTATION"?rotationActive(employee,localDate):workDays(employee).includes(parts(d).weekday);
    if(active && now.getTime()>=d.getTime() && now.getTime()<=end.getTime()+60000)return {start:d,end,isWorkDay:true};
  }
  const base=localDateTime(today,employee.workStartTime); const startMinutes=(()=>{const m=/^(\d{1,2}):(\d{2})$/.exec(String(employee.workStartTime||""));return m?Number(m[1])*60+Number(m[2]):9*60;})(); const endMinutes=(()=>{const m=/^(\d{1,2}):(\d{2})$/.exec(String(employee.workEndTime||""));return m?Number(m[1])*60+Number(m[2]):16*60;})(); const overnight=endMinutes<=startMinutes; const end=new Date(base.getTime()+((overnight?endMinutes+1440:endMinutes)-startMinutes)*60000); const active=kind==="ROTATION"?rotationActive(employee,new Date(`${today}T00:00:00Z`)):workDays(employee).includes(parts(base).weekday); return {start:base,end,isWorkDay:active};
}
async function employeeLocation(db:D1Database,employeeId:string){ const employee=await db.prepare("SELECT id,job_number AS jobNumber,name,status,location_id AS locationId,schedule_type AS scheduleType,rotation_start_date AS rotationStartDate,rotation_days_on AS rotationDaysOn,rotation_days_off AS rotationDaysOff,work_start_time AS workStartTime,work_end_time AS workEndTime,work_days_json AS workDaysJson FROM employees WHERE id=? AND status='active' LIMIT 1").bind(employeeId).first<any>(); if(!employee)return null; const rows=await db.prepare("SELECT id,name,lat,lng,radius_meters AS radiusMeters FROM locations ORDER BY name").all<any>(); const list=rows.results||[]; const selected=(employee.locationId?list.find((x:any)=>String(x.id)===String(employee.locationId)):null)||list.find((x:any)=>String(x.id)==="main")||list[0]; if(!selected)return null; const lat=coordinate(selected.lat),lng=coordinate(selected.lng),radius=Number(selected.radiusMeters); if(!Number.isFinite(lat)||!Number.isFinite(lng)||!Number.isFinite(radius)||radius<=0)return null; return {employee,location:{id:String(selected.id),name:String(selected.name||"الموقع"),lat,lng,radiusMeters:radius}}; }
async function employeeSchedule(db:D1Database,employeeId:string){ return db.prepare("SELECT id,schedule_type AS scheduleType,rotation_start_date AS rotationStartDate,rotation_days_on AS rotationDaysOn,rotation_days_off AS rotationDaysOff,work_start_time AS workStartTime,work_end_time AS workEndTime,work_days_json AS workDaysJson FROM employees WHERE id=? AND status='active' LIMIT 1").bind(employeeId).first<any>(); }
async function earlyCheckoutMinutes(db:D1Database,employeeId:string){ const row=await db.prepare("SELECT early_checkout_minutes AS earlyCheckoutMinutes FROM employee_checkout_policies WHERE employee_id=? LIMIT 1").bind(employeeId).first<any>(); const value=Number(row?.earlyCheckoutMinutes); return Number.isFinite(value)&&value>0?Math.min(Math.floor(value),1440):0; }
async function approvedEarlyCheckoutToday(db:D1Database,employeeId:string,now:Date){ const today=dayKey(now); const rows=await db.prepare("SELECT type,status,created_at AS createdAt FROM requests WHERE employee_id=? AND type='checkout' ORDER BY created_at DESC LIMIT 50").bind(employeeId).all<any>(); return (rows.results||[]).some((r:any)=>["approved","confirmed"].includes(String(r.status||"").toLowerCase())&&String(r.createdAt||"").slice(0,10)===today); }
function scopedRows(rows:any[],shift:{start:Date;end:Date},now?:Date){ const upper=Math.min(shift.end.getTime()+60000,now?now.getTime()+30000:shift.end.getTime()+60000); return rows.filter((r:any)=>{const t=Date.parse(String(r.timestamp));return Number.isFinite(t)&&t>=shift.start.getTime()&&t<=upper;}).sort((a:any,b:any)=>Date.parse(String(a.timestamp))-Date.parse(String(b.timestamp))); }
export async function handleEmployeeAttendance(req:Request,env:Env,actor:any,origin:string){ if(actor?.role!=="staff")return null; if(req.method==="GET"){
    const requestedLimit=Math.min(Math.max(Number(new URL(req.url).searchParams.get("limit")||100),1),500);
    const rows=await env.DB.prepare("SELECT id,employee_id AS employeeId,job_number AS jobNumber,employee_name AS employeeName,type,timestamp,lat,lng,distance_meters AS distanceMeters,device_id AS deviceId,ip,qr_code AS qrCode,location_id AS locationId FROM attendance WHERE employee_id=? ORDER BY timestamp DESC LIMIT ?").bind(actor.id,requestedLimit).all<any>();
    if(requestedLimit<=500){
      const employee=await employeeSchedule(env.DB,actor.id); if(!employee)return json([],200,origin);
      const shift=currentShift(employee,new Date()); if(!shift.isWorkDay)return json([],200,origin);
      return json(scopedRows(rows.results||[],shift,new Date()).reverse(),200,origin);
    }
    return json(rows.results||[],200,origin);
  }
  if(req.method!=="POST")return json({error:"الطريقة غير مدعومة"},405,origin); const b=await req.json().catch(()=>({})) as any;const type=String(b.type||"");if(type!=="check-in"&&type!=="check-out")return json({error:"نوع الحضور غير صحيح"},400,origin);const lat=coordinate(b.lat),lng=coordinate(b.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)return json({error:"إحداثيات GPS غير صالحة"},400,origin);const fresh=await employeeLocation(env.DB,actor.id);if(!fresh)return json({error:"لا يوجد موقع عمل صالح محفوظ في D1"},409,origin);const distance=distanceMeters(lat,lng,fresh.location.lat,fresh.location.lng);if(distance>fresh.location.radiusMeters)return json({error:`أنت خارج نطاق موقع العمل. المسافة ${distance} م، والنطاق ${fresh.location.radiusMeters} م.`},403,origin);const now=new Date();const shift=currentShift(fresh.employee,now);if(!shift.isWorkDay)return json({error:"لا يوجد دوام للموظف الآن"},403,origin);const rows=await env.DB.prepare("SELECT id,type,timestamp FROM attendance WHERE employee_id=? ORDER BY timestamp DESC LIMIT 500").bind(actor.id).all<any>();const periodRows=scopedRows(rows.results||[],shift,now);const last=periodRows[periodRows.length-1];if(type==="check-in"){if(periodRows.some((r:any)=>r.type==="check-in"))return json({error:"تم تسجيل الحضور مسبقًا لهذه الفترة"},409,origin);}else{if(!last||last.type!=="check-in")return json({error:"لا يمكن تسجيل الانصراف قبل تسجيل الحضور"},409,origin);const end=shift.end; if(now.getTime()<end.getTime()){const allowed=await earlyCheckoutMinutes(env.DB,actor.id);const inside=allowed>0&&now.getTime()>=Math.max(shift.start.getTime(),end.getTime()-allowed*60000);if(!inside&&!await approvedEarlyCheckoutToday(env.DB,actor.id,now))return json({error:"لم ينتهِ وقت دوامك بعد"},403,origin);}}
const deviceId=String(req.headers.get("x-device-id")||b.deviceId||"unknown").trim()||"unknown";const ip=req.headers.get("CF-Connecting-IP")||"unknown";const id=crypto.randomUUID();const timestamp=now.toISOString();await env.DB.prepare("INSERT INTO attendance(id,employee_id,job_number,employee_name,type,timestamp,lat,lng,distance_meters,device_id,ip,qr_code,location_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,fresh.employee.id,fresh.employee.jobNumber,fresh.employee.name,type,timestamp,lat,lng,distance,deviceId,ip,String(b.qrCode||""),fresh.location.id).run();await env.DB.prepare("INSERT INTO audit(id,employee_id,job_number,actor_name,action,result,reason,timestamp,device_id,ip,lat,lng,distance_meters) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),fresh.employee.id,fresh.employee.jobNumber,fresh.employee.name,type,"success",null,timestamp,deviceId,ip,lat,lng,distance).run().catch(()=>undefined);return json({ok:true,record:{id,employeeId:fresh.employee.id,jobNumber:fresh.employee.jobNumber,employeeName:fresh.employee.name,type,timestamp,lat,lng,distanceMeters:distance,deviceId,ip,qrCode:String(b.qrCode||""),locationId:fresh.location.id}},201,origin); }
