import app from "./app";
import { HadirRealtime } from "./realtime";

// Keep the production Worker deployment in sync with the D1-backed API entrypoint.

type Env = { REALTIME: DurableObjectNamespace; DB: D1Database; JWT_SECRET?: string; APP_ORIGIN?: string; OWNER_RECOVERY_CODE?: string; PROFILE_IMAGES?: R2Bucket };
const SESSION_COOKIE = "hadir_session";
const cors = (origin: string) => ({ "access-control-allow-origin": origin, "access-control-allow-credentials": "true", "access-control-allow-headers": "content-type, authorization, x-device-id", "access-control-allow-methods": "GET,POST,PATCH,PUT,DELETE,OPTIONS" });
function readCookie(request: Request, name: string): string | null { const cookies=request.headers.get("cookie")||"";const item=cookies.split(";").map(v=>v.trim()).find(v=>v.startsWith(`${name}=`));return item?decodeURIComponent(item.slice(name.length+1)):null; }
async function hashToken(token: string) { const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));let binary="";for(const byte of new Uint8Array(digest))binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,""); }
async function actorIdFromSession(request: Request, env: Env): Promise<string|null> { const token=(readCookie(request,SESSION_COOKIE)||request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"").trim();if(!token||!env.DB)return null;try{const tokenHash=await hashToken(token);const row=await env.DB.prepare("SELECT user_id AS userId FROM auth_sessions WHERE token_hash=? LIMIT 1").bind(tokenHash).first<{userId:string}>();return row?.userId||null;}catch{return null;} }
function realtimeId(env: Env) { return env.REALTIME.idFromName("hadir-global"); }
async function broadcast(env: Env, payload: Record<string, unknown>) { if(!env.REALTIME)return;const stub=env.REALTIME.get(realtimeId(env));await stub.fetch("https://realtime/broadcast",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}).catch(()=>undefined); }
function validDeviceId(value: string|null): value is string { return Boolean(value&&value.trim().length>=8&&value.trim().length<=200); }
function readDeviceCookie(request: Request) { const cookies=request.headers.get("cookie")||"";const item=cookies.split(";").map(v=>v.trim()).find(v=>v.startsWith("hadir_device_id="));return item?decodeURIComponent(item.slice("hadir_device_id=".length)):null; }
function createDeviceId() { return `dev-cookie-${crypto.randomUUID()}`; }
async function ensureDeviceIdentity(request: Request): Promise<{request:Request;deviceId:string;setCookie:boolean}> { const headerId=request.headers.get("x-device-id")?.trim()||null;const cookieId=readDeviceCookie(request);const deviceId=validDeviceId(headerId)?headerId:validDeviceId(cookieId)?cookieId:createDeviceId();const headers=new Headers(request.headers);headers.set("x-device-id",deviceId);let nextRequest:Request;if(new URL(request.url).pathname==="/api/auth/login"&&request.method==="POST"&&(request.headers.get("content-type")||"").includes("application/json")){const body=await request.clone().json().catch(()=>null) as Record<string,unknown>|null;if(body){if(!String(body.deviceId||"").trim())body.deviceId=deviceId;if(!String(body.deviceLabel||"").trim())body.deviceLabel="متصفح الهاتف";}nextRequest=new Request(request,{headers,body:body?JSON.stringify(body):undefined});}else nextRequest=new Request(request,{headers});return{request:nextRequest,deviceId,setCookie:!validDeviceId(cookieId)||cookieId!==deviceId}; }
function addDeviceCookie(response:Response,deviceId:string,setCookie:boolean):Response { if(!setCookie)return response;const headers=new Headers(response.headers);headers.append("Set-Cookie",`hadir_device_id=${encodeURIComponent(deviceId)}; Path=/; Max-Age=31536000; SameSite=Lax; Secure; HttpOnly`);return new Response(response.body,{status:response.status,statusText:response.statusText,headers}); }
export { HadirRealtime };
export default { async fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response> { const url=new URL(request.url);const origin=env.APP_ORIGIN||request.headers.get("origin")||"*";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(url.pathname==="/api/realtime"&&request.method==="GET"){const userId=await actorIdFromSession(request,env);if(!userId)return new Response("غير مصرح",{status:401,headers:cors(origin)});if(!env.REALTIME)return new Response("Realtime غير مفعّل",{status:503,headers:cors(origin)});const stub=env.REALTIME.get(realtimeId(env));const connectUrl=new URL("https://realtime/connect");connectUrl.searchParams.set("userId",userId);const response=await stub.fetch(connectUrl,{method:"GET"});return response.status===101?response:new Response("Realtime connection failed",{status:502,headers:cors(origin)});}
  const prepared=await ensureDeviceIdentity(request);const mutation=["POST","PUT","PATCH","DELETE"].includes(request.method)&&url.pathname.startsWith("/api/");const response=await app.fetch(prepared.request,env,ctx);if(mutation&&response.ok)ctx.waitUntil(broadcast(env,{type:"cloud-data-changed",timestamp:new Date().toISOString(),path:url.pathname,method:request.method}));return addDeviceCookie(response,prepared.deviceId,prepared.setCookie); } };
