// Generated from date-holidays 3.25.0 data. Update this file when the dependency data is upgraded.
export type HolidayCountry = string;
export type HolidayCountryMeta = { code: string; name: string; nameEn: string };

export const HOLIDAY_COUNTRIES: HolidayCountryMeta[] = [
  { code: "SY", name: "سوريا", nameEn: "Syria" },
  { code: "AL", name: "Albania", nameEn: "Albania" },
  { code: "AS", name: "American Samoa", nameEn: "American Samoa" },
  { code: "AD", name: "Andorra", nameEn: "Andorra" },
  { code: "AO", name: "Angola", nameEn: "Angola" },
  { code: "AI", name: "Anguilla", nameEn: "Anguilla" },
  { code: "AG", name: "Antigua & Barbuda", nameEn: "Antigua & Barbuda" },
  { code: "AR", name: "Argentina", nameEn: "Argentina" },
  { code: "AM", name: "Armenia", nameEn: "Armenia" },
  { code: "AW", name: "Aruba", nameEn: "Aruba" },
  { code: "AU", name: "Australia", nameEn: "Australia" },
  { code: "AT", name: "Austria", nameEn: "Austria" },
  { code: "AZ", name: "Azerbaijan", nameEn: "Azerbaijan" },
  { code: "BS", name: "Bahamas", nameEn: "Bahamas" },
  { code: "BB", name: "Barbados", nameEn: "Barbados" },
  { code: "BY", name: "Belarus", nameEn: "Belarus" },
  { code: "BE", name: "Belgium", nameEn: "Belgium" },
  { code: "BZ", name: "Belize", nameEn: "Belize" },
  { code: "BJ", name: "Benin", nameEn: "Benin" },
  { code: "BM", name: "Bermuda", nameEn: "Bermuda" },
  { code: "BO", name: "Bolivia", nameEn: "Bolivia" },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    nameEn: "Bosnia and Herzegovina",
  },
  { code: "BW", name: "Botswana", nameEn: "Botswana" },
  { code: "BR", name: "Brazil", nameEn: "Brazil" },
  {
    code: "VG",
    name: "British Virgin Islands",
    nameEn: "British Virgin Islands",
  },
  { code: "BN", name: "Brunei", nameEn: "Brunei" },
  { code: "BG", name: "Bulgaria", nameEn: "Bulgaria" },
  { code: "BF", name: "Burkina Faso", nameEn: "Burkina Faso" },
  { code: "BI", name: "Burundi", nameEn: "Burundi" },
  { code: "CM", name: "Cameroon", nameEn: "Cameroon" },
  { code: "CA", name: "Canada", nameEn: "Canada" },
  { code: "IC", name: "Canary Islands", nameEn: "Canary Islands" },
  { code: "CV", name: "Cape Verde", nameEn: "Cape Verde" },
  {
    code: "BQ",
    name: "Caribbean Netherlands",
    nameEn: "Caribbean Netherlands",
  },
  { code: "KY", name: "Cayman Islands", nameEn: "Cayman Islands" },
  {
    code: "CF",
    name: "Central African Republic",
    nameEn: "Central African Republic",
  },
  { code: "CL", name: "Chile", nameEn: "Chile" },
  { code: "CN", name: "China", nameEn: "China" },
  { code: "CX", name: "Christmas Island", nameEn: "Christmas Island" },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    nameEn: "Cocos (Keeling) Islands",
  },
  { code: "CO", name: "Colombia", nameEn: "Colombia" },
  { code: "KM", name: "Comoros", nameEn: "Comoros" },
  { code: "CK", name: "Cook Islands", nameEn: "Cook Islands" },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica" },
  { code: "HR", name: "Croatia", nameEn: "Croatia" },
  { code: "CU", name: "Cuba", nameEn: "Cuba" },
  { code: "CW", name: "Curaçao", nameEn: "Curaçao" },
  { code: "CY", name: "Cyprus", nameEn: "Cyprus" },
  { code: "CZ", name: "Czech Republic", nameEn: "Czech Republic" },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    nameEn: "Democratic Republic of the Congo",
  },
  { code: "DK", name: "Denmark", nameEn: "Denmark" },
  { code: "DM", name: "Dominica", nameEn: "Dominica" },
  { code: "DO", name: "Dominican Republic", nameEn: "Dominican Republic" },
  { code: "EC", name: "Ecuador", nameEn: "Ecuador" },
  { code: "SV", name: "El Salvador", nameEn: "El Salvador" },
  { code: "ER", name: "Eritrea", nameEn: "Eritrea" },
  { code: "EE", name: "Estonia", nameEn: "Estonia" },
  { code: "ET", name: "Ethiopia", nameEn: "Ethiopia" },
  { code: "FO", name: "Faroe Islands", nameEn: "Faroe Islands" },
  { code: "FJ", name: "Fiji", nameEn: "Fiji" },
  { code: "FI", name: "Finland", nameEn: "Finland" },
  { code: "FR", name: "France", nameEn: "France" },
  { code: "GF", name: "French Guiana", nameEn: "French Guiana" },
  { code: "GA", name: "Gabon", nameEn: "Gabon" },
  { code: "GE", name: "Georgia", nameEn: "Georgia" },
  { code: "DE", name: "Germany", nameEn: "Germany" },
  { code: "GH", name: "Ghana", nameEn: "Ghana" },
  { code: "GI", name: "Gibraltar", nameEn: "Gibraltar" },
  { code: "GR", name: "Greece", nameEn: "Greece" },
  { code: "GL", name: "Greenland", nameEn: "Greenland" },
  { code: "GD", name: "Grenada", nameEn: "Grenada" },
  { code: "GP", name: "Guadeloupe", nameEn: "Guadeloupe" },
  { code: "GU", name: "Guam", nameEn: "Guam" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala" },
  { code: "GG", name: "Guernsey", nameEn: "Guernsey" },
  { code: "GN", name: "Guinea", nameEn: "Guinea" },
  { code: "GW", name: "Guinea-Bissau", nameEn: "Guinea-Bissau" },
  { code: "GY", name: "Guyana", nameEn: "Guyana" },
  { code: "HT", name: "Haiti", nameEn: "Haiti" },
  { code: "HN", name: "Honduras", nameEn: "Honduras" },
  { code: "HK", name: "Hong Kong", nameEn: "Hong Kong" },
  { code: "HU", name: "Hungary", nameEn: "Hungary" },
  { code: "IS", name: "Iceland", nameEn: "Iceland" },
  { code: "ID", name: "Indonesia", nameEn: "Indonesia" },
  { code: "IR", name: "Iran", nameEn: "Iran" },
  { code: "IE", name: "Ireland", nameEn: "Ireland" },
  { code: "IM", name: "Isle of Man", nameEn: "Isle of Man" },
  { code: "IL", name: "Israel", nameEn: "Israel" },
  { code: "IT", name: "Italia", nameEn: "Italia" },
  { code: "JM", name: "Jamaica", nameEn: "Jamaica" },
  { code: "JP", name: "Japan", nameEn: "Japan" },
  { code: "JE", name: "Jersey", nameEn: "Jersey" },
  { code: "KE", name: "Kenya", nameEn: "Kenya" },
  { code: "XK", name: "Kosovo", nameEn: "Kosovo" },
  { code: "LV", name: "Latvia", nameEn: "Latvia" },
  { code: "LS", name: "Lesotho", nameEn: "Lesotho" },
  { code: "LR", name: "Liberia", nameEn: "Liberia" },
  { code: "LI", name: "Liechtenstein", nameEn: "Liechtenstein" },
  { code: "LT", name: "Lithuania", nameEn: "Lithuania" },
  { code: "LU", name: "Luxembourg", nameEn: "Luxembourg" },
  { code: "MK", name: "Macedonia", nameEn: "Macedonia" },
  { code: "MG", name: "Madagascar", nameEn: "Madagascar" },
  { code: "MW", name: "Malawi", nameEn: "Malawi" },
  { code: "MY", name: "Malaysia", nameEn: "Malaysia" },
  { code: "MT", name: "Malta", nameEn: "Malta" },
  { code: "MQ", name: "Martinique", nameEn: "Martinique" },
  { code: "YT", name: "Mayotte", nameEn: "Mayotte" },
  { code: "MX", name: "Mexico", nameEn: "Mexico" },
  { code: "MD", name: "Moldova", nameEn: "Moldova" },
  { code: "MC", name: "Monaco", nameEn: "Monaco" },
  { code: "ME", name: "Montenegro", nameEn: "Montenegro" },
  { code: "MS", name: "Montserrat", nameEn: "Montserrat" },
  { code: "MZ", name: "Mozambique", nameEn: "Mozambique" },
  { code: "NA", name: "Namibia", nameEn: "Namibia" },
  { code: "NL", name: "Netherlands", nameEn: "Netherlands" },
  { code: "NC", name: "New Caledonia", nameEn: "New Caledonia" },
  { code: "NZ", name: "New Zealand", nameEn: "New Zealand" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria" },
  { code: "NO", name: "Norway", nameEn: "Norway" },
  { code: "PA", name: "Panama", nameEn: "Panama" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay" },
  {
    code: "BD",
    name: "People's Republic of Bangladesh",
    nameEn: "People's Republic of Bangladesh",
  },
  { code: "PE", name: "Peru", nameEn: "Peru" },
  { code: "PH", name: "Philippines", nameEn: "Philippines" },
  { code: "PL", name: "Poland", nameEn: "Poland" },
  { code: "PT", name: "Portugal", nameEn: "Portugal" },
  { code: "PR", name: "Puerto Rico", nameEn: "Puerto Rico" },
  {
    code: "CI",
    name: "Republic of Côte d'Ivoire",
    nameEn: "Republic of Côte d'Ivoire",
  },
  {
    code: "GQ",
    name: "Republic of Equatorial Guinea",
    nameEn: "Republic of Equatorial Guinea",
  },
  { code: "ML", name: "Republic of Mali", nameEn: "Republic of Mali" },
  {
    code: "CG",
    name: "Republic of the Congo",
    nameEn: "Republic of the Congo",
  },
  {
    code: "NE",
    name: "Republic of the Niger",
    nameEn: "Republic of the Niger",
  },
  { code: "RO", name: "Romania", nameEn: "Romania" },
  { code: "RU", name: "Russia", nameEn: "Russia" },
  { code: "RW", name: "Rwanda", nameEn: "Rwanda" },
  { code: "RE", name: "Réunion", nameEn: "Réunion" },
  { code: "SM", name: "San Marino", nameEn: "San Marino" },
  { code: "SN", name: "Senegal", nameEn: "Senegal" },
  { code: "RS", name: "Serbia", nameEn: "Serbia" },
  { code: "SC", name: "Seychelles", nameEn: "Seychelles" },
  { code: "SL", name: "Sierra Leone", nameEn: "Sierra Leone" },
  { code: "SG", name: "Singapore", nameEn: "Singapore" },
  { code: "SX", name: "Sint Maarten", nameEn: "Sint Maarten" },
  { code: "SK", name: "Slovakia", nameEn: "Slovakia" },
  { code: "SI", name: "Slovenia", nameEn: "Slovenia" },
  { code: "ZA", name: "South Africa", nameEn: "South Africa" },
  { code: "KR", name: "South Korea", nameEn: "South Korea" },
  { code: "SS", name: "South Sudan", nameEn: "South Sudan" },
  { code: "ES", name: "Spain", nameEn: "Spain" },
  { code: "BL", name: "St. Barths", nameEn: "St. Barths" },
  { code: "SH", name: "St. Helena", nameEn: "St. Helena" },
  { code: "KN", name: "St. Kitts & Nevis", nameEn: "St. Kitts & Nevis" },
  { code: "LC", name: "St. Lucia", nameEn: "St. Lucia" },
  { code: "MF", name: "St. Martin", nameEn: "St. Martin" },
  {
    code: "PM",
    name: "St. Pierre & Miquelon",
    nameEn: "St. Pierre & Miquelon",
  },
  {
    code: "VC",
    name: "St. Vincent & Grenadines",
    nameEn: "St. Vincent & Grenadines",
  },
  { code: "SR", name: "Suriname", nameEn: "Suriname" },
  { code: "SJ", name: "Svalbard & Jan Mayen", nameEn: "Svalbard & Jan Mayen" },
  { code: "SZ", name: "Swaziland", nameEn: "Swaziland" },
  { code: "SE", name: "Sweden", nameEn: "Sweden" },
  { code: "CH", name: "Switzerland", nameEn: "Switzerland" },
  { code: "ST", name: "São Tomé & Príncipe", nameEn: "São Tomé & Príncipe" },
  { code: "TW", name: "Taiwan", nameEn: "Taiwan" },
  { code: "TZ", name: "Tanzania", nameEn: "Tanzania" },
  { code: "TH", name: "Thailand", nameEn: "Thailand" },
  { code: "GM", name: "The Gambia", nameEn: "The Gambia" },
  { code: "TG", name: "Togolese Republic", nameEn: "Togolese Republic" },
  { code: "TO", name: "Tonga", nameEn: "Tonga" },
  { code: "TT", name: "Trinidad & Tobago", nameEn: "Trinidad & Tobago" },
  { code: "TR", name: "Turkey", nameEn: "Turkey" },
  {
    code: "TC",
    name: "Turks & Caicos Islands",
    nameEn: "Turks & Caicos Islands",
  },
  { code: "VI", name: "U.S. Virgin Islands", nameEn: "U.S. Virgin Islands" },
  { code: "UG", name: "Uganda", nameEn: "Uganda" },
  { code: "UA", name: "Ukraine", nameEn: "Ukraine" },
  { code: "GB", name: "United Kingdom", nameEn: "United Kingdom" },
  {
    code: "US",
    name: "United States of America",
    nameEn: "United States of America",
  },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay" },
  { code: "VU", name: "Vanuatu", nameEn: "Vanuatu" },
  { code: "VA", name: "Vatican City", nameEn: "Vatican City" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam" },
  { code: "ZM", name: "Zambia", nameEn: "Zambia" },
  { code: "ZW", name: "Zimbabwe", nameEn: "Zimbabwe" },
  { code: "AX", name: "Åland Islands", nameEn: "Åland Islands" },
  { code: "MR", name: "الجمهورية الإسلامية الموريتانية", nameEn: "Mauritania" },
  { code: "TN", name: "الجمهورية التونسية", nameEn: "Tunisia" },
  {
    code: "DZ",
    name: "الجمهورية الجزائرية الديمقراطية الشعبية",
    nameEn: "Algeria",
  },
  {
    code: "EH",
    name: "الجمهورية العربية الصحراوية الديمقراطية",
    nameEn: "Western Sahara",
  },
  { code: "SA", name: "المملكة العربية السعودية", nameEn: "Saudi Arabia" },
  { code: "MA", name: "المملكة المغربية", nameEn: "Kingdom of Morocco" },
  { code: "SD", name: "جمهورية السودان", nameEn: "Sudan" },
  { code: "SO", name: "جمهورية الصومال الفدرالية", nameEn: "Somalia" },
  { code: "TD", name: "جمهورية تشاد", nameEn: "Chad" },
  { code: "DJ", name: "جمهورية جيبوتي", nameEn: "Djibouti" },
  { code: "EG", name: "جمهورية مصر العربية", nameEn: "Egypt" },
  {
    code: "AE",
    name: "دولة الإمارات العربية المتحدة",
    nameEn: "United Arab Emirates",
  },
  { code: "LY", name: "دولة ليبيا", nameEn: "Libya" },
  { code: "BH", name: "مملكة البحرين", nameEn: "Bahrain" },
];

export const HOLIDAY_COUNTRY_CODES = new Set(
  HOLIDAY_COUNTRIES.map((country) => country.code),
);
