type Role = "owner" | "manager" | "supervisor" | "staff";
type Actor = { id: string; username: string; name: string; role: Role };
type Env = { DB: D1Database; JWT_SECRET?: string; APP_ORIGIN?: string };
const SESSION_COOKIE = "hadir_session";
const now=()=>new Date().toISOString(); const uid=()=>crypto.randomUUID(); const encoder=new TextEncoder(); const PASSWORD_ITERATIONS=100000;
function b64(data:ArrayBuffer|Uint8Array){const bytes=data instanceof Uint8Array?data:new Uint8Array(data);let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=/g,"");}
function unb64(value:string){const padded=value.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((value.length+3)%4);const binary=atob(padded);return Uint8Array.from(binary,c=>c.charCodeAt(0));}
async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits("PBKDF2",key,{name:"PBKDF2",hash:"SHA-256",salt,iterations:PASSWORD_ITERATIONS},256);return `pbkdf2$${PASSWORD_ITERATIONS}$${b64(salt)}$${b64(bits)}`;}
async function verifyPassword(password:string,stored:string){try{const[kind,it,saltText,hashText]=String(stored||"").split("$");const iterations=Number(it);if(kind!=="pbkdf2"||iterations!==PASSWORD_ITERATIONS)return false;const salt=unb64(saltText),expectedHash=unb64(hashText),key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits("PBKDF2",key,{name:"PBKDF2",hash:"SHA-256",salt,iterations},256),actual=new Uint8Array(bits);if(actual.length!==expectedHash.length)return false;let match=0;for(let i=0;i<actual.length;i++)match|=actual[i]^expectedHash[i];return match===0;}catch{return false;}}
async function sign(actor:Actor,secret:string){if(!secret)throw new Error("JWT_SECRET is missing");const header=b64(encoder.encode(JSON.stringify({alg:"HS256",typ:"JWT"})));const payload=b64(encoder.encode(JSON.stringify({iss:"hadir",sub:actor.id,name:actor.name,role:actor.role,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+86400})));const sig=await crypto.subtle.sign("HMAC",await crypto.subtle.importKey("raw",encoder.encode(secret),"HMAC",false,["sign"]),encoder.encode(`${header}.${payload}`));return`${header}.${payload}.${b64(sig)}`;}
function getCookie(req:Request,name:string){const raw=req.headers.get("cookie")||"";for(const part of raw.split(";")){const [key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="));}return "";}
async function hashSessionToken(token:string){const digest=await crypto.subtle.digest("SHA-256",encoder.encode(token));return b64(digest);}
async function createSession(env:Env,actor:Actor){const token=`hs_${uid().replace(/-/g,"")}_${uid().replace(/-/g,"")}`;const tokenHash=await hashSessionToken(token);await env.DB.prepare("INSERT INTO sessions(token_hash,actor_id,actor_name,actor_role,created_at,expires_at)VALUES(?,?,?,?,?,?)").bind(tokenHash,actor.id,actor.name,actor.role,now(),new Date(Date.now()+86400000).toISOString()).run();return token;}
async function readToken(req:Request,env:Env):Promise<Actor|null>{const token=getCookie(req,SESSION_COOKIE)||req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)return null;try{const sessionToken=token.startsWith("hs_")?token:null;if(sessionToken){const tokenHash=await hashSessionToken(sessionToken);const row=await env.DB.prepare("SELECT actor_id,actor_name,actor_role FROM sessions WHERE token_hash=? AND expires_at>? LIMIT 1").bind(tokenHash,now()).first<{actor_id:string;actor_name:string;actor_role:Role}>();if(row)return{id:row.actor_id,username:"",name:row.actor_name,role:row.actor_role};}
if(!env.JWT_SECRET)return null;const[header,payload,signature]=token.split(".");if(!header||!payload||!signature)return null;const key=await crypto.subtle.importKey("raw",encoder.encode(env.JWT_SECRET),"HMAC",false,["verify"]),valid=await crypto.subtle.verify("HMAC",key,unb64(signature),encoder.encode(`${header}.${payload}`));if(!valid)return null;const claims=JSON.parse(new TextDecoder().decode(unb64(payload)));if(claims.exp<Math.floor(Date.now()/1000))return null;return{id:claims.sub,username:"",name:claims.name,role:claims.role};}catch{return null;}}
const cors=(origin:string)=>({"content-type":"application/json; charset=utf-8","access-control-allow-origin":origin,"access-control-allow-headers":"content-type, authorization, x-device-id","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, PUT, PATCH, DELETE, OPTIONS"});
const json=(data:unknown,status=200,origin="*")=>new Response(JSON.stringify(data),{status,headers:cors(origin)}); const body=async(req:Request)=>await req.json().catch(()=>({})) as Record<string,unknown>;
const isAdmin=(role:Role)=>["owner","manager","supervisor"].includes(role);const canWrite=(role:Role)=>["owner","manager"].includes(role);const isOwner=(role:Role)=>role==="owner";
let schemaReady:Promise<void>|null=null;
async function ensureSchema(env:Env){if(!schemaReady){schemaReady=env.DB.batch([
  env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_accounts(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('owner','manager','supervisor')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,actor_id TEXT NOT NULL,actor_name TEXT NOT NULL,actor_role TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS employees(id TEXT PRIMARY KEY,job_number TEXT NOT NULL UNIQUE,name TEXT NOT NULL,pin_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',device_id TEXT,device_label TEXT,created_at TEXT NOT NULL,schedule_type TEXT DEFAULT 'ADMIN',rotation_start_date TEXT,work_start_time TEXT,work_end_time TEXT,rotation_start_time TEXT,rotation_end_time TEXT,grace_period_minutes INTEGER,early_checkout_grace_minutes INTEGER,role TEXT DEFAULT 'staff',location_id TEXT,rotation_days_on INTEGER,rotation_days_off INTEGER,avatar TEXT)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS attendance(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,job_number TEXT NOT NULL,employee_name TEXT NOT NULL,type TEXT NOT NULL,timestamp TEXT NOT NULL,lat REAL NOT NULL,lng REAL NOT NULL,distance_meters REAL,challenge_id TEXT)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS locations(id TEXT PRIMARY KEY,name TEXT NOT NULL,lat REAL NOT NULL,lng REAL NOT NULL,radius_meters REAL NOT NULL)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS requests(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,employee_name TEXT NOT NULL,job_number TEXT NOT NULL,type TEXT NOT NULL,reason TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,start_date TEXT,end_date TEXT)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,employee_id TEXT,job_number TEXT NOT NULL,actor_name TEXT NOT NULL,action TEXT NOT NULL,result TEXT NOT NULL,reason TEXT,timestamp TEXT NOT NULL,device_id TEXT,ip TEXT,lat REAL,lng REAL,distance_meters REAL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS escape_events(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,job_number TEXT NOT NULL,employee_name TEXT NOT NULL,status TEXT NOT NULL,timestamp TEXT NOT NULL,reason TEXT,actor_id TEXT,actor_name TEXT,lat REAL,lng REAL)"),
  ]).then(()=>undefined).catch(error=>{schemaReady=null;throw error;});}await schemaReady;}
async function ownerExists(env:Env){const row=await env.DB.prepare("SELECT 1 AS ok FROM admin_accounts WHERE role='owner' LIMIT 1").first<{ok:number}>();return Boolean(row);} function arr(value:unknown):any[]{return Array.isArray(value)?value:[];}
function employeeOut(r:any){return{id:r.id,jobNumber:r.job_number,name:r.name,pinHash:"",status:r.status,deviceId:r.device_id,deviceLabel:r.device_label,createdAt:r.created_at,scheduleType:r.schedule_type,rotationStartDate:r.rotation_start_date,workStartTime:r.work_start_time,workEndTime:r.work_end_time,rotationStartTime:r.rotation_start_time,rotationEndTime:r.rotation_end_time,gracePeriodMinutes:r.grace_period_minutes,earlyCheckoutGraceMinutes:r.early_checkout_grace_minutes,role:r.role,locationId:r.location_id,rotationDaysOn:r.rotation_days_on,rotationDaysOff:r.rotation_days_off,avatar:r.avatar};}
async function audit(env:Env,req:Request,actorName:string,action:string,result:"success"|"rejected",employeeId:string|null=null,jobNumber="",reason:string|null=null){await env.DB.prepare("INSERT INTO audit(id,employee_id,job_number,actor_name,action,result,reason,timestamp,device_id,ip)VALUES(?,?,?,?,?,?,?,?,?,?)").bind(uid(),employeeId,jobNumber,actorName,action,result,reason||null,now(),"device",req.headers.get("x-forwarded-for")||"").run();}
async function resetData(env:Env,req:Request,actor:Actor){const audit_id=uid();try{await env.DB.batch([env.DB.prepare("DELETE FROM attendance"),env.DB.prepare("DELETE FROM escape_events"),env.DB.prepare("DELETE FROM requests"),env.DB.prepare("DELETE FROM employees"),env.DB.prepare("DELETE FROM audit"),env.DB.prepare("DELETE FROM sessions WHERE actor_id!=?").bind(actor.id),]);await env.DB.prepare("INSERT INTO audit(id,employee_id,job_number,actor_name,action,result,reason,timestamp,device_id,ip)VALUES(?,?,?,?,?,?,?,?,?,?)").bind(audit_id,null,"SYSTEM",actor.name,"system-reset","success","تم مسح بيانات النظام",now(),"system",req.headers.get("x-forwarded-for")||"").run();return{ok:true,deleted:{employees:"all",attendance:"all",escape_events:"all",requests:"all",audit:"logged"},preserved:["admin_accounts","locations","settings","schema"],message:"تم حذف بيانات التشغيل بنجاح. الحسابات والإعدادات محفوظة."};}catch(error){throw new Error(`فشل Reset: ${error instanceof Error?error.message:"خطأ غير معروف"}`);}}
export default {async fetch(req:Request,env:Env){const origin=env.APP_ORIGIN||"*";if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});const path=new URL(req.url).pathname.replace(/\/+/g,"/").split("?")[0];
if(path==="/"&&req.method==="GET")return json({ok:true,service:"hadir-api",message:"Hadir API is running"},200,origin);
if(path==="/api/health"&&req.method==="GET"){await env.DB.prepare("SELECT 1 AS ok").first();return json({ok:true,service:"hadir-api",database:"D1",ownerInitialized:await ownerExists(env),time:now()},200,origin);}
if(path==="/api/bootstrap"&&req.method==="GET"){if(await ownerExists(env))return json({bootstrap:false},200,origin);const token=await sign({id:"bootstrap",username:"",name:"إعداد النظام",role:"owner"},env.JWT_SECRET||"");return json({bootstrap:true,token},200,origin);}
if(path==="/api/bootstrap/owner"&&req.method==="POST"){if(await ownerExists(env))return json({error:"تم إعداد حساب المالك مسبقًا"},409,origin);const bootstrapActor=await readToken(req,env);if(!bootstrapActor||bootstrapActor.role!=="owner")return json({error:"غير مصرح"},403,origin);await ensureSchema(env);const b=await body(req),username=String(b.username||"").trim(),password=String(b.password||"").trim(),name=String(b.name||"المالك").trim();if(!username||!password)return json({error:"اسم المستخدم وكلمة المرور مطلوبان"},400,origin);const passwordHash=await hashPassword(password),owner={id:uid(),username,passwordHash,name,role:"owner" as const,active:true,createdAt:now()};await env.DB.prepare("INSERT INTO admin_accounts VALUES(?,?,?,?,?,?,?)").bind(owner.id,owner.username,owner.passwordHash,owner.name,owner.role,1,owner.createdAt).run();const token=await createSession(env,{id:owner.id,username:owner.username,name:owner.name,role:owner.role});return json({ok:true,token,user:owner},200,origin);}
if(path==="/api/auth/login"&&req.method==="POST"){const b=await body(req),username=String(b.username||"").trim(),password=String(b.password||"");if(!username||!password)return json({error:"اسم المستخدم وكلمة المرور مطلوبان"},400,origin);
const incomingDeviceId=String(b.deviceId||req.headers.get("x-device-id")||"").trim();const incomingDeviceLabel=String(b.deviceLabel||"جهاز غير معروف").trim()||"جهاز غير معروف";const rebindDevice=Boolean(b.rebindDevice);
const adminRow=await env.DB.prepare("SELECT * FROM admin_accounts WHERE username=? LIMIT 1").bind(username).first();if(adminRow&&adminRow.active){if(await verifyPassword(password,adminRow.password_hash)){const actor={id:adminRow.id,username:adminRow.username,name:adminRow.name,role:adminRow.role};const token=await createSession(env,actor);await audit(env,req,adminRow.name,"manager-login","success");return json({ok:true,token,user:actor,kind:"admin"},200,origin);}else{await audit(env,req,username,"manager-login-failed","rejected","كلمة المرور غير صحيحة");return json({error:"كلمة المرور غير صحيحة"},401,origin);}}
const empRow=await env.DB.prepare("SELECT * FROM employees WHERE job_number=? LIMIT 1").bind(username).first();if(!empRow)return json({error:"المستخدم غير موجود"},401,origin);if(empRow.status!=="active")return json({error:"الحساب موقوف"},403,origin);if(!await verifyPassword(password,empRow.pin_hash))return json({error:"رمز الدخول غير صحيح"},401,origin);
let boundDeviceId=String(empRow.device_id||"").trim();let boundDeviceLabel=String(empRow.device_label||"").trim();
if(boundDeviceId&&incomingDeviceId!==boundDeviceId){if(!rebindDevice)return json({error:"هذا الحساب مرتبط بجهاز آخر. إذا كنت تستخدم هاتفًا جديدًا، اطلب إعادة ربط الجهاز."},403,origin);}
if(!boundDeviceId){const saved=await env.DB.prepare("UPDATE employees SET device_id=?,device_label=? WHERE id=? AND (device_id IS NULL OR TRIM(device_id)='') RETURNING id,device_id,device_label").bind(incomingDeviceId,incomingDeviceLabel,empRow.id).first();if(saved){boundDeviceId=incomingDeviceId;boundDeviceLabel=incomingDeviceLabel;}}
const actor={id:empRow.id,username:empRow.job_number,name:empRow.name,role:"staff"};await audit(env,req,empRow.name,"login","success",empRow.id,empRow.job_number);const token=await createSession(env,actor);return json({ok:true,token,user:employeeOut(empRow),kind:"employee"},200,origin);}
if(path==="/api/auth/logout"&&req.method==="POST"){const token=getCookie(req,SESSION_COOKIE)||req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(token){await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await hashSessionToken(token)).run();}return json({ok:true},200,origin);}
const actor=await readToken(req,env);if(!actor)return json({error:"غير مصرح"},401,origin);if(path==="/api/me"&&req.method==="GET")return json({user:actor},200,origin);
if((path==="/api/employee/profile"||path==="/api/employee/me")&&req.method==="GET"){if(actor.role!=="staff")return json({error:"هذا المسار مخصص للموظفين"},403,origin);const row=await env.DB.prepare("SELECT * FROM employees WHERE id=? LIMIT 1").bind(actor.id).first();return row?json({user:employeeOut(row)},200,origin):json({error:"الموظف غير موجود"},404,origin);}
if(path==="/api/admins"&&req.method==="GET"){if(!isAdmin(actor.role))return json({error:"غير مصرح"},403,origin);const rows=await env.DB.prepare("SELECT id,username,name,role,active,created_at FROM admin_accounts ORDER BY name").all();return json(arr(rows.results),200,origin);}
if(path==="/api/admins"&&req.method==="POST"){if(!isOwner(actor.role))return json({error:"المالك فقط"},403,origin);const b=await body(req),username=String(b.username||"").trim(),name=String(b.name||"").trim(),password=String(b.password||"").trim(),role=String(b.role||"manager") as "manager"|"supervisor";if(!username||!name||!password||!["manager","supervisor"].includes(role))return json({error:"بيانات غير صالحة"},400,origin);const passwordHash=await hashPassword(password),id=uid();await env.DB.prepare("INSERT INTO admin_accounts VALUES(?,?,?,?,?,?,?)").bind(id,username,passwordHash,name,role,1,now()).run();await audit(env,req,actor.name,"admin-created","success",null,username);return json({ok:true},200,origin);}
if(path.startsWith("/api/admins/")&&req.method==="PATCH"){if(!isOwner(actor.role))return json({error:"المالك فقط"},403,origin);const id=decodeURIComponent(path.split("/").pop()||""),b=await body(req);if(b.password){const newHash=await hashPassword(String(b.password));await env.DB.prepare("UPDATE admin_accounts SET password_hash=? WHERE id=?").bind(newHash,id).run();}if(b.active!==undefined)await env.DB.prepare("UPDATE admin_accounts SET active=? WHERE id=?").bind(b.active?1:0,id).run();if(b.name)await env.DB.prepare("UPDATE admin_accounts SET name=? WHERE id=?").bind(String(b.name),id).run();await audit(env,req,actor.name,"admin-updated","success",null,id);return json({ok:true},200,origin);}
if(path.startsWith("/api/admins/")&&req.method==="DELETE"){if(!isOwner(actor.role))return json({error:"المالك فقط"},403,origin);const id=decodeURIComponent(path.split("/").pop()||"");await env.DB.prepare("DELETE FROM admin_accounts WHERE id=? AND role!='owner'").bind(id).run();await audit(env,req,actor.name,"admin-deleted","success",null,id);return json({ok:true},200,origin);}
if(path.startsWith("/api/employees/")&&req.method==="PATCH"&&!path.endsWith("/device")&&!path.endsWith("/avatar")){if(!canWrite(actor.role))return json({error:"لا تملك صلاحية الكتابة"},403,origin);const id=decodeURIComponent(path.split("/")[3]||""),b=await body(req);
for(const[k,col]of Object.entries({name:"name",status:"status",scheduleType:"schedule_type",rotationStartDate:"rotation_start_date",workStartTime:"work_start_time",workEndTime:"work_end_time",gracePeriodMinutes:"grace_period_minutes",earlyCheckoutGraceMinutes:"early_checkout_grace_minutes",role:"role",locationId:"location_id",rotationDaysOn:"rotation_days_on",rotationDaysOff:"rotation_days_off"})){if(k in b)await env.DB.prepare(`UPDATE employees SET ${col}=? WHERE id=?`).bind(b[k as keyof typeof b],id).run();}await audit(env,req,actor.name,"employee-updated","success",id);return json({ok:true},200,origin);}
if(path==="/api/employees"&&req.method==="GET"){if(!isAdmin(actor.role))return json({error:"غير مصرح"},403,origin);const rows=await env.DB.prepare("SELECT * FROM employees ORDER BY name").all();return json(arr(rows.results).map(employeeOut),200,origin);}
if(path==="/api/employees"&&req.method==="POST"){if(!["owner","manager","supervisor"].includes(actor.role))return json({error:"لا تملك صلاحية الإضافة"},403,origin);const b=await body(req),jobNumber=String(b.jobNumber||"").trim(),name=String(b.name||"").trim(),pin=String(b.pin||"").trim();if(!jobNumber||!name||!pin)return json({error:"بيانات ناقصة"},400,origin);const pinHash=await hashPassword(pin),id=uid();await env.DB.prepare("INSERT INTO employees(id,job_number,name,pin_hash,created_at)VALUES(?,?,?,?,?)").bind(id,jobNumber,name,pinHash,now()).run();await audit(env,req,actor.name,"employee-created","success",id,jobNumber);return json({ok:true,id},200,origin);}
if(path.startsWith("/api/employees/")&&req.method==="DELETE"&&!path.endsWith("/device")){if(!canWrite(actor.role))return json({error:"لا تملك صلاحية الكتابة"},403,origin);const id=decodeURIComponent(path.split("/")[3]||"");await env.DB.prepare("DELETE FROM employees WHERE id=?").bind(id).run();await audit(env,req,actor.name,"employee-deleted","success",id);return json({ok:true},200,origin);}
if(path.startsWith("/api/employees/")&&req.method==="DELETE"&&path.endsWith("/device")){if(!canWrite(actor.role))return json({error:"لا تملك صلاحية الكتابة"},403,origin);const id=decodeURIComponent(path.split("/")[3]||"");await env.DB.prepare("UPDATE employees SET device_id=NULL,device_label=NULL WHERE id=?").bind(id).run();await audit(env,req,actor.name,"device-unbound","success",id);return json({ok:true},200,origin);}
if(path==="/api/escape-events"&&req.method==="GET"){if(!isAdmin(actor.role)&&actor.role!=="staff")return json({error:"غير مصرح"},403,origin);const requested=String(new URL(req.url).searchParams.get("employeeId")||""),limit=Math.min(Number(new URL(req.url).searchParams.get("limit"))||500,2000),query=requested?env.DB.prepare("SELECT * FROM escape_events WHERE employee_id=? ORDER BY timestamp DESC LIMIT ?").bind(requested,limit):env.DB.prepare("SELECT * FROM escape_events ORDER BY timestamp DESC LIMIT ?").bind(limit);const rows=await query.all();return json(arr(rows.results),200,origin);}
if(path==="/api/escape-events"&&req.method==="POST"){if(!canWrite(actor.role))return json({error:"المالك أو المدير فقط يستطيعان تسجيل حالة الهروب أو العودة"},403,origin);const b=await body(req);await env.DB.prepare("INSERT INTO escape_events(id,employee_id,job_number,employee_name,status,timestamp,reason,actor_id,actor_name)VALUES(?,?,?,?,?,?,?,?,?)").bind(uid(),b.employeeId,b.jobNumber,b.employeeName,b.status,now(),b.reason||null,actor.id,actor.name).run();return json({ok:true},200,origin);}
if(path==="/api/workforce/reset"&&req.method==="POST"){if(!isOwner(actor.role))return json({error:"المالك فقط يستطيع تنفيذ Reset"},403,origin);try{const result=await resetData(env,req,actor);return json(result,200,origin);}catch(error){return json({error:error instanceof Error?error.message:"فشل Reset"},500,origin);}}
return json({error:"المسار غير موجود"},404,origin);
}catch(error){return json({error:error instanceof Error?error.message:"حدث خطأ غير متوقع"},500,origin);}}};
