if(p==="/api/attendance"&&req.method==="POST"){const b=await req.json() as any;if(actor.role==="staff"&&b.employeeId!==actor.id)return json({error:"غير مصرح"},403,origin);if(actor.role!=="staff"&&!canWrite(actor.role))return json({error:"غير مصرح"},403,origin);const e=await env.DB.prepare("SELECT * FROM employees WHERE id=?").bind(b.employeeId).first<any>();if(!e)return json({error:"الموظف غير موجود"},404,origin);await env.DB.prepare("INSERT INTO attendance(id,employee_id,job_number,employee_name,type,timestamp,lat,lng,distance_meters,device_id,ip,qr_code,location_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id(),e.id,e.job_number,e.name,b.type,b.timestamp||now(),Number(b.lat)||0,Number(b.lng)||0,Number(b.distanceMeters)||0,b.deviceId||e.device_id||"",req.headers.get("CF-Connecting-IP")||"unknown",b.qrCode||"",b.locationId||null).run();return json({ok:true},201,origin)}
if(p==="/api/requests"&&req.method==="GET"){const r=actor.role==="staff"?await env.DB.prepare("SELECT * FROM requests WHERE employee_id=? ORDER BY created_at DESC").bind(actor.id).all():await env.DB.prepare("SELECT * FROM requests ORDER BY created_at DESC").all();return json(r.results,200,origin)}
if(p==="/api/requests"&&req.method==="POST"){const b=await req.json() as any;if(actor.role==="staff"&&b.employeeId!==actor.id)return json({error:"غير مصرح"},403,origin);await env.DB.prepare("INSERT INTO requests(id,employee_id,employee_name,job_number,type,reason,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(id(),b.employeeId,b.employeeName||actor.name,b.jobNumber,b.type,b.reason||null,"pending",now()).run();return json({ok:true},201,origin)}
if(p.startsWith("/api/requests/")&&req.method==="PATCH"){if(!canWrite(actor.role))return json({error:"غير مصرح"},403,origin);const b=await req.json() as any;if(!["approved","rejected"].includes(b.status))return json({error:"حالة غير صحيحة"},400,origin);await env.DB.prepare("UPDATE requests SET status=? WHERE id=?").bind(b.status,p.split("/").pop()!).run();return json({ok:true},200,origin)}
if(p==="/api/audit"&&req.method==="GET"){if(!canRead(actor.role))return json({error:"غير مصرح"},403,origin);const limit=Math.min(Math.max(Number(u.searchParams.get("limit")||500),1),2000);const r=await env.DB.prepare("SELECT * FROM audit ORDER BY timestamp DESC LIMIT ?").bind(limit).all();return json(r.results,200,origin)}
if(p==="/api/settings"&&req.method==="GET"){if(!canRead(actor.role))return json({error:"غير مصرح"},403,origin);const r=await env.DB.prepare("SELECT key,value FROM settings").all();return json(Object.fromEntries(r.results.map((x:any)=>[x.key,JSON.parse(x.value)])),200,origin)}
if(p==="/api/settings"&&req.method==="PUT"){if(!canWrite(actor.role))return json({error:"غير مصرح"},403,origin);const b=await req.json() as Record<string,unknown>;if(Object.keys(b).length)await env.DB.batch(Object.entries(b).map(([k,v])=>env.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(k,JSON.stringify(v))));return json({ok:true},200,origin)}
if(p==="/api/locations"&&req.method==="GET"){if(!canRead(actor.role))return json({error:"غير مصرح"},403,origin);const r=await env.DB.prepare("SELECT id,name,lat,lng,radius_meters AS radiusMeters FROM locations ORDER BY name").all();return json(r.results,200,origin)}
if(p==="/api/locations"&&req.method==="PUT"){if(!canWrite(actor.role))return json({error:"غير مصرح"},403,origin);const b=await req.json() as any;await env.DB.prepare("INSERT INTO locations(id,name,lat,lng,radius_meters) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,lat=excluded.lat,lng=excluded.lng,radius_meters=excluded.radius_meters").bind(b.id||id(),b.name,Number(b.lat),Number(b.lng),Number(b.radiusMeters)).run();return json({ok:true},200,origin)}
return json({error:"المسار غير موجود"},404,origin)}}};