type Env={DB:D1Database}; type Actor={id:string;role:string;name?:string};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}}); const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString(); const encoder=new TextEncoder(); const ITER=100000;
const manage=(a:Actor|null)=>!!a&&["owner","manager","supervisor"].includes(a.role); const admin=(a:Actor|null)=>!!a&&["owner","manager"].includes(a.role);
function b64(data:ArrayBuffer|Uint8Array){const bytes=data instanceof Uint8Array?data:new Uint8Array(data);let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function ub64(v:string){const p=v.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((v.length+3)%4);const s=atob(p);return Uint8Array.from(s,c=>c.charCodeAt(0));}
async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:ITER,hash:"SHA-256"},key,256);return `pbkdf2$${ITER}$${b64(salt)}$${b64(bits)}`;}
async function verifyPassword(password:string,stored:string){try{const[k,it,salt,hash]=String(stored||"").split("$");if(k!=="pbkdf2"||Number(it)!==ITER||!salt||!hash)return false;const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:ub64(salt),iterations:ITER,hash:"SHA-256"},key,256);return b64(bits)===hash;}catch{return false;}}
async function ensureWorkforceSchema(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,recipient_id TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'info',type TEXT NOT NULL DEFAULT 'info',read_at TEXT,created_at TEXT NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS n1 ON notifications(recipient_id,created_at DESC)"),
 db.prepare("CREATE TABLE IF NOT EXISTS violations(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,type TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'warning',occurred_at TEXT NOT NULL,minutes INTEGER NOT NULL DEFAULT 0,reason TEXT,status TEXT NOT NULL DEFAULT 'open',reviewed_by TEXT,reviewed_at TEXT,created_at TEXT NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS v1 ON violations(employee_id,occurred_at DESC)"),
 db.prepare("CREATE TABLE IF NOT EXISTS leave_requests(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,type TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,reason TEXT,status TEXT NOT NULL DEFAULT 'pending',reviewer_id TEXT,reviewed_at TEXT,created_at TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,assignee_id TEXT,created_by TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'todo',priority TEXT NOT NULL DEFAULT 'normal',due_at TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS performance_reviews(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,period_start TEXT NOT NULL,period_end TEXT NOT NULL,attendance_score REAL NOT NULL DEFAULT 0,punctuality_score REAL NOT NULL DEFAULT 0,reliability_score REAL NOT NULL DEFAULT 0,overall_score REAL NOT NULL DEFAULT 0,notes TEXT,reviewer_id TEXT,created_at TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS payroll_entries(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,period_start TEXT NOT NULL,period_end TEXT NOT NULL,regular_minutes INTEGER NOT NULL DEFAULT 0,overtime_minutes INTEGER NOT NULL DEFAULT 0,late_minutes INTEGER NOT NULL DEFAULT 0,absence_minutes INTEGER NOT NULL DEFAULT 0,adjustment_amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',approved_by TEXT,approved_at TEXT,created_at TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS anomaly_events(id TEXT PRIMARY KEY,employee_id TEXT,type TEXT NOT NULL,score REAL NOT NULL DEFAULT 0,evidence TEXT,status TEXT NOT NULL DEFAULT 'new',detected_at TEXT NOT NULL,resolved_at TEXT)"),
 db.prepare("CREATE TABLE IF NOT EXISTS ai_insights(id TEXT PRIMARY KEY,scope TEXT NOT NULL,scope_id TEXT,kind TEXT NOT NULL,title TEXT NOT NULL,summary TEXT NOT NULL,evidence TEXT,confidence REAL,created_at TEXT NOT NULL,expires_at TEXT)"),
 db.prepare("CREATE TABLE IF NOT EXISTS push_subscriptions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,endpoint TEXT NOT NULL UNIQUE,p256dh TEXT NOT NULL,auth TEXT NOT NULL,created_at TEXT NOT NULL,last_seen_at TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS escape_events(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,job_number TEXT NOT NULL,employee_name TEXT NOT NULL,status TEXT NOT NULL,timestamp TEXT NOT NULL,reason TEXT,actor_id TEXT,actor_name TEXT,lat REAL,lng REAL,created_at TEXT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS device_rebind_requests(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL,job_number TEXT NOT NULL,employee_name TEXT NOT NULL,device_label TEXT,device_id TEXT,reason TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,resolved_at TEXT,resolved_by TEXT)")
]);}
async function notify(db:D1Database,u:string,t:string,b:string,severity="info",type="system"){await db.prepare("INSERT INTO notifications(id,recipient_id,title,body,severity,type,created_at) VALUES(?,?,?,?,?,?,?)").bind(id(),u,t,b,severity,type,now()).run();}
async function rows(db:D1Database,sql:string,...b:any[]){return (await db.prepare(sql).bind(...b).all()).results||[];}

export async function handleWorkforce(req:Request,env:Env,actor:Actor|null,pathname:string){await ensureWorkforceSchema(env.DB);const u=new URL(req.url);const method=req.method;
 if(pathname==="/api/workforce/live"&&method==="POST"&&!actor){const b=await req.json().catch(()=>({})) as any;const action=String(b.action||"");if(action!=="device-rebind-request")return J({error:"غير مصرح"},401);const job=String(b.jobNumber||"").trim(),password=String(b.password||"");if(!job||!password)return J({error:"الرقم الوظيفي ورمز الدخول مطلوبان"},400);const employee=await env.DB.prepare("SELECT id,job_number AS jobNumber,name,pin_hash AS pinHash,device_id AS deviceId FROM employees WHERE job_number=? AND status='active' LIMIT 1").bind(job).first<any>();if(!employee||!(await verifyPassword(password,employee.pinHash)))return J({error:"بيانات الموظف غير صحيحة"},401);if(!employee.deviceId)return J({error:"هذا الحساب لا يحتوي على جهاز مرتبط"},409);const pending=await env.DB.prepare("SELECT id FROM device_rebind_requests WHERE employee_id=? AND status='pending' LIMIT 1").bind(employee.id).first();if(pending)return J({ok:true,pending:true,message:"يوجد طلب إعادة ربط قيد المراجعة بالفعل"});const requestId=id();await env.DB.prepare("INSERT INTO device_rebind_requests(id,employee_id,job_number,employee_name,device_label,device_id,reason,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(requestId,employee.id,employee.jobNumber,employee.name,String(b.deviceLabel||"الهاتف الجديد"),String(b.deviceId||""),String(b.reason||"يريد الموظف إعادة ربط حسابه بهاتف جديد"),"pending",now()).run();const managers=await rows(env.DB,"SELECT id FROM admin_accounts WHERE role IN ('owner','manager','supervisor') AND active=1");for(const m of managers as any[])await notify(env.DB,m.id,"طلب إعادة ربط هاتف",`الموظف ${employee.name} (${employee.jobNumber}) يريد إعادة ربط حسابه بهاتف جديد.`,"warning","device-rebind");return J({ok:true,pending:true,requestId,message:"تم إرسال طلب إعادة ربط الهاتف، راجع الإدارة أو تواصل مع الإداريين"},201);}
 if(pathname==="/api/workforce/live"&&method==="PATCH"&&actor?.role==="staff"){const b=await req.json().catch(()=>({})) as any;const sets:string[]=[];const values:any[]=[];if(typeof b.password==="string"&&b.password.length>=4){sets.push("pin_hash=?");values.push(await hashPassword(b.password));}if(typeof b.avatar==="string"){if(!b.avatar.startsWith("data:image/"))return J({error:"صيغة الصورة غير صحيحة"},400);const comma=b.avatar.indexOf(",");const raw=comma>=0?b.avatar.slice(comma+1):"";const bytes=Math.floor(raw.length*3/4);if(bytes>100*1024)return J({error:"حجم الصورة بعد الضغط يجب ألا يتجاوز 100 كيلوبايت"},413);sets.push("avatar=?");values.push(b.avatar);}if(!sets.length)return J({error:"لا توجد تغييرات"},400);values.push(actor.id);await env.DB.prepare(`UPDATE employees SET ${sets.join(",")} WHERE id=?`).bind(...values).run();const employee=await env.DB.prepare("SELECT * FROM employees WHERE id=? LIMIT 1").bind(actor.id).first<any>();return J({ok:true,employee:{id:employee.id,jobNumber:employee.job_number,name:employee.name,avatar:employee.avatar||null}},200);}
 if(!actor)return J({error:"غير مصرح"},401);
 if(pathname==="/api/workforce/live"&&method==="GET"){
  if(!manage(actor))return J({error:"غير مصرح"},403);
  const [employees,notifications,violations,leaveRequests,tasks,performance,payroll,anomalies,insights,escapes]=await Promise.all([
   rows(env.DB,"SELECT id,job_number AS jobNumber,name,status,role,work_start_time AS workStartTime,work_end_time AS workEndTime,schedule_type AS scheduleType,is_vip AS isVip,auto_check_in AS autoCheckIn,auto_check_out AS autoCheckOut,avatar FROM employees ORDER BY name"),
   rows(env.DB,"SELECT id,title,body,severity,type,read_at AS readAt,created_at AS createdAt FROM notifications WHERE recipient_id=? ORDER BY created_at DESC LIMIT 50",actor.id),
   rows(env.DB,"SELECT v.*,e.name AS employeeName,e.job_number AS jobNumber FROM violations v LEFT JOIN employees e ON e.id=v.employee_id ORDER BY occurred_at DESC LIMIT 100"),
   rows(env.DB,"SELECT l.*,e.name AS employeeName,e.job_number AS jobNumber FROM leave_requests l LEFT JOIN employees e ON e.id=l.employee_id ORDER BY l.created_at DESC LIMIT 100"),
   rows(env.DB,"SELECT t.*,e.name AS assigneeName FROM tasks t LEFT JOIN employees e ON e.id=t.assignee_id ORDER BY t.due_at IS NULL,t.due_at ASC LIMIT 100"),
   rows(env.DB,"SELECT p.*,e.name AS employeeName,e.job_number AS jobNumber FROM performance_reviews p LEFT JOIN employees e ON e.id=p.employee_id ORDER BY p.period_end DESC LIMIT 100"),
   rows(env.DB,"SELECT p.*,e.name AS employeeName,e.job_number AS jobNumber FROM payroll_entries p LEFT JOIN employees e ON e.id=p.employee_id ORDER BY p.period_end DESC LIMIT 100"),
   rows(env.DB,"SELECT a.*,e.name AS employeeName,e.job_number AS jobNumber FROM anomaly_events a LEFT JOIN employees e ON e.id=a.employee_id ORDER BY detected_at DESC LIMIT 100"),
   rows(env.DB,"SELECT * FROM ai_insights ORDER BY created_at DESC LIMIT 50"),
   rows(env.DB,"SELECT x.*,e.name AS employeeName,e.job_number AS jobNumber FROM escape_events x LEFT JOIN employees e ON e.id=x.employee_id ORDER BY x.timestamp DESC LIMIT 100")
  ]);
  const att=await rows(env.DB,"SELECT employee_id AS employeeId,type,timestamp FROM attendance WHERE timestamp>=datetime('now','-1 day') ORDER BY timestamp DESC LIMIT 5000");const checkedIn=new Set((att as any[]).filter(x=>x.type==='check-in').map(x=>x.employeeId));const checkedOut=new Set((att as any[]).filter(x=>x.type==='check-out').map(x=>x.employeeId));const active=(employees as any[]).filter(x=>x.status==='active');
  return J({generatedAt:now(),summary:{total:employees.length,active:active.length,checkedIn:active.filter(x=>checkedIn.has(x.id)&&!checkedOut.has(x.id)).length,checkedOut:active.filter(x=>checkedOut.has(x.id)).length},employees,notifications,violations,leaveRequests,tasks,performance,payroll,anomalies,insights,escapes});
 }

 /* WORKFORCE_OWNER_CONTROLS_PATCH_V1 */
 if(pathname==="/api/workforce/live"&&method==="PATCH"&&actor?.role==="owner"){
  const b=await req.json().catch(()=>({})) as any;
  const employeeId=String(b.employeeId||"").trim();
  if(!employeeId)return J({error:"رقم الموظف مطلوب"},400);
  const employee=await env.DB.prepare("SELECT id,status FROM employees WHERE id=? LIMIT 1").bind(employeeId).first<any>();
  if(!employee)return J({error:"الموظف غير موجود"},404);
  const sets:string[]=[];const values:any[]=[];
  for(const key of ["isVip","autoCheckIn","autoCheckOut"] as const){if(typeof b[key]==="boolean"){sets.push(key==="isVip"?"is_vip=?":key==="autoCheckIn"?"auto_check_in=?":"auto_check_out=?");values.push(b[key]?1:0);}}
  if(!sets.length)return J({error:"لا توجد تغييرات"},400);
  values.push(employeeId);
  await env.DB.prepare(`UPDATE employees SET ${sets.join(",")} WHERE id=?`).bind(...values).run();
  const updated=await env.DB.prepare("SELECT id,job_number AS jobNumber,name,status,is_vip AS isVip,auto_check_in AS autoCheckIn,auto_check_out AS autoCheckOut FROM employees WHERE id=? LIMIT 1").bind(employeeId).first<any>();
  await env.DB.prepare("INSERT INTO audit(id,employee_id,job_number,actor_name,action,result,reason,timestamp,device_id,ip) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id(),employeeId,updated?.jobNumber||"",actor.name||"المالك","workforce-controls","success","تحديث إعدادات Workforce من بطاقة الموظف",now(),"OWNER_PANEL","unknown").run().catch(()=>undefined);
  return J({ok:true,employee:updated});
 }
 if(pathname==="/api/workforce/live"&&method==="POST"&&actor?.role==="owner"){
  const b=await req.json().catch(()=>({})) as any;
  const employeeId=String(b.employeeId||"").trim();const type=String(b.type||"");
  if(!employeeId||!["check-in","check-out"].includes(type))return J({error:"بيانات الإجراء غير صحيحة"},400);
  const employee=await env.DB.prepare("SELECT id,job_number AS jobNumber,name,status,location_id AS locationId FROM employees WHERE id=? LIMIT 1").bind(employeeId).first<any>();
  if(!employee||employee.status!=="active")return J({error:"الموظف غير موجود أو موقوف"},404);
  const last=await env.DB.prepare("SELECT type FROM attendance WHERE employee_id=? ORDER BY timestamp DESC LIMIT 1").bind(employeeId).first<any>();
  if(type==="check-in"&&last?.type==="check-in")return J({error:"الموظف مسجل حضور بالفعل"},409);
  if(type==="check-out"&&last?.type!=="check-in")return J({error:"لا يوجد حضور مفتوح للموظف"},409);
  const location=(await env.DB.prepare("SELECT id,lat,lng FROM locations WHERE id=? LIMIT 1").bind(employee.locationId||"main").first<any>()) || (await env.DB.prepare("SELECT id,lat,lng FROM locations ORDER BY name LIMIT 1").first<any>());
  if(!location)return J({error:"لا يوجد موقع عمل محفوظ"},409);
  const recordId=id();const timestamp=now();const deviceId=`admin-direct:${actor.id}`;
  await env.DB.prepare("INSERT INTO attendance(id,employee_id,job_number,employee_name,type,timestamp,lat,lng,distance_meters,device_id,ip,qr_code,location_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(recordId,employee.id,employee.jobNumber,employee.name,type,timestamp,Number(location.lat),Number(location.lng),0,deviceId,"unknown","ADMIN_DIRECT",location.id).run();
  await env.DB.prepare("INSERT INTO audit(id,employee_id,job_number,actor_name,action,result,reason,timestamp,device_id,ip,lat,lng,distance_meters) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id(),employee.id,employee.jobNumber,actor.name||"المالك",type,"success",type==="check-in"?"تحضير مباشر من بطاقة الموظف":"انصراف مباشر من بطاقة الموظف",timestamp,deviceId,"unknown",Number(location.lat),Number(location.lng),0).run().catch(()=>undefined);
  return J({ok:true,record:{id:recordId,employeeId:employee.id,jobNumber:employee.jobNumber,employeeName:employee.name,type,timestamp,lat:Number(location.lat),lng:Number(location.lng),distanceMeters:0,deviceId,qrCode:"ADMIN_DIRECT",locationId:location.id}},201);
 }
 if(pathname==="/api/notifications"&&method==="GET")return J(await rows(env.DB,"SELECT id,recipient_id AS recipientId,recipient_id AS userId,title,body,severity,type,read_at AS readAt,created_at AS createdAt FROM notifications WHERE recipient_id=? ORDER BY created_at DESC LIMIT 100",actor.id));
 if(pathname==="/api/notifications/read"&&method==="POST"){const b=await req.json().catch(()=>({})) as any;if(b.id)await env.DB.prepare("UPDATE notifications SET read_at=? WHERE id=? AND recipient_id=?").bind(now(),b.id,actor.id).run();else await env.DB.prepare("UPDATE notifications SET read_at=? WHERE recipient_id=? AND read_at IS NULL").bind(now(),actor.id).run();return J({ok:true});}
 if(pathname==="/api/device-rebind-requests"&&method==="GET"){if(!admin(actor))return J({error:"غير مصرح"},403);return J(await rows(env.DB,"SELECT * FROM device_rebind_requests WHERE status='pending' ORDER BY created_at DESC LIMIT 100"));}
 if(pathname==="/api/device-rebind-requests"&&method==="PATCH"){if(!admin(actor))return J({error:"غير مصرح"},403);const b=await req.json().catch(()=>({})) as any;const requestId=String(b.id||""),status=String(b.status||"");if(!requestId||!["approved","rejected"].includes(status))return J({error:"بيانات الطلب غير صحيحة"},400);const r=await env.DB.prepare("SELECT * FROM device_rebind_requests WHERE id=? AND status='pending' LIMIT 1").bind(requestId).first<any>();if(!r)return J({error:"الطلب غير موجود أو تمت معالجته"},404);if(status==="approved")await env.DB.prepare("UPDATE employees SET device_id=NULL,device_label=NULL WHERE id=?").bind(r.employee_id).run();await env.DB.prepare("UPDATE device_rebind_requests SET status=?,resolved_at=?,resolved_by=? WHERE id=?").bind(status,now(),actor.id,requestId).run();await notify(env.DB,r.employee_id,status==="approved"?"تمت الموافقة على إعادة ربط الهاتف":"تم رفض طلب إعادة ربط الهاتف",status==="approved"?"يمكنك الآن تسجيل الدخول من هاتفك الجديد.":"لم تتم الموافقة على طلب إعادة الربط.",status==="approved"?"success":"warning","device-rebind");return J({ok:true});}
 if(pathname==="/api/violations"&&method==="GET")return manage(actor)?J(await rows(env.DB,"SELECT v.*,e.name AS employeeName,e.job_number AS jobNumber FROM violations v LEFT JOIN employees e ON e.id=v.employee_id ORDER BY occurred_at DESC LIMIT 500")):J({error:"غير مصرح"},403);
 if(pathname==="/api/violations"&&method==="POST"){if(!manage(actor))return J({error:"غير مصرح"},403);const b=await req.json().catch(()=>({})) as any;const e=await env.DB.prepare("SELECT id FROM employees WHERE id=?").bind(String(b.employeeId||"")).first();if(!e)return J({error:"EMPLOYEE_NOT_FOUND"},404);const r={id:id(),employeeId:String(b.employeeId),type:String(b.type||"other"),severity:String(b.severity||"warning"),occurredAt:String(b.occurredAt||now()),minutes:Math.max(0,Number(b.minutes||0)),reason:b.reason?String(b.reason):null,status:"open",createdAt:now()};await env.DB.prepare("INSERT INTO violations(id,employee_id,type,severity,occurred_at,minutes,reason,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(r.id,r.employeeId,r.type,r.severity,r.occurredAt,r.minutes,r.reason,r.status,r.createdAt).run();await notify(env.DB,r.employeeId,"مخالفة حضور جديدة",`تم تسجيل مخالفة: ${r.type}`,"warning","violation");return J({ok:true,violation:r},201);}
 const vm=pathname.match(/^\/api\/violations\/([^/]+)$/);if(vm&&method==="PATCH"){if(!manage(actor))return J({error:"غير مصرح"},403);const b=await req.json().catch(()=>({})) as any;const s=String(b.status||"");if(!["open","accepted","rejected","resolved"].includes(s))return J({error:"حالة غير صحيحة"},400);await env.DB.prepare("UPDATE violations SET status=?,reviewed_by=?,reviewed_at=? WHERE id=?").bind(s,actor.id,now(),vm[1]).run();return J({ok:true,status:s});}
 if(pathname==="/api/ai/insights/generate"&&method==="POST"){if(!manage(actor))return J({error:"غير مصرح"},403);const total=Number((await env.DB.prepare("SELECT COUNT(*) c FROM employees WHERE status='active'").first<any>())?.c||0);const checked=Number((await env.DB.prepare("SELECT COUNT(DISTINCT employee_id) c FROM attendance WHERE type='check-in' AND timestamp>=datetime('now','-1 day')").first<any>())?.c||0);const rate=total?Math.round(checked/total*100):0;const r={id:id(),scope:"dashboard",scopeId:null,kind:"attendance-summary",title:"ملخص الحضور الذكي",summary:`نسبة الحضور خلال آخر 24 ساعة ${rate}% (${checked}/${total}).`,evidence:JSON.stringify({checked,total,rate}),confidence:.98,createdAt:now()};await env.DB.prepare("INSERT INTO ai_insights(id,scope,scope_id,kind,title,summary,evidence,confidence,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(r.id,r.scope,r.scopeId,r.kind,r.title,r.summary,r.evidence,r.confidence,r.createdAt).run();return J({ok:true,insight:r},201);}
 if(pathname==="/api/anomalies/scan"&&method==="POST"){if(!manage(actor))return J({error:"غير مصرح"},403);const es=await rows(env.DB,"SELECT id FROM employees WHERE status='active'");const created:any[]=[];for(const e of es as any[]){const c=Number((await env.DB.prepare("SELECT COUNT(*) c FROM audit WHERE employee_id=? AND result='rejected' AND timestamp>=datetime('now','-7 day')").bind(e.id).first<any>())?.c||0);if(c>=3){const r={id:id(),employeeId:e.id,type:"repeated-rejected-actions",score:Math.min(100,50+c*10),evidence:`${c} محاولات مرفوضة خلال 7 أيام`,status:"new",detectedAt:now()};await env.DB.prepare("INSERT INTO anomaly_events(id,employee_id,type,score,evidence,status,detected_at) VALUES(?,?,?,?,?,?,?)").bind(r.id,r.employeeId,r.type,r.score,r.evidence,r.status,r.detectedAt).run();created.push(r);}}return J({ok:true,created});}
 if(pathname==="/api/escape-events"&&method==="POST"){if(!manage(actor))return J({error:"غير مصرح"},403);const b=await req.json().catch(()=>({})) as any;const eid=String(b.employeeId||""),s=String(b.status||"");if(!eid||!["escaped","returned"].includes(s))return J({error:"بيانات الهروب غير صحيحة"},400);const e=await env.DB.prepare("SELECT id,name,job_number AS jobNumber FROM employees WHERE id=?").bind(eid).first<any>();if(!e)return J({error:"EMPLOYEE_NOT_FOUND"},404);const last=await env.DB.prepare("SELECT status FROM escape_events WHERE employee_id=? ORDER BY timestamp DESC LIMIT 1").bind(eid).first<any>();if((s==='escaped'&&last?.status==='escaped')||(s==='returned'&&last?.status!=='escaped'))return J({error:"تسلسل حالة الهروب غير صحيح"},409);const r={id:id(),employeeId:eid,jobNumber:e.jobNumber,employeeName:e.name,status:s,timestamp:now(),reason:b.reason?String(b.reason):null,actorId:actor.id,actorName:actor.name||null,lat:b.lat==null?null:Number(b.lat),lng:b.lng==null?null:Number(b.lng),createdAt:now()};await env.DB.prepare("INSERT INTO escape_events(id,employee_id,job_number,employee_name,status,timestamp,reason,actor_id,actor_name,lat,lng,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(r.id,r.employeeId,r.jobNumber,r.employeeName,r.status,r.timestamp,r.reason,r.actorId,r.actorName,r.lat,r.lng,r.createdAt).run();await notify(env.DB,eid,s==='escaped'?"تم تسجيل الهروب":"تم تسجيل العودة",s==='escaped'?"تم تسجيل حالة هروب":"تم تسجيل عودتك للعمل",s==='escaped'?"danger":"success","escape");return J({ok:true,event:r},201);}
 return J({error:"WORKFORCE_ROUTE_NOT_FOUND"},404);
}