import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { currentSession } from "@/lib/auth";
import { getManagerSession } from "@/lib/storage";
import { getBackendAttendance, getBackendEmployeeProfile, backendEnabled } from "@/lib/backend";
import { answerEmployeeQuestion, answerManagerQuestion, employeeExamples, managerExamples, type AIAnswer } from "@/lib/localAI";
const API_URL=String(import.meta.env.VITE_API_URL||"https://hadir-api.abunizar963.workers.dev").replace(/\/$/,"");
const managerToken=()=>typeof window==="undefined"?"":localStorage.getItem("hadir.api.token.admin")||"";
type Msg={role:"user"|"assistant";text:string;items?:string[]};
export default function AIAssistant(){
 const nav=useNavigate();const employeeSession=currentSession();const managerSession=getManagerSession();const manager=Boolean(managerSession&&!employeeSession);const[question,setQuestion]=useState("");const[messages,setMessages]=useState<Msg[]>([]);const[busy,setBusy]=useState(false);const[employee,setEmployee]=useState<any>(null);const[attendance,setAttendance]=useState<any[]>([]);const[managerData,setManagerData]=useState<any>(null);const examples=manager?managerExamples:employeeExamples;
 useEffect(()=>{let alive=true;(async()=>{try{if(!backendEnabled)return;if(manager){const r=await fetch(`${API_URL}/api/workforce/live`,{headers:{authorization:`Bearer ${managerToken()}`},credentials:"include",cache:"no-store"});if(r.ok&&alive)setManagerData(await r.json());}else{const[p,a]=await Promise.all([getBackendEmployeeProfile(),getBackendAttendance(5000)]);if(alive){setEmployee(p);setAttendance(Array.isArray(a)?a:[]);}}}catch{/* يبقى المساعد متاحًا حتى عند تعذر المزامنة */}})();return()=>{alive=false;};},[manager]);
 const intro=useMemo(()=>manager?`مرحبًا ${managerSession?.name||"مدير النظام"}. أنا مساعد Hadir الذكي المجاني. أستطيع تحليل بيانات الحضور والغياب والهروب والإحصاءات المتاحة ضمن صلاحياتك.`:`مرحبًا ${employee?.name||employeeSession?.employeeId||""}. أنا مساعد Hadir المجاني. أستطيع تحليل بيانات حضورك أنت فقط.`,[manager,managerSession?.name,employee?.name,employeeSession?.employeeId]);
 useEffect(()=>setMessages([{role:"assistant",text:intro}]),[intro]);
 const ask=(q:string)=>{const text=q.trim();if(!text||busy)return;setQuestion("");setMessages(m=>[...m,{role:"user",text}]);setBusy(true);window.setTimeout(()=>{let a:AIAnswer;if(manager){const d=managerData||{employees:[],attendance:[],escapes:[]};a=answerManagerQuestion(text,{employees:d.employees||[],attendance:d.attendance||[],escapes:d.escapes||[]});}else if(employee){a=answerEmployeeQuestion(text,employee,attendance);}else a={text:"لم تكتمل مزامنة بياناتك بعد. حاول مرة أخرى بعد لحظات."};setMessages(m=>[...m,{role:"assistant",text:a.text,items:a.items}]);setBusy(false);},120);};
 return <div dir="rtl" className="min-h-screen bg-background text-foreground"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 sm:py-10"><div className="flex items-center justify-between gap-3 mb-6"><button onClick={()=>nav(-1)} className="rounded-xl border border-border px-4 py-2 text-sm font-bold hover:bg-secondary">← العودة</button><div className="text-right"><div className="text-xs text-primary font-bold">Hadir AI · مجاني</div><h1 className="text-2xl font-black">المساعد الذكي</h1><p className="text-xs text-muted-foreground mt-1">تحليل موسّع للحضور والغياب والهروب والإحصاءات، مع احترام صلاحيات كل مستخدم.</p></div></div><section className="hud-card p-4 sm:p-6"><div className="flex gap-3 items-start"><div className="h-12 w-12 rounded-2xl bg-primary/12 text-primary grid place-items-center text-xl font-black">AI</div><div className="flex-1"><div className="font-black">{manager?"مساعد المدير":"مساعد الموظف"}</div><div className="text-xs text-muted-foreground mt-1">{manager?"يحلل بيانات الموظفين المتاحة للمدير.":"يحلل بياناتك أنت فقط ولا يكشف بيانات الموظفين الآخرين."}</div></div></div><div className="mt-5 flex flex-wrap gap-2">{examples.map(x=><button key={x} onClick={()=>ask(x)} className="rounded-full border border-border bg-secondary/50 px-3 py-2 text-xs font-semibold hover:border-primary/40 hover:text-primary transition">{x}</button>)}</div><div className="mt-5 space-y-3 max-h-[52vh] overflow-y-auto pr-1">{messages.map((m,i)=><div key={i} className={`rounded-2xl p-4 ${m.role==="user"?"bg-primary/10 mr-8":"bg-secondary/50 ml-8"}`}><div className="text-sm leading-7">{m.text}</div>{m.items&&<ul className="mt-2 space-y-1 text-xs text-muted-foreground">{m.items.map((x,j)=><li key={j}>• {x}</li>)}</ul>}</div>)}{busy&&<div className="text-xs text-muted-foreground animate-pulse">يحلل بيانات النظام…</div>}</div><form onSubmit={e=>{e.preventDefault();ask(question);}} className="mt-5 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder={manager?"اسأل عن الحضور والغياب والهروب والإحصاءات…":"اسأل عن حضورك وغيابك وسجلاتك…"} className="flex-1 rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><button disabled={!question.trim()||busy} className="rounded-xl bg-primary text-primary-foreground px-5 py-3 text-sm font-black disabled:opacity-40">اسأل</button></form></section></div></div>;
}
