import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { currentSession } from "@/lib/auth";
import { getManagerSession } from "@/lib/storage";
import { getBackendAttendance, getBackendEmployeeProfile, backendEnabled } from "@/lib/backend";
import { answerEmployeeQuestion, answerManagerQuestion, employeeExamples, managerExamples, type AIAnswer, type AIContext } from "@/lib/localAI";
import { getPrayerTimes, qiblaBearing } from "@/lib/prayerTimes";
const API_URL=String(import.meta.env.VITE_API_URL||"https://hadir-api.abunizar963.workers.dev").replace(/\/$/,"");
type Msg={role:"user"|"assistant";text:string;items?:string[]};
const weatherLabel=(code:number)=>code===0?"صافي":code<=3?"غائم جزئيًا":code<=48?"ضباب":code<=67?"أمطار":code<=77?"ثلوج":code<=82?"زخات مطر":code<=86?"زخات ثلج":"عاصفة";
function aiToken(manager:boolean){if(typeof window==="undefined")return "";return localStorage.getItem(manager?"hadir.api.token.admin":"hadir.api.token.employee")||"";}
async function remoteAI(question:string,manager:boolean){
 const token=aiToken(manager);
 const headers=new Headers({"content-type":"application/json"});
 if(token)headers.set("authorization",`Bearer ${token}`);
 const response=await fetch(`${API_URL}/api/ai`,{method:"POST",headers,credentials:"include",cache:"no-store",body:JSON.stringify({question})});
 const data=await response.json().catch(()=>({}));
 if(!response.ok||!data?.ok||!data?.text)throw new Error(String(data?.error||"تعذر تشغيل النموذج"));
 return {text:String(data.text),provider:String(data.provider||"cloudflare-workers-ai")};
}
export default function AIAssistant(){
 const nav=useNavigate();const employeeSession=currentSession();const managerSession=getManagerSession();const manager=Boolean(managerSession&&!employeeSession);const[question,setQuestion]=useState("");const[messages,setMessages]=useState<Msg[]>([]);const[busy,setBusy]=useState(false);const[employee,setEmployee]=useState<any>(null);const[attendance,setAttendance]=useState<any[]>([]);const[managerData,setManagerData]=useState<any>(null);const[context,setContext]=useState<AIContext>({});const[contextLoading,setContextLoading]=useState(true);const[aiMode,setAiMode]=useState<"cloud"|"local"|null>(null);const examples=manager?managerExamples:employeeExamples;
 useEffect(()=>{let alive=true;(async()=>{try{if(!backendEnabled)return;if(manager){const token=aiToken(true);const r=await fetch(`${API_URL}/api/workforce/live`,{headers:token?{authorization:`Bearer ${token}`}:{},credentials:"include",cache:"no-store"});if(r.ok&&alive)setManagerData(await r.json());}else{const[p,a]=await Promise.all([getBackendEmployeeProfile(),getBackendAttendance(5000)]);if(alive){setEmployee(p);setAttendance(Array.isArray(a)?a:[]);}}}catch{/* يبقى المساعد متاحًا حتى عند تعذر المزامنة */}})();return()=>{alive=false;};},[manager]);
 useEffect(()=>{let alive=true;const controller=new AbortController();const loadContext=async()=>{if(!navigator.geolocation){setContextLoading(false);return;}navigator.geolocation.getCurrentPosition(async position=>{const{latitude,longitude}=position.coords;try{const prayerPromise=getPrayerTimes({latitude,longitude});const weatherPromise=fetch(`https://api.open-meteo.com/v1/forecast?${new URLSearchParams({latitude:String(latitude),longitude:String(longitude),current:"temperature_2m,apparent_temperature,weather_code,wind_speed_10m",timezone:"auto"})}`,{cache:"no-store",signal:controller.signal}).then(r=>r.ok?r.json():null);const geoPromise=fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=ar`,{cache:"no-store",signal:controller.signal}).then(r=>r.ok?r.json():null).catch(()=>null);const[prayer,weather,geo]=await Promise.all([prayerPromise,weatherPromise,geoPromise]);if(!alive)return;const current=weather?.current;setContext({city:geo?.city||geo?.locality||geo?.principalSubdivision||prayer.meta.city||"موقعك الحالي",prayer:prayer.times?{...prayer.times,gregorian:prayer.meta.gregorian,hijri:prayer.meta.hijri}:undefined,weather:current&&typeof current.temperature_2m==="number"?{temp:current.temperature_2m,apparent:current.apparent_temperature,wind:current.wind_speed_10m,description:weatherLabel(Number(current.weather_code))}:undefined,qibla:qiblaBearing(latitude,longitude)});}catch{/* السياق الإضافي اختياري */}finally{if(alive)setContextLoading(false);}},()=>{if(alive)setContextLoading(false)},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});return()=>controller.abort();};void loadContext();return()=>{alive=false;controller.abort();};},[]);
 const intro=useMemo(()=>manager?`مرحبًا ${managerSession?.name||"مدير النظام"}. أنا مساعد Hadir الذكي. أستطيع تحليل بيانات الحضور والغياب والهروب والإحصاءات، والإجابة عن الطقس ومواقيت الصلاة والقبلة حسب موقعك.`:`مرحبًا ${employee?.name||employeeSession?.employeeId||""}. أنا مساعد Hadir الذكي. أستطيع تحليل بيانات حضورك أنت فقط، والإجابة عن الطقس ومواقيت الصلاة والقبلة حسب موقعك.`,[manager,managerSession?.name,employee?.name,employeeSession?.employeeId]);
 useEffect(()=>setMessages([{role:"assistant",text:intro}]),[intro]);
 const ask=async(q:string)=>{const text=q.trim();if(!text||busy)return;setQuestion("");setMessages(m=>[...m,{role:"user",text}]);setBusy(true);try{const answer=await remoteAI(text,manager);setAiMode(answer.provider==="google-gemini"?"cloud":"cloud");setMessages(m=>[...m,{role:"assistant",text:answer.text}]);}catch{let a:AIAnswer;if(manager){const d=managerData||{employees:[],attendance:[],escapes:[]};a=answerManagerQuestion(text,{employees:d.employees||[],attendance:d.attendance||[],escapes:d.escapes||[]},context);}else if(employee){a=answerEmployeeQuestion(text,employee,attendance,context);}else a={text:"لم تكتمل مزامنة بياناتك بعد. حاول مرة أخرى بعد لحظات."};setAiMode("local");setMessages(m=>[...m,{role:"assistant",text:a.text,items:a.items}]);}finally{setBusy(false);}};
 return <div dir="rtl" className="min-h-screen bg-background text-foreground"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 sm:py-10"><div className="flex items-center justify-between gap-3 mb-6"><button onClick={()=>nav(-1)} className="rounded-xl border border-border px-4 py-2 text-sm font-bold hover:bg-secondary">← العودة</button><div className="text-right"><div className="text-xs text-primary font-bold">Hadir AI · {aiMode==="cloud"?"AI سحابي":aiMode==="local"?"محلي":"مجاني"}</div><h1 className="text-2xl font-black">المساعد الذكي</h1><p className="text-xs text-muted-foreground mt-1">تحليل موسّع للحضور والغياب والهروب والإحصاءات، مع الطقس ومواقيت الصلاة والقبلة وربطها ببيانات النظام.</p></div></div><section className="hud-card p-4 sm:p-6"><div className="flex gap-3 items-start"><div className="h-12 w-12 rounded-2xl bg-primary/12 text-primary grid place-items-center text-xl font-black">AI</div><div className="flex-1"><div className="font-black">{manager?"مساعد المدير":"مساعد الموظف"}</div><div className="text-xs text-muted-foreground mt-1">{manager?"يحلل بيانات الموظفين المتاحة للمدير.":"يحلل بياناتك أنت فقط ولا يكشف بيانات الموظفين الآخرين."}</div></div></div><div className="mt-5 flex flex-wrap gap-2">{examples.map(x=><button key={x} onClick={()=>ask(x)} className="rounded-full border border-border bg-secondary/50 px-3 py-2 text-xs font-semibold hover:border-primary/40 hover:text-primary transition">{x}</button>)}</div><div className="mt-3 text-[11px] text-muted-foreground">{contextLoading?"جاري مزامنة الطقس ومواقيت الصلاة والقبلة…":context.city?`الموقع المرتبط بالمساعد: ${context.city}`:"لم يتوفر الموقع؛ يمكنك تفعيل الموقع للحصول على الإجابات المحلية."}</div><div className="mt-5 space-y-3 max-h-[52vh] overflow-y-auto pr-1">{messages.map((m,i)=><div key={i} className={`rounded-2xl p-4 ${m.role==="user"?"bg-primary/10 mr-8":"bg-secondary/50 ml-8"}`}><div className="text-sm leading-7">{m.text}</div>{m.items&&<ul className="mt-2 space-y-1 text-xs text-muted-foreground">{m.items.map((x,j)=><li key={j}>• {x}</li>)}</ul>}</div>)}{busy&&<div className="text-xs text-muted-foreground animate-pulse">يتحقق من نموذج الذكاء الاصطناعي…</div>}</div><form onSubmit={e=>{e.preventDefault();void ask(question);}} className="mt-5 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder={manager?"اسأل عن الموظفين أو الطقس أو الصلاة أو القبلة…":"اسأل عن حضورك أو الطقس أو الصلاة أو القبلة…"} className="flex-1 rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><button disabled={!question.trim()||busy} className="rounded-xl bg-primary text-primary-foreground px-5 py-3 text-sm font-black disabled:opacity-40">اسأل</button></form></section></div></div>;
}