import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Camera, KeyRound, ShieldCheck } from "lucide-react";
import { currentSession } from "@/lib/auth";
import { getBackendEmployeeProfile } from "@/lib/backend";

const API_URL=String(import.meta.env.VITE_API_URL||"https://hadir-api.abunizar963.workers.dev").replace(/\/$/,"");
const deviceId=()=>localStorage.getItem("hadir.device.id")||"";
function compress(file:File):Promise<string>{return new Promise((resolve,reject)=>{const img=new Image();const canvas=document.createElement("canvas");const reader=new FileReader();reader.onload=()=>{img.onload=()=>{const size=512;const scale=Math.min(1,size/Math.max(img.width,img.height));canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return reject(new Error("تعذر تجهيز الصورة"));ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/webp",.78));};img.onerror=()=>reject(new Error("تعذر قراءة الصورة"));img.src=String(reader.result);};reader.onerror=()=>reject(new Error("تعذر قراءة الملف"));reader.readAsDataURL(file);});}
async function saveProfile(body:Record<string,unknown>){const token=localStorage.getItem("hadir.api.token.employee")||"";const res=await fetch(`${API_URL}/api/workforce/live`,{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`,"x-device-id":deviceId()},body:JSON.stringify(body),cache:"no-store"});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(typeof data.error==="string"?data.error:"تعذر حفظ الملف الشخصي");return data;}
export default function EmployeeProfile(){const navigate=useNavigate();const session=currentSession();const [name,setName]=useState(session?.name||"");const [avatar,setAvatar]=useState<string|null>(null);const [newPassword,setNewPassword]=useState("");const [confirm,setConfirm]=useState("");const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");useEffect(()=>{void getBackendEmployeeProfile().then(p=>{setName(p.name);setAvatar(p.avatar||null);}).catch(()=>undefined);},[]);
 const photo=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{setError("");const data=await compress(file);setAvatar(data);await saveProfile({avatar:data});setMessage("تم تحديث الصورة الشخصية بنجاح");}catch(err){setError(err instanceof Error?err.message:"تعذر تحديث الصورة");}};
 const password=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");if(newPassword.length<4)return setError("كلمة السر يجب أن تتكون من 4 أحرف/أرقام على الأقل.");if(newPassword!==confirm)return setError("تأكيد كلمة السر غير مطابق.");setSaving(true);try{await saveProfile({password:newPassword});setNewPassword("");setConfirm("");setMessage("تم تغيير كلمة السر بنجاح");}catch(err){setError(err instanceof Error?err.message:"تعذر تغيير كلمة السر");}finally{setSaving(false);}};
 return <main dir="rtl" className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-xl space-y-4"><button onClick={()=>navigate(-1)} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2 text-sm font-bold"><ArrowRight className="h-4 w-4"/>العودة</button><section className="hud-card overflow-hidden p-6"><div className="flex items-center gap-4"><div className="relative"><div className="grid h-24 w-24 place-items-center overflow-hidden rounded-3xl border-2 border-primary/30 bg-primary/10 text-3xl font-black text-primary">{avatar?<img src={avatar} alt={name} className="h-full w-full object-cover"/>:name.charAt(0)||"م"}</div><label className="absolute -bottom-2 -left-2 grid h-10 w-10 cursor-pointer place-items-center rounded-xl bg-primary text-primary-foreground shadow-lg"><Camera className="h-5 w-5"/><input type="file" accept="image/*" className="hidden" onChange={photo}/></label></div><div><div className="text-xs text-muted-foreground">الملف الشخصي</div><h1 className="text-2xl font-black">{name}</h1><p className="mt-1 text-xs text-muted-foreground">يمكنك تغيير صورتك وكلمة السر الخاصة بحسابك.</p></div></div></section><section className="hud-card p-6"><div className="flex items-center gap-2 font-black"><KeyRound className="h-5 w-5 text-primary"/>تغيير كلمة السر</div><form onSubmit={password} className="mt-5 space-y-4"><input className="input w-full" type="password" autoComplete="new-password" placeholder="كلمة السر الجديدة" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><input className="input w-full" type="password" autoComplete="new-password" placeholder="تأكيد كلمة السر" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="btn-primary w-full" disabled={saving}>{saving?"جاري الحفظ…":"حفظ كلمة السر"}</button></form><div className="mt-4 flex items-start gap-2 rounded-xl border border-primary/20 bg-primary/5 p-3 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0 text-primary"/>تُحفظ كلمة السر في الخادم باستخدام PBKDF2 ولا يتم تخزينها كنص مكشوف.</div>{message&&<div className="mt-3 rounded-xl border border-primary/30 bg-primary/10 p-3 text-sm text-primary">{message}</div>}{error&&<div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}</section></div></main>;}