import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Brand from "@/components/Brand";
import { currentSession } from "@/lib/auth";
import { getSettings, type RequestType } from "@/lib/storage";
import { backendEnabled, getBackendAttendance, getBackendEmployeeProfile, getBackendLocations, createBackendRequest } from "@/lib/backend";
import { getEmployeeScheduleStatus, getActiveWorkPeriod, getScheduleCountdown } from "@/lib/schedule";
import { formatDurationMinutes, formatTime, minutesBetween, normalizeDigits } from "@/lib/utils";
import type { AttendanceRecord, Employee, Location } from "@/types";

const PROFILE_TIMEOUT_MS=12000;const API_URL=String(import.meta.env.VITE_API_URL||"https://hadir-api.abunizar963.workers.dev").replace(/\/$/,"");
function periodRecords(rows:AttendanceRecord[],employeeId:string,start:Date|null,end:Date|null){return rows.filter(r=>{if(r.employeeId!==employeeId)return false;const t=new Date(r.timestamp).getTime();return !start||(t>=start.getTime()&&(!end||t<=end.getTime()+60000));}).sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime());}
function countdownText(target:Date|null,now:Date){if(!target)return "";const ms=target.getTime()-now.getTime();if(ms<=0)return "";const total=Math.floor(ms/1000);const days=Math.floor(total/86400);const hours=Math.floor((total%86400)/3600);const minutes=Math.floor((total%3600)/60);const seconds=total%60;const text=days>0?`${days} يوم ${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`:`${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`;return normalizeDigits(text);}
function clockText(value:string|undefined,fallback="09:00"){return /^\d{1,2}:\d{2}$/.test(String(value||""))?String(value):fallback;}
async function loadAvatar(value:string|null,id:string){if(!value)return null;if(value.startsWith("data:"))return value;const token=localStorage.getItem("hadir.api.token.employee")||"";try{const r=await fetch(`${API_URL}/api/employees/${encodeURIComponent(id)}/avatar`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok)return null;const blob=await r.blob();return URL.createObjectURL(blob);}catch{return null;}}

export default function EmployeeHome(){
 const nav=useNavigate(); const session=currentSession(); const sessionKey=session?`${session.employeeId}|${session.jobNumber}|${session.loginAt}|${session.role??""}`:null;
 const [now,setNow]=useState(new Date()); const [emp,setEmp]=useState<Employee|null>(null); const [avatarSrc,setAvatarSrc]=useState<string|null>(null); const [locations,setLocations]=useState<Location[]>([]); const [attendance,setAttendance]=useState<AttendanceRecord[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [showRequest,setShowRequest]=useState(false); const [requestType,setRequestType]=useState<RequestType>("permission"); const [reason,setReason]=useState(""); const [requestSent,setRequestSent]=useState(false); const [showProfile,setShowProfile]=useState(false); const loadingRef=useRef(false);
 useEffect(()=>{const t=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(t);},[]);
 useEffect(()=>{if(!sessionKey){nav("/login",{replace:true});return;}let cancelled=false;const load=async(initial=false)=>{if(loadingRef.current)return;loadingRef.current=true;if(initial){setLoading(true);setError(null);}try{if(!backendEnabled)throw new Error("الخادم غير مفعّل. يرجى المحاولة لاحقاً.");const timeout=new Promise<never>((_,reject)=>window.setTimeout(()=>reject(new Error("انتهت مهلة الاتصال بالخادم.")),PROFILE_TIMEOUT_MS));const profile=await Promise.race([getBackendEmployeeProfile(),timeout]);if(cancelled)return;if(!profile?.id)throw new Error("لم يتم العثور على ملف الموظف المرتبط بحسابك.");setEmp(profile);if(profile.avatar){const src=await loadAvatar(profile.avatar,profile.id);if(!cancelled)setAvatarSrc(src);}else setAvatarSrc(null);const [a,l]=await Promise.allSettled([getBackendAttendance(500),getBackendLocations()]);if(cancelled)return;if(a.status==="fulfilled"&&Array.isArray(a.value))setAttendance(a.value);if(l.status==="fulfilled"&&Array.isArray(l.value))setLocations(l.value);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"تعذر تحميل بيانات الموظف.");}finally{if(!cancelled&&initial)setLoading(false);loadingRef.current=false;}};void load(true);const refresh=()=>void load(false);window.addEventListener("hadir:cloud-data-changed",refresh);window.addEventListener("hadir:d1-view-changed",refresh);return()=>{cancelled=true;window.removeEventListener("hadir:cloud-data-changed",refresh);window.removeEventListener("hadir:d1-view-changed",refresh);};},[sessionKey,nav]);
 useEffect(()=>()=>{if(avatarSrc?.startsWith("blob:"))URL.revokeObjectURL(avatarSrc);},[avatarSrc]);
 const settings=getSettings(); const schedule=useMemo(()=>getEmployeeScheduleStatus(emp,now),[emp,now]); const period=useMemo(()=>getActiveWorkPeriod(emp,now),[emp,now]); const countdown=useMemo(()=>getScheduleCountdown(emp,now),[emp,now]); const remaining=useMemo(()=>countdownText(countdown.target,now),[countdown.target,now]);const currentRecords=useMemo(()=>periodRecords(attendance,emp?.id||"",period.start,period.end),[attendance,emp?.id,period.start?.getTime(),period.end?.getTime()]);const latest=useMemo(()=>attendance.filter(r=>r.employeeId===emp?.id).sort((a,b)=>new Date(b.timestamp).getTime()-new Date(a.timestamp).getTime())[0],[attendance,emp?.id]);const openSession=latest?.type==="check-in"?latest:undefined;const pair=useMemo(()=>{if(openSession)return{checkIn:openSession,checkOut:undefined};const ci=currentRecords.find(r=>r.type==="check-in");const co=ci?currentRecords.find(r=>r.type==="check-out"&&new Date(r.timestamp).getTime()>=new Date(ci.timestamp).getTime()):undefined;return{checkIn:ci,checkOut:co};},[openSession,currentRecords]);const checkIn=pair.checkIn;const checkOut=pair.checkOut;const workedMinutes=checkIn?minutesBetween(checkIn.timestamp,checkOut?.timestamp??now.toISOString()):0;const canCheckIn=Boolean(emp&&schedule.isWorkDay&&!openSession&&!currentRecords.some(r=>r.type==="check-in"));const canCheckOut=Boolean(emp&&openSession);let late=0;if(checkIn&&period.start)late=Math.max(0,Math.round((new Date(checkIn.timestamp).getTime()-period.start.getTime())/60000)-(emp?.gracePeriodMinutes??settings.lateGraceMinutes??10));const locationName=emp?.locationId?(locations.find(l=>l.id===emp.locationId)?.name||"الموقع المخصص"):"المقر الرئيسي";const isRotation=emp?.scheduleType==="ROTATION";const rotationOn=Math.max(1,Math.floor(emp?.rotationDaysOn??4));const rotationOff=Math.max(0,Math.floor(emp?.rotationDaysOff??4));const rotationStartClock=clockText(emp?.rotationStartTime||emp?.workStartTime,"09:00");const rotationEndClock=clockText(emp?.rotationEndTime||emp?.workEndTime,"16:00");const shiftDurationLabel=isRotation?`${rotationOn} أيام عمل + ${rotationOff} أيام راحة`:(period.start&&period.end?`${formatTime(period.start)} → ${formatTime(period.end)}`:"حسب الجدول الإداري");const shiftHoursLabel=period.start&&period.end?`${formatTime(period.start)} → ${formatTime(period.end)}`:`${rotationStartClock} → ${rotationEndClock}`;const sendRequest=async(e:React.FormEvent)=>{e.preventDefault();if(!emp)return;try{await createBackendRequest({employeeId:emp.id,employeeName:emp.name,jobNumber:emp.jobNumber,type:requestType,reason});setRequestSent(true);window.setTimeout(()=>{setRequestSent(false);setShowRequest(false);setReason("");},1800);}catch(err){setError(err instanceof Error?err.message:"تعذر إرسال الطلب إلى الخادم.");}};
 if(!sessionKey)return null;if(loading)return <Centered><Brand/><div className="mt-5 font-bold">جاري تحميل بياناتك</div><div className="text-xs text-muted-foreground mt-2">يتم مزامنة الجدول والحضور من الخادم.</div></Centered>;if(error||!emp)return <Centered><Brand/><div className="mt-5 font-bold">تعذر تحميل بيانات الموظف</div><div className="text-sm text-muted-foreground mt-2">{error||"لم يتم العثور على ملف الموظف."}</div><button className="btn-primary mt-5 w-full" onClick={()=>window.location.reload()}>إعادة المحاولة</button></Centered>;const showCountdown=countdown.kind!=="NONE"&&Boolean(countdown.target)&&Boolean(remaining);
 return <div className="min-h-screen bg-background">
 <main className="max-w-xl mx-auto px-4 sm:px-5 pb-16 space-y-4"><section className="hud-card overflow-hidden p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3 min-w-0"><div className="h-14 w-14 rounded-2xl bg-primary/12 grid place-items-center border border-primary/25 shrink-0 overflow-hidden">{avatarSrc?<img src={avatarSrc} alt={emp.name} className="h-full w-full object-cover"/>:<span className="text-primary font-black text-xl">{emp.name.charAt(0)||"م"}</span>}</div><div className="min-w-0"><div className="text-xs text-muted-foreground">مرحبًا بك</div><div className="font-black text-xl truncate">{emp.name}</div><div className="text-xs text-muted-foreground mt-0.5">{emp.jobNumber} · {locationName}</div></div></div><div className="text-left shrink-0"><div className="mono text-xl font-black tabular-nums">{normalizeDigits(now.toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit",hour12:false}))}</div><div className="text-[10px] text-muted-foreground mt-1">{normalizeDigits(now.toLocaleDateString("ar-EG",{weekday:"short",day:"2-digit",month:"short"}))}</div></div></div><div className={`mt-5 rounded-2xl border p-4 ${schedule.isWorkDay?"border-primary/30 bg-primary/8":"border-accent/30 bg-accent/8"}`}><div className="flex items-center justify-between gap-3"><div><div className="text-xs text-muted-foreground">حالة اليوم</div><div className="font-black text-lg mt-0.5">{schedule.isWorkDay?"في المناوبة":"فترة راحة"}</div></div><span className={`badge ${schedule.isWorkDay?"bg-primary/15 text-primary":"bg-accent/15 text-accent"}`}>{schedule.isWorkDay?"عمل":"راحة"}</span></div><div className="text-xs text-muted-foreground mt-1">{isRotation?(schedule.detail||`اليوم ${schedule.cycleDay??1} في المناوبة`):schedule.label}</div>{showCountdown&&<div className="mt-4 rounded-xl bg-background/55 border border-border/40 p-3"><div className="text-[10px] text-muted-foreground">{schedule.isWorkDay?"تنتهي المناوبة خلال":"تبدأ المناوبة القادمة خلال"}</div><div className="mono text-2xl font-black tabular-nums tracking-wide mt-1">{remaining}</div></div>}</div>{late>0&&<div className="mt-3 rounded-xl border border-[hsl(var(--warning))]/40 bg-[hsl(var(--warning))]/10 p-3 text-xs text-[hsl(var(--warning))]">تم رصد تأخر {normalizeDigits(String(late))} دقيقة عن بداية الفترة.</div>}</section>
 <section className="grid grid-cols-2 gap-3"><Link to="/employee/scan/check-in" aria-disabled={!canCheckIn} className={`hud-card p-4 sm:p-5 transition-transform ${!canCheckIn?"opacity-45 pointer-events-none":"hover:-translate-y-0.5"}`}><div className="h-10 w-10 rounded-xl bg-primary/12 grid place-items-center text-primary mb-3 text-xl font-black" aria-hidden="true">↓</div><div className="font-black">تسجيل حضور</div><div className="text-xs text-muted-foreground mt-1 leading-5">{!schedule.isWorkDay?"أنت في الراحة":openSession?"الدوام جارٍ":"مسح رمز QR"}</div></Link><Link to="/employee/scan/check-out" aria-disabled={!canCheckOut} className={`hud-card p-4 sm:p-5 transition-transform ${!canCheckOut?"opacity-45 pointer-events-none":"hover:-translate-y-0.5"}`}><div className="h-10 w-10 rounded-xl bg-accent/12 grid place-items-center text-accent mb-3 text-xl font-black" aria-hidden="true">↑</div><div className="font-black">تسجيل انصراف</div><div className="text-xs text-muted-foreground mt-1 leading-5">{openSession?"إنهاء الدوام الآن":checkOut?"تم تسجيل الانصراف":"بعد تسجيل الحضور"}</div></Link></section>
 <section className="hud-card p-5"><div className="flex items-center justify-between mb-3"><div><div className="text-xs text-muted-foreground">ملخص اليوم</div><div className="font-black mt-0.5">سجل الدوام</div></div><span className="badge bg-secondary/70">اليوم</span></div><div className="grid grid-cols-3 gap-2"><Stat label="الحضور" value={checkIn?formatTime(checkIn.timestamp):"—"}/><Stat label="الانصراف" value={checkOut?formatTime(checkOut.timestamp):"—"}/><Stat label="مدة العمل" value={formatDurationMinutes(workedMinutes)}/></div></section>
 <section className="hud-card p-5"><div className="flex items-center justify-between mb-3"><div><div className="text-xs text-muted-foreground">معلومات الدوام</div><div className="font-black mt-0.5">حالتك الحالية</div></div><span className={`badge ${schedule.isWorkDay?"bg-primary/15 text-primary":"bg-accent/15 text-accent"}`}>{schedule.isWorkDay?"يوم عمل":"راحة"}</span></div><div className="grid grid-cols-2 gap-2 text-xs"><Row label="نوع الدوام" value={isRotation?"تناوبي":"إداري"}/><Row label={isRotation?"مدة الدورة":"وقت الدوام"} value={shiftDurationLabel}/><Row label={isRotation?"وقت المناوبة":"الفترة"} value={shiftHoursLabel}/><Row label="الحالة" value={schedule.label}/><Row label="الجهاز" value={emp.deviceLabel||"غير مرتبط"}/><Row label="الموقع" value={locationName}/></div></section><button onClick={()=>setShowRequest(true)} className="hud-card w-full p-4 text-right border-dashed hover:brightness-105"><div className="flex items-center justify-between"><div><div className="font-black text-accent">طلب استئذان أو إجازة</div><div className="text-xs text-muted-foreground mt-1">إرسال طلب للإدارة</div></div><span className="text-accent text-xl">←</span></div></button></main>
 {showProfile&&<div className="fixed inset-0 z-[10000] bg-black/60 backdrop-blur-sm grid place-items-center p-4" onMouseDown={e=>{if(e.currentTarget===e.target)setShowProfile(false)}}><section className="hud-card w-full max-w-md p-5" role="dialog" aria-modal="true"><div className="flex items-center justify-between"><h2 className="font-black text-xl">الملف الشخصي</h2><button type="button" className="btn-ghost" onClick={()=>setShowProfile(false)} aria-label="إغلاق"><span aria-hidden="true">×</span></button></div><div className="mt-5 flex items-center gap-4"><div className="h-20 w-20 rounded-2xl border border-primary/30 bg-primary/10 overflow-hidden grid place-items-center shrink-0">{avatarSrc?<img src={avatarSrc} alt={emp.name} className="h-full w-full object-cover"/>:<span className="text-primary font-black text-2xl">{emp.name.charAt(0)||"م"}</span>}</div><div><div className="font-black text-lg">{emp.name}</div><div className="text-sm text-muted-foreground mt-1">الرقم الوظيفي: {emp.jobNumber}</div></div></div><Link to="/employee/profile" onClick={()=>setShowProfile(false)} className="btn-primary w-full mt-5 text-center">إدارة الملف الشخصي</Link><Link to="/employee/history" onClick={()=>setShowProfile(false)} className="btn-secondary w-full mt-2 text-center">سجل عملي وطلباتي</Link></section></div>}
 {showRequest&&<div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm grid place-items-center p-4"><form onSubmit={sendRequest} className="hud-card w-full max-w-md p-5"><div className="flex items-center justify-between"><div><div className="text-xs text-muted-foreground">الإدارة</div><h2 className="font-black text-lg">طلب جديد</h2></div><button type="button" className="btn-ghost" onClick={()=>setShowRequest(false)}>إغلاق</button></div><label className="block mt-4"><span className="text-xs font-semibold">نوع الطلب</span><select className="input w-full mt-1" value={requestType} onChange={e=>setRequestType(e.target.value as RequestType)}><option value="permission">استئذان</option><option value="leave">إجازة</option><option value="checkout">انصراف مبكر</option></select></label><label className="block mt-4"><span className="text-xs font-semibold">السبب</span><textarea className="input w-full mt-1 min-h-28" value={reason} onChange={e=>setReason(e.target.value)} required/></label><button className="btn-primary w-full mt-4" type="submit">{requestSent?"تم إرسال الطلب":"إرسال الطلب"}</button></form></div>}
 </div>;
}
function Centered({children}:{children:React.ReactNode}){return <div className="min-h-screen grid place-items-center px-5"><div className="hud-card w-full max-w-md p-7 text-center">{children}</div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="text-center rounded-2xl bg-secondary/40 border border-border/40 p-3"><div className="text-[10px] text-muted-foreground">{label}</div><div className="mono font-black mt-1 text-sm">{value}</div></div>}
function Row({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-secondary/30 border border-border/30 p-3"><div className="text-[10px] text-muted-foreground">{label}</div><div className="font-semibold mt-0.5 truncate">{value}</div></div>}
