import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Brand from "@/components/Brand";
import { currentSession, logoutEmployee } from "@/lib/auth";
import { getSettings, type RequestType } from "@/lib/storage";
import { backendEnabled, getBackendAttendance, getBackendEmployeeProfile, getBackendLocations, createBackendRequest } from "@/lib/backend";
import { getActiveWorkPeriod, getEmployeeScheduleStatus } from "@/lib/schedule";
import { formatDurationMinutes, formatTime, minutesBetween } from "@/lib/utils";
import type { AttendanceRecord, Employee, Location } from "@/types";

const PROFILE_TIMEOUT_MS=12000;

export default function EmployeeHome(){
 const nav=useNavigate(); const session=currentSession(); const sessionKey=session?`${session.employeeId}|${session.jobNumber}|${session.loginAt}|${session.role??""}`:null;
 const [now,setNow]=useState(new Date()); const [emp,setEmp]=useState<Employee|null>(null); const [locations,setLocations]=useState<Location[]>([]); const [attendance,setAttendance]=useState<AttendanceRecord[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [showRequest,setShowRequest]=useState(false); const [requestType,setRequestType]=useState<RequestType>("permission"); const [reason,setReason]=useState(""); const [requestSent,setRequestSent]=useState(false); const loadingRef=useRef(false);
 useEffect(()=>{const t=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(t);},[]);
 useEffect(()=>{if(!sessionKey){nav("/login",{replace:true});return;}let cancelled=false;const load=async()=>{if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setError(null);try{if(!backendEnabled)throw new Error("خادم D1 غير مفعّل. يرجى المحاولة لاحقاً.");const timeout=new Promise<never>((_,reject)=>window.setTimeout(()=>reject(new Error("انتهت مهلة الاتصال بقاعدة البيانات.")),PROFILE_TIMEOUT_MS));const profile=await Promise.race([getBackendEmployeeProfile(),timeout]);if(cancelled)return;if(!profile?.id)throw new Error("لم يتم العثور على ملف الموظف المرتبط بحسابك في D1.");setEmp(profile);const [a,l]=await Promise.allSettled([getBackendAttendance(500),getBackendLocations()]);if(cancelled)return;if(a.status==="fulfilled"&&Array.isArray(a.value))setAttendance(a.value);if(l.status==="fulfilled"&&Array.isArray(l.value))setLocations(l.value);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"تعذر تحميل بيانات الموظف من D1.");}finally{if(!cancelled)setLoading(false);loadingRef.current=false;}};void load();const refresh=()=>void load();window.addEventListener("hadir:cloud-data-changed",refresh);window.addEventListener("hadir:d1-view-changed",refresh);return()=>{cancelled=true;window.removeEventListener("hadir:cloud-data-changed",refresh);window.removeEventListener("hadir:d1-view-changed",refresh);};},[sessionKey,nav]);
 const settings=getSettings(); const schedule=useMemo(()=>getEmployeeScheduleStatus(emp,now),[emp,now]); const period=useMemo(()=>getActiveWorkPeriod(emp,now),[emp,now]);
 const sessionPair=useMemo(()=>{if(!emp)return{checkIn:undefined,checkOut:undefined};const rows=attendance.filter(r=>r.employeeId===emp.id).sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime());let checkIn:AttendanceRecord|undefined;let checkOut:AttendanceRecord|undefined;for(const row of rows){if(row.type==="check-in"){checkIn=row;checkOut=undefined;}else if(row.type==="check-out"&&checkIn){checkOut=row;break;}}return{checkIn,checkOut};},[attendance,emp]);
 const checkIn=sessionPair.checkIn; const checkOut=sessionPair.checkOut; const workedMinutes=checkIn?minutesBetween(checkIn.timestamp,checkOut?.timestamp??now.toISOString()):0; const canCheckIn=Boolean(emp&&schedule.isWorkDay&&!checkIn); const canCheckOut=Boolean(emp&&checkIn&&!checkOut); const locationName=emp?.locationId?(locations.find(l=>l.id===emp.locationId)?.name||"الموقع المخصص"):"المقر الرئيسي";
 let late=0; if(checkIn&&period.start){late=Math.max(0,Math.round((new Date(checkIn.timestamp).getTime()-period.start.getTime())/60000)-(emp?.gracePeriodMinutes??settings.lateGraceMinutes??10));}
 const expectedEnd=period.end; const endText=expectedEnd?formatTime(expectedEnd):"—";
 const logout=()=>{logoutEmployee();nav("/login");};
 const sendRequest=async(e:React.FormEvent)=>{e.preventDefault();if(!emp)return;try{await createBackendRequest({employeeId:emp.id,employeeName:emp.name,jobNumber:emp.jobNumber,type:requestType,reason});setRequestSent(true);window.setTimeout(()=>{setRequestSent(false);setShowRequest(false);setReason("");},1800);}catch(err){setError(err instanceof Error?err.message:"تعذر إرسال الطلب إلى D1.");}};
 if(!sessionKey)return null;
 if(loading)return <Centered><Brand/><div className="mt-5 font-bold">جاري تحميل بيانات الموظف من D1...</div><div className="text-xs text-muted-foreground mt-2">يتم جلب الجدول والحضور من قاعدة البيانات.</div></Centered>;
 if(error||!emp)return <Centered><Brand/><div className="mt-5 font-bold">تعذر تحميل بيانات الموظف</div><div className="text-sm text-muted-foreground mt-2">{error||"لم يتم العثور على ملف الموظف في D1."}</div><button className="btn-primary mt-5 w-full" onClick={()=>window.location.reload()}>إعادة المحاولة</button></Centered>;
 return <div className="min-h-screen"><header className="max-w-xl mx-auto px-4 sm:px-5 py-4 flex items-center justify-between"><Brand/><button onClick={logout} className="btn-ghost text-xs">خروج</button></header><main className="max-w-xl mx-auto px-4 sm:px-5 pb-16 space-y-4">
  <section className="hud-card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3 min-w-0"><div className="h-14 w-14 rounded-full bg-primary/15 grid place-items-center border-2 border-primary/30 shrink-0">{emp.avatar?<img src={emp.avatar} alt={emp.name} className="h-full w-full rounded-full object-cover"/>:<span className="text-primary font-extrabold text-xl">{emp.name.charAt(0)||"م"}</span>}</div><div className="min-w-0"><div className="text-[10px] text-muted-foreground mono">EMPLOYEE</div><div className="font-extrabold text-lg truncate">{emp.name}</div><div className="text-xs text-muted-foreground mono">{emp.jobNumber} · {locationName}</div></div></div><div className="text-left"><div className="mono text-2xl font-extrabold tabular-nums">{now.toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit",hour12:false})}</div><div className="text-[10px] text-muted-foreground">{now.toLocaleDateString("ar-EG",{weekday:"long",day:"2-digit",month:"2-digit"})}</div></div></div>
   <div className="mt-4 grid grid-cols-3 gap-2"><Stat label="الحضور" value={checkIn?formatTime(checkIn.timestamp):"—"}/><Stat label="الانصراف" value={checkOut?formatTime(checkOut.timestamp):"—"}/><Stat label="ساعات العمل" value={formatDurationMinutes(workedMinutes)}/></div>
   <div className={`mt-4 rounded-xl border p-3 text-xs font-semibold ${schedule.isWorkDay?"border-primary/30 bg-primary/10 text-primary":"border-accent/40 bg-accent/10 text-accent"}`}>{schedule.label}{schedule.detail?` · ${schedule.detail}`:""}{schedule.isWorkDay&&period.end&&<div className="mt-1 text-muted-foreground">نهاية الفترة المتوقعة: {endText}</div>}</div>
   {late>0&&<div className="mt-3 rounded-xl border border-[hsl(var(--warning))]/40 bg-[hsl(var(--warning))]/10 p-3 text-xs text-[hsl(var(--warning))]">تم رصد تأخر {late} دقيقة عن بداية الفترة.</div>}
  </section>
  <section className="grid grid-cols-2 gap-3"><Link to="/employee/scan/check-in" aria-disabled={!canCheckIn} className={`hud-card p-5 text-center ${!canCheckIn?"opacity-40 pointer-events-none":"hover:brightness-110"}`}><div className="text-2xl mb-2">↘</div><div className="font-extrabold">تسجيل حضور</div><div className="text-xs text-muted-foreground mt-1">{!schedule.isWorkDay?"أنت في يوم راحة":checkIn?"تم تسجيل الحضور":"امسح QR داخل المقر"}</div></Link><Link to="/employee/scan/check-out" aria-disabled={!canCheckOut} className={`hud-card p-5 text-center ${!canCheckOut?"opacity-40 pointer-events-none":"hover:brightness-110"}`}><div className="text-2xl mb-2">↗</div><div className="font-extrabold">تسجيل انصراف</div><div className="text-xs text-muted-foreground mt-1">{checkOut?"تم تسجيل الانصراف":checkIn?"يمكنك تسجيل الانصراف الآن":"سجل الحضور أولاً"}</div></Link></section>
  <section className="hud-card p-5"><div className="flex items-center justify-between mb-3"><div className="font-bold">حالة الدوام</div><span className={`badge ${schedule.isWorkDay?"bg-primary/15 text-primary":"bg-accent/15 text-accent"}`}>{schedule.isWorkDay?"يوم عمل":"راحة"}</span></div><div className="grid grid-cols-2 gap-2 text-xs"><Row label="نوع الدوام" value={emp.scheduleType==="ROTATION"?"تناوبي":"إداري"}/><Row label="الحالة" value={schedule.label}/><Row label="الجهاز" value={emp.deviceLabel||"غير مرتبط"}/><Row label="الموقع" value={locationName}/></div></section>
  <button onClick={()=>setShowRequest(true)} className="hud-card w-full p-4 text-center border-dashed hover:brightness-110"><div className="font-extrabold text-accent">طلب استئذان / إجازة</div><div className="text-xs text-muted-foreground mt-1">إرسال طلب للمدير عبر D1</div></button>
 </main>
 {showRequest&&<div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm grid place-items-center p-4"><form onSubmit={sendRequest} className="hud-card w-full max-w-md p-5"><div className="flex items-center justify-between"><h2 className="font-extrabold">طلب جديد</h2><button type="button" className="btn-ghost" onClick={()=>setShowRequest(false)}>إغلاق</button></div><label className="block mt-4"><span className="text-xs font-semibold">نوع الطلب</span><select className="input w-full mt-1" value={requestType} onChange={e=>setRequestType(e.target.value as RequestType)}><option value="permission">استئذان</option><option value="leave">إجازة</option><option value="checkout">انصراف مبكر</option></select></label><label className="block mt-4"><span className="text-xs font-semibold">السبب</span><textarea className="input w-full mt-1 min-h-28" value={reason} onChange={e=>setReason(e.target.value)} required/></label><button className="btn-primary w-full mt-4" type="submit">{requestSent?"تم إرسال الطلب":"إرسال الطلب"}</button></form></div>}
 </div>;
}
function Centered({children}:{children:React.ReactNode}){return <div className="min-h-screen grid place-items-center px-5"><div className="hud-card w-full max-w-md p-7 text-center">{children}</div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="text-center rounded-xl bg-secondary/40 p-2"><div className="text-[10px] text-muted-foreground">{label}</div><div className="mono font-bold mt-1 text-sm">{value}</div></div>}
function Row({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-secondary/30 p-2"><div className="text-[10px] text-muted-foreground">{label}</div><div className="font-semibold mt-0.5 truncate">{value}</div></div>}
