import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { currentSession } from "@/lib/auth";
import { getBackendEmployeeProfile } from "@/lib/backend";
import { compressProfileImageDataUrl } from "@/lib/imageCompression";
import EmployeeDigitalCard from "@/components/employee/EmployeeDigitalCard";

const API_URL = String(import.meta.env.VITE_API_URL || "https://hadir-api.abunizar963.workers.dev").replace(/\/$/, "");
const deviceId = () => localStorage.getItem("hadir.device.id") || "";
function fileToDataUrl(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("تعذر قراءة الصورة.")); reader.onerror = () => reject(new Error("تعذر قراءة الصورة من الجهاز.")); reader.readAsDataURL(file); }); }
async function blobToDataUrl(blob: Blob): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("تعذر تجهيز صورة الملف الشخصي.")); reader.onerror = () => reject(new Error("تعذر قراءة صورة الملف الشخصي.")); reader.readAsDataURL(blob); }); }
async function saveProfile(body: Record<string, unknown>) {
  const token = localStorage.getItem("hadir.api.token.employee") || "";
  if (!token) throw new Error("جلسة الموظف غير موجودة. يرجى تسجيل الدخول مرة أخرى.");
  if (typeof body.avatar === "string") {
    const profile = await getBackendEmployeeProfile();
    const blob = (() => { const comma = body.avatar.indexOf(","); if (comma < 0) throw new Error("صيغة الصورة المضغوطة غير صالحة."); const header = body.avatar.slice(0, comma); const base64 = body.avatar.slice(comma + 1); const mime = /^data:([^;]+);base64$/i.exec(header)?.[1] || "image/webp"; const binary = atob(base64); const bytes = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i); return new Blob([bytes], { type: mime }); })();
    if (blob.type !== "image/webp" || blob.size <= 0 || blob.size > 100 * 1024) throw new Error("صورة الموظف يجب أن تكون WebP وأقل من 100 كيلوبايت.");
    const form = new FormData(); form.append("file", blob, "avatar.webp");
    const response = await fetch(`${API_URL}/api/employees/${encodeURIComponent(profile.id)}/avatar`, { method: "POST", headers: { authorization: `Bearer ${token}`, "x-device-id": deviceId() }, body: form, cache: "no-store", credentials: "include" });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : `تعذر حفظ الصورة الشخصية (${response.status})`);
    return data as { ok?: boolean; key?: string; employee?: { avatar?: string | null } };
  }
  const response = await fetch(`${API_URL}/api/workforce/live`, { method: "PATCH", headers: { "content-type": "application/json", authorization: `Bearer ${token}`, "x-device-id": deviceId() }, body: JSON.stringify(body), cache: "no-store", credentials: "include" });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "تعذر حفظ الملف الشخصي"); return data as { ok?: boolean; employee?: { avatar?: string | null } };
}

export default function EmployeeProfile() {
  const navigate = useNavigate(); const session = currentSession(); const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [name, setName] = useState(session?.name || ""); const [jobNumber, setJobNumber] = useState(session?.jobNumber || ""); const [avatar, setAvatar] = useState<string | null>(null); const [newPassword, setNewPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [showPassword, setShowPassword] = useState(false); const [saving, setSaving] = useState(false); const [photoSaving, setPhotoSaving] = useState(false); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [lastSync, setLastSync] = useState(""); const [copied, setCopied] = useState(false);
  const loadProfile = async () => { setLoading(true); try { const profile = await getBackendEmployeeProfile(); setName(profile.name); setJobNumber(profile.jobNumber || session?.jobNumber || ""); if (typeof profile.avatar === "string" && profile.avatar.startsWith("data:image/")) setAvatar(profile.avatar); else if (profile.id) { const token = localStorage.getItem("hadir.api.token.employee") || ""; const response = await fetch(`${API_URL}/api/employees/${encodeURIComponent(profile.id)}/avatar`, { headers: { authorization: `Bearer ${token}` }, credentials: "include", cache: "no-store" }); if (response.ok) setAvatar(await blobToDataUrl(await response.blob())); else setAvatar(null); } else setAvatar(null); setLastSync(new Date().toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })); } catch { setName(session?.name || ""); setJobNumber(session?.jobNumber || ""); } finally { setLoading(false); } };
  useEffect(() => { void loadProfile(); }, []);
  const openPhotoPicker = () => { setError(""); setMessage(""); const input = fileInputRef.current; if (!input) return; try { if (typeof input.showPicker === "function") input.showPicker(); else input.click(); } catch { input.click(); } };
  const photo = async (event: ChangeEvent<HTMLInputElement>) => { const input = event.currentTarget; const file = input.files?.[0]; input.value = ""; if (!file) return; if (!file.type.startsWith("image/")) { setError("اختر صورة فقط من ألبوم الصور."); return; } setPhotoSaving(true); setError(""); setMessage(""); try { const original = await fileToDataUrl(file); const compressed = await compressProfileImageDataUrl(original, { maxWidth: 512, maxHeight: 512, quality: 0.78, minQuality: 0.45, type: "image/webp", maxBytes: 100 * 1024 }); await saveProfile({ avatar: compressed }); setAvatar(compressed); window.dispatchEvent(new Event("hadir:cloud-data-changed")); window.dispatchEvent(new Event("hadir:d1-view-changed")); setMessage("تم حفظ الصورة الشخصية في خادم R2 بنجاح، وستظهر مباشرة في واجهة الحضور."); } catch (err) { setError(err instanceof Error ? err.message : "تعذر حفظ الصورة الشخصية."); } finally { setPhotoSaving(false); } };
  const password = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); if (newPassword.length < 4) return setError("كلمة السر يجب أن تتكون من 4 أحرف/أرقام على الأقل."); if (newPassword !== confirm) return setError("تأكيد كلمة السر غير مطابق."); setSaving(true); try { await saveProfile({ password: newPassword }); setNewPassword(""); setConfirm(""); setShowPassword(false); setMessage("تم تغيير كلمة السر بنجاح"); } catch (err) { setError(err instanceof Error ? err.message : "تعذر تغيير كلمة السر"); } finally { setSaving(false); } };
  const copyJobNumber = async () => { if (!jobNumber) return; try { await navigator.clipboard.writeText(jobNumber); setCopied(true); window.setTimeout(() => setCopied(false), 1500); } catch { setError("تعذر نسخ الرقم الوظيفي."); } };
  const refresh = async () => { setError(""); setMessage(""); await loadProfile(); setMessage("تم تحديث بيانات الملف الشخصي."); };

  return <main dir="rtl" className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-xl space-y-4">
    <div className="flex items-center justify-between gap-2"><button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2 text-sm font-bold"><span aria-hidden="true">→</span> العودة</button><button type="button" onClick={() => void refresh()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2 text-sm font-bold hover:bg-secondary disabled:opacity-50"><span aria-hidden="true">↻</span> تحديث البيانات</button></div>
    <section className="hud-card overflow-hidden p-6"><div className="flex items-center gap-4"><div className="relative"><div className="grid h-24 w-24 place-items-center overflow-hidden rounded-3xl border-2 border-primary/30 bg-primary/10 text-3xl font-black text-primary">{avatar ? <img src={avatar} alt={name} className="h-full w-full object-cover" /> : name.charAt(0) || "م"}</div><button type="button" onClick={openPhotoPicker} disabled={photoSaving} aria-label="تغيير الصورة الشخصية" title="تغيير الصورة الشخصية" className="absolute -bottom-2 -left-2 grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground shadow-lg transition hover:scale-105 disabled:cursor-wait disabled:opacity-60">{photoSaving ? <span className="text-xs font-black">…</span> : <span aria-hidden="true">▣</span>}</button><input ref={fileInputRef} type="file" accept="image/*,.heic,.heif" onChange={photo} className="absolute h-px w-px overflow-hidden opacity-0" tabIndex={-1} aria-label="اختيار صورة من ألبوم الصور" /></div><div className="min-w-0"><div className="text-xs text-muted-foreground">الملف الشخصي</div><h1 className="text-2xl font-black truncate">{name}</h1><p className="mt-1 text-xs text-muted-foreground">إدارة الصورة الشخصية وأمان الحساب ومعلومات الموظف.</p><div className="mt-3 inline-flex items-center gap-2 rounded-lg bg-secondary/50 px-2.5 py-1.5 text-xs font-bold"><span aria-hidden="true">♙</span> موظف</div></div></div></section>
    <EmployeeDigitalCard name={name} jobNumber={jobNumber} avatar={avatar} />
    <section className="hud-card p-5"><div className="flex items-center justify-between mb-4"><div><div className="text-xs text-muted-foreground">معلومات الحساب</div><div className="font-black mt-0.5">بيانات الموظف</div></div><span className="grid h-9 w-9 place-items-center rounded-lg bg-background/50 border border-border/50" aria-hidden="true">▥</span></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl border border-border/50 bg-secondary/25 p-3"><div className="text-[10px] text-muted-foreground">الاسم</div><div className="font-bold mt-1 truncate">{name || "—"}</div></div><button type="button" onClick={() => void copyJobNumber()} className="rounded-xl border border-border/50 bg-secondary/25 p-3 text-right hover:bg-secondary/50"><div className="text-[10px] text-muted-foreground">الرقم الوظيفي</div><div className="font-bold mt-1 truncate">{copied ? "تم النسخ ✓" : jobNumber || "—"}</div></button><div className="rounded-xl border border-border/50 bg-secondary/25 p-3"><div className="text-[10px] text-muted-foreground">حالة الحساب</div><div className="font-bold mt-1 text-primary">● نشط</div></div><div className="rounded-xl border border-border/50 bg-secondary/25 p-3"><div className="text-[10px] text-muted-foreground">آخر مزامنة</div><div className="font-bold mt-1">{lastSync || "جاري التحميل…"}</div></div></div></section>
    <section className="hud-card p-6"><div className="flex items-center gap-3 font-black"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary" aria-hidden="true">⚿</span><span>أمان الحساب</span></div><form onSubmit={password} className="mt-5 space-y-4"><div className="relative"><input className="input w-full pl-12" type={showPassword ? "text" : "password"} autoComplete="new-password" placeholder="كلمة السر الجديدة" value={newPassword} onChange={e => setNewPassword(e.target.value)} /><button type="button" onClick={() => setShowPassword(v => !v)} className="absolute left-2 top-1/2 -translate-y-1/2 rounded-lg px-2 py-1 text-xs text-muted-foreground hover:bg-secondary" aria-label={showPassword ? "إخفاء كلمة السر" : "إظهار كلمة السر"}>{showPassword ? "إخفاء" : "إظهار"}</button></div><input className="input w-full" type={showPassword ? "text" : "password"} autoComplete="new-password" placeholder="تأكيد كلمة السر" value={confirm} onChange={e => setConfirm(e.target.value)} /><button className="btn-primary w-full" disabled={saving}>{saving ? "جاري الحفظ…" : "حفظ كلمة السر"}</button></form><div className="mt-4 flex items-start gap-2 rounded-xl border border-primary/20 bg-primary/5 p-3 text-xs text-muted-foreground"><span aria-hidden="true">✓</span><span>تُحفظ كلمة السر في الخادم باستخدام PBKDF2 ولا يتم تخزينها كنص مكشوف.</span></div>{message && <div className="mt-3 rounded-xl border border-primary/30 bg-primary/10 p-3 text-sm text-primary">{message}</div>}{error && <div className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}</section>
  </div></main>;
}
