import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Brand from "@/components/Brand";
import { loginEmployee } from "@/lib/auth";
import { backendEnabled, backendEmployeeLogin } from "@/lib/backend";
import { hydrateLocalData } from "@/lib/cloudDataSync";
import { setSession } from "@/lib/storage";
import type { Employee } from "@/types";
export default function EmployeeLogin(){const navigate=useNavigate();const[jobNumber,setJobNumber]=useState("");const[pin,setPin]=useState("");const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(false);const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(loading)return;setError(null);setLoading(true);try{if(backendEnabled){const employee=await backendEmployeeLogin(jobNumber,pin),e=employee as Employee;setSession({employeeId:e.id,jobNumber:e.jobNumber,name:e.name,loginAt:new Date().toISOString(),role:e.role});try{await hydrateLocalData()}catch{}navigate("/employee",{replace:true});return}const result=loginEmployee(jobNumber,pin);if(!result.success){setError(result.reason||"الرقم الوظيفي أو رمز الدخول غير صحيح");return}navigate("/employee",{replace:true})}catch(e){setError(e instanceof Error?e.message:"تعذر الاتصال بالخادم")}finally{setLoading(false)}};return <div className="min-h-screen flex flex-col"><header className="p-5"><Brand /></header><main className="flex-1 grid place-items-center px-5 pb-10"><div className="w-full max-w-md hud-card p-7"><div className="text-xs mono text-muted-foreground">EMPLOYEE · حاضِر</div><h1 className="text-2xl font-extrabold mt-1">دخول الموظفين</h1><p className="text-sm text-muted-foreground mt-1">أدخل الرقم الوظيفي ورمز الدخول الخاص بك.</p><form onSubmit={submit} className="mt-6 space-y-4"><div><label className="block text-sm font-semibold mb-1.5" htmlFor="jobNumber">الرقم الوظيفي</label><input id="jobNumber" type="text" inputMode="numeric" autoComplete="username" className="input w-full" value={jobNumber} onChange={e=>setJobNumber(e.target.value)} placeholder="مثال: 1001" required /></div><div><label className="block text-sm font-semibold mb-1.5" htmlFor="pin">رمز الدخول</label><input id="pin" type="password" inputMode="numeric" autoComplete="current-password" className="input w-full" value={pin} onChange={e=>setPin(e.target.value)} placeholder="أدخل رمز الدخول" required /></div>{error&&<div className="rounded-xl border border-destructive/40 bg-destructive/10 text-destructive-foreground p-3 text-sm" role="alert">{error}</div>}<button type="submit" className="btn-primary w-full py-3" disabled={loading}>{loading?"جاري التحقق...":"دخول الموظف"}</button></form><div className="mt-5 text-xs text-center flex justify-between items-center gap-4"><Link to="/" className="text-muted-foreground hover:text-foreground">← العودة للرئيسية</Link><Link to="/manager/login" className="text-primary hover:underline">دخول الإدارة</Link></div></div></main></div>}
