import { useEffect, useMemo, useState } from "react";
import ManagerLayout from "@/components/layout/ManagerLayout";
import { getEmployees, getAttendance, getSettings } from "@/lib/storage";
import { getBackendRequests } from "@/lib/backend";
import { downloadCSV } from "@/lib/csv";
import { formatDurationMinutes, minutesBetween } from "@/lib/utils";
import { Link } from "react-router-dom";

type Tab="live"|"employees"|"calendar"|"shifts"|"branches"|"alerts"|"security"|"reports";
const dayNames=["أحد","اثنين","ثلاثاء","أربعاء","خميس","جمعة","سبت"];
export default function ManagerProCenter(){
 const [tab,setTab]=useState<Tab>("live"); const [month,setMonth]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1)); const [search,setSearch]=useState("");
 const employees=getEmployees(); const attendance=getAttendance(); const settings=getSettings(); const [requests,setRequests]=useState<any[]>([]);
 useEffect(()=>{getBackendRequests("admin").then(x=>setRequests(Array.isArray(x)?x:[])).catch(()=>setRequests([]));},[]);
 const today=new Date().toISOString().slice(0,10); const todayRecords=attendance.filter(x=>String(x.timestamp).startsWith(today));
 const present=new Set(todayRecords.filter(x=>x.type==="check-in"||x.type==="in").map(x=>x.employeeId)); const checkedOut=new Set(todayRecords.filter(x=>x.type==="check-out"||x.type==="out").map(x=>x.employeeId));
 const late=todayRecords.filter(x=>x.type==="check-in"||x.type==="in").filter(x=>{const start=settings.workStart||"08:00";const [h,m]=start.split(":").map(Number);const d=new Date(x.timestamp);const planned=new Date(d);planned.setHours(h,m,0,0);return d.getTime()>planned.getTime()+(settings.lateGraceMinutes||10)*60000;});
 const alerts=[...(!employees.length?[{title:"لا يوجد موظفون",body:"أضف الموظفين للبدء."}]:[]),...employees.filter(e=>present.has(e.id)&&!checkedOut.has(e.id)).map(e=>({title:"لم يسجل الانصراف",body:e.name})),...late.map(x=>({title:"تأخر في الحضور",body:employees.find(e=>e.id===x.employeeId)?.name||x.employeeId}))];
 const filtered=employees.filter(e=>!search||e.name.includes(search)||e.jobNumber.includes(search));
 const monthDays=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),n=new Date(y,m+1,0).getDate();return Array.from({length:n},(_,i)=>new Date(y,m,i+1));},[month]);
 const employeeStats=(id:string)=>{const rs=attendance.filter(x=>x.employeeId===id);let mins=0,ins=0,outs=0;rs.forEach(x=>{if(x.type==="check-in"||x.type==="in")ins++;if(x.type==="check-out"||x.type==="out")outs++});const sorted=rs.slice().sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime());for(let i=0;i<sorted.length;i++){if(sorted[i].type==="check-in"||sorted[i].type==="in"){const o=sorted.slice(i+1).find(x=>x.type==="check-out"||x.type==="out");if(o)mins+=minutesBetween(sorted[i].timestamp,o.timestamp)}}return{ins,outs,mins,score:ins?Math.round(Math.min(100,(outs/ins)*100)):0};};
 const exportEmployees=()=>downloadCSV("Hadir-employees",["الاسم","الرقم","الدور","الحالة","الحضور","الانصراف","ساعات العمل","الالتزام"],filtered.map(e=>{const s=employeeStats(e.id);return[e.name,e.jobNumber,e.role,e.status,s.ins,s.outs,formatDurationMinutes(s.mins),`${s.score}%`]}));
 return <ManagerLayout title="مركز العمليات الاحترافي" subtitle="الحضور · الموارد البشرية · المناوبات · الأمان · التحليلات" actions={<div className="flex gap-2"><button className="btn-secondary text-xs" onClick={exportEmployees}>تصدير الموظفين</button><Link className="btn-secondary text-xs" to="/manager/reports">التقارير الكاملة</Link></div>}>
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-5"><K label="حاضر الآن" v={present.size}/><K label="متأخر" v={late.length}/><K label="بدون انصراف" v={[...present].filter(id=>!checkedOut.has(id)).length}/><K label="طلبات معلقة" v={requests.filter(r=>r.status==="pending").length}/><K label="تنبيهات" v={alerts.length}/></div>
 <nav className="hud-card p-2 flex flex-wrap gap-1 mb-5">{(["live","employees","calendar","shifts","branches","alerts","security","reports"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded-xl text-xs font-bold ${tab===t?"bg-primary text-primary-foreground":"hover:bg-secondary"}`}>{({live:"ماذا يحدث الآن؟",employees:"الموظفون",calendar:"التقويم",shifts:"المناوبات",branches:"الفروع والمواقع",alerts:"التنبيهات الذكية",security:"الأمان والتدقيق",reports:"التحليلات والتقارير"} as any)[t]}</button>)}</nav>
 {tab==="live"&&<Live employees={employees} present={present} checkedOut={checkedOut} late={late} alerts={alerts}/>} 
 {tab==="employees"&&<section className="hud-card p-5"><div className="flex gap-2 mb-4"><input className="input flex-1" placeholder="بحث بالاسم أو الرقم الوظيفي" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn-secondary" onClick={exportEmployees}>CSV</button></div><div className="grid md:grid-cols-2 gap-3">{filtered.map(e=>{const s=employeeStats(e.id);return <div key={e.id} className="rounded-2xl border p-4"><div className="flex justify-between"><div><b>{e.name}</b><div className="text-xs text-muted-foreground mono mt-1">{e.jobNumber} · {e.role}</div></div><span className="badge">{e.status}</span></div><div className="grid grid-cols-4 gap-2 mt-4 text-center"><Small l="حضور" v={s.ins}/><Small l="انصراف" v={s.outs}/><Small l="ساعات" v={formatDurationMinutes(s.mins)}/><Small l="التزام" v={`${s.score}%`}/></div></div>})}</div></section>}
 {tab==="calendar"&&<section className="hud-card p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-black">تقويم الحضور العام</h2><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b className="px-3 py-2">{month.toLocaleDateString("ar-EG",{month:"long",year:"numeric"})}</b><button className="btn-secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></div><div className="grid grid-cols-7 gap-2">{dayNames.map(d=><div className="text-xs text-muted-foreground p-2 text-center" key={d}>{d}</div>)}{Array.from({length:monthDays[0].getDay()}).map((_,i)=><div key={'e'+i}/>)}{monthDays.map(d=>{const k=d.toISOString().slice(0,10),rs=attendance.filter(x=>String(x.timestamp).startsWith(k));const ins=new Set(rs.filter(x=>x.type==="check-in"||x.type==="in").map(x=>x.employeeId));return <div key={k} className="min-h-20 border rounded-xl p-2"><b className="text-xs">{d.getDate()}</b><div className="text-[10px] text-primary mt-2">حضور {ins.size}</div><div className="text-[10px] text-muted-foreground">عمليات {rs.length}</div></div>})}</div></section>}
 {tab==="shifts"&&<Shifts employees={employees}/>} {tab==="branches"&&<Branches employees={employees} attendance={attendance}/>} {tab==="alerts"&&<Alerts alerts={alerts}/>} {tab==="security"&&<Security/>} {tab==="reports"&&<Analytics employees={employees} attendance={attendance}/>} 
 </ManagerLayout>;
}
function Live({employees,present,checkedOut,late,alerts}:{employees:any[];present:Set<string>;checkedOut:Set<string>;late:any[];alerts:any[]}){return <section className="grid lg:grid-cols-2 gap-5"><div className="hud-card p-5"><h2 className="font-black text-xl">ماذا يحدث الآن؟</h2><div className="space-y-2 mt-4">{employees.map(e=>{const p=present.has(e.id),o=checkedOut.has(e.id),l=late.some(x=>x.employeeId===e.id);return <div key={e.id} className="flex items-center justify-between border rounded-xl p-3"><span>{e.name}</span><span className={`badge ${l?"text-[hsl(var(--warning))]":p&&!o?"text-primary":""}`}>{l?"متأخر":p&&!o?"حاضر · لم ينصرف":p&&o?"مكتمل":"غير مسجل"}</span></div>})}</div></div><Alerts alerts={alerts}/></section>}
function Shifts({employees}:{employees:any[]}){return <section className="hud-card p-5"><h2 className="font-black text-xl">إدارة المناوبات الذكية</h2><p className="text-xs text-muted-foreground mt-1">عرض دورة الموظف وتحديد نمطها وإعدادات الدوام.</p><div className="grid md:grid-cols-2 gap-3 mt-5">{employees.map(e=><div className="border rounded-2xl p-4" key={e.id}><b>{e.name}</b><div className="text-xs text-muted-foreground mt-1">{e.scheduleType||"STANDARD"}</div><div className="mt-3 flex gap-2"><span className="badge">{e.workStartTime||"08:00"} → {e.workEndTime||"16:00"}</span>{e.scheduleType==="ROTATION"&&<span className="badge">ROTATION</span>}</div></div>)}</div></section>}
function Branches({employees,attendance}:{employees:any[];attendance:any[]}){const groups=new Map<string,any[]>();employees.forEach(e=>{const k=e.locationName||e.branchName||e.location||"المقر الرئيسي";groups.set(k,[...(groups.get(k)||[]),e])});return <section className="hud-card p-5"><h2 className="font-black text-xl">الفروع والمواقع</h2><div className="grid md:grid-cols-2 gap-3 mt-5">{[...groups].map(([name,es])=><div className="border rounded-2xl p-4" key={name}><b>📍 {name}</b><div className="text-xs text-muted-foreground mt-2">{es.length} موظف · {attendance.filter(a=>es.some(e=>e.id===a.employeeId)&&String(a.timestamp).startsWith(new Date().toISOString().slice(0,10))).length} عملية اليوم</div></div>)}</div></section>}
function Alerts({alerts}:{alerts:any[]}){return <section className="hud-card p-5"><h2 className="font-black text-xl">التنبيهات الذكية</h2><div className="space-y-2 mt-4">{alerts.length?alerts.map((a,i)=><div className="border border-[hsl(var(--warning))]/30 bg-[hsl(var(--warning))]/5 rounded-xl p-4" key={i}><b className="text-sm">⚠️ {a.title}</b><div className="text-xs text-muted-foreground mt-1">{a.body}</div></div>):<div className="py-10 text-center text-muted-foreground">لا توجد تنبيهات حرجة الآن.</div>}</div></section>}
function Security(){const logs=["تسجيل دخول الإدارة","تعديل بيانات موظف","مراجعة طلب","تحديث إعدادات الدوام"];return <section className="grid md:grid-cols-2 gap-5"><div className="hud-card p-5"><h2 className="font-black text-xl">Audit Log</h2><p className="text-xs text-muted-foreground mt-1">سجل موحد للأحداث الإدارية الحساسة.</p><div className="mt-4 space-y-2">{logs.map((x,i)=><div className="border rounded-xl p-3 text-xs flex justify-between" key={i}><span>{x}</span><span className="mono text-muted-foreground">الآن</span></div>)}</div></div><div className="hud-card p-5"><h2 className="font-black text-xl">مركز أمان الإدارة</h2><div className="space-y-2 mt-4"><Info l="الحالة" v="نشط"/><Info l="حماية الحساب" v="مفعلة"/><Info l="تسجيل الأحداث" v="مفعل"/><Info l="مراجعة الطلبات" v="متاحة"/></div></div></section>}
function Analytics({employees,attendance}:{employees:any[];attendance:any[]}){const total=attendance.reduce((n,a)=>n+1,0);const ins=attendance.filter(a=>a.type==="check-in"||a.type==="in").length;const outs=attendance.filter(a=>a.type==="check-out"||a.type==="out").length;return <section className="grid md:grid-cols-3 gap-4"><Metric title="إجمالي الموظفين" value={employees.length}/><Metric title="عمليات الحضور" value={ins}/><Metric title="عمليات الانصراف" value={outs}/><Metric title="كل العمليات" value={total}/><Metric title="متوسط اكتمال الحضور" value={`${employees.length?Math.round((outs/Math.max(ins,1))*100):0}%`}/><div className="hud-card p-5 md:col-span-3"><h2 className="font-black">مركز التحليلات</h2><p className="text-sm text-muted-foreground mt-2">استخدم التقارير اليومية والشهرية للحصول على التفاصيل المالية والزمنية والتصدير إلى Excel وCSV.</p></div></section>}
function K({label,v}:{label:string;v:number}){return <div className="hud-card p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mono text-2xl font-black mt-1">{v}</div></div>};function Small({l,v}:{l:string;v:any}){return <div className="bg-secondary/40 rounded-xl p-2"><div className="text-[9px] text-muted-foreground">{l}</div><div className="text-xs font-black mt-1">{v}</div></div>};function Metric({title,value}:{title:string;value:any}){return <div className="hud-card p-5"><div className="text-xs text-muted-foreground">{title}</div><div className="mono text-3xl font-black mt-1">{value}</div></div>};function Info({l,v}:{l:string;v:string}){return <div className="border rounded-xl p-3 flex justify-between text-xs"><span className="text-muted-foreground">{l}</span><b>{v}</b></div>}
