import { useEffect, useMemo, useState } from "react";
import ManagerLayout from "@/components/layout/ManagerLayout";
import { getBackendAttendance, getBackendEmployees } from "@/lib/backend";
import { getAttendance, getEmployees } from "@/lib/storage";
import { normalizeDigits, todayKey } from "@/lib/utils";
import type { AttendanceRecord, Employee } from "@/types";
import { Link } from "react-router-dom";

function Dot({ status }: { status: "ok" | "warn" | "bad" }) { return <span className="live-status-dot" data-status={status === "ok" ? "info" : status === "warn" ? "warning" : "danger"} />; }
function Metric({ label, value, status }: { label: string; value: string | number; status?: "ok" | "warn" | "bad" }) { return <div className="rounded-2xl border border-border/60 bg-background/30 p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground">{status && <Dot status={status}/>} {label}</div><div className="live-value mono mt-1 text-2xl font-black">{value}</div></div>; }

export default function ManagerWorkforce() {
 const [employees,setEmployees]=useState<Employee[]>([]),[attendance,setAttendance]=useState<AttendanceRecord[]>([]),[query,setQuery]=useState(""),[sync,setSync]=useState(new Date());
 useEffect(()=>{let live=true;const load=async()=>{const [e,a]=await Promise.allSettled([getBackendEmployees(),getBackendAttendance(5000)]);if(!live)return;setEmployees(e.status==="fulfilled"?e.value:getEmployees());setAttendance(a.status==="fulfilled"?a.value:getAttendance());setSync(new Date())};void load();const t=window.setInterval(()=>void load(),10000);return()=>{live=false;window.clearInterval(t)}},[]);
 const today=todayKey(), todayRows=useMemo(()=>attendance.filter(x=>x.timestamp.startsWith(today)),[attendance,today]);
 const inIds=useMemo(()=>new Set(todayRows.filter(x=>x.type==="check-in").map(x=>x.employeeId)),[todayRows]);
 const outIds=useMemo(()=>new Set(todayRows.filter(x=>x.type==="check-out").map(x=>x.employeeId)),[todayRows]);
 const present=employees.filter(e=>inIds.has(e.id)&&!outIds.has(e.id)), absent=employees.filter(e=>e.status==="active"&&!inIds.has(e.id));
 const late=useMemo(()=>todayRows.filter(x=>x.type==="check-in").map(x=>{const e=employees.find(y=>y.id===x.employeeId);const [h,m]=(e?.workStartTime||"08:00").split(":").map(Number);const d=new Date(x.timestamp);const scheduled=new Date(d);scheduled.setHours(h||0,m||0,0,0);const minutes=Math.max(0,Math.round((d.getTime()-scheduled.getTime())/60000)-(e?.gracePeriodMinutes||0));return minutes?{...x,minutes}:null}).filter(Boolean) as Array<AttendanceRecord&{minutes:number}>,[todayRows,employees]);
 const filtered=employees.filter(e=>`${e.name} ${e.jobNumber}`.toLowerCase().includes(query.toLowerCase()));
 return <ManagerLayout title="مركز القوى العاملة" subtitle="مراقبة حية للموظفين والحضور والمخالفات بدون إعادة تحميل الواجهة." actions={<Link to="/manager" className="btn-secondary text-xs">لوحة القيادة</Link>}><div className="space-y-5">
  <section className="hud-card p-5 border-primary/25"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="mono text-xs font-bold text-primary">LIVE WORKFORCE CENTER</div><h1 className="text-2xl font-black mt-1">مركز المراقبة الحية</h1></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Dot status="ok"/> متصل · {normalizeDigits(sync.toLocaleTimeString("en-US",{hour12:false}))}</div></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-5"><Metric label="الموظفون" value={employees.length}/><Metric label="حاضر الآن" value={present.length} status="ok"/><Metric label="لم يحضر" value={absent.length} status="warn"/><Metric label="متأخر" value={late.length} status="bad"/><Metric label="نسبة الحضور" value={`${employees.length?Math.round(present.length/employees.length*100):0}%`}/></div></section>
  <div className="grid xl:grid-cols-[1.5fr_1fr] gap-5"><section className="hud-card p-5"><div className="flex justify-between gap-3 items-center"><h2 className="font-black">حالة الموظفين</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالاسم أو الرقم" className="rounded-lg border bg-background/40 px-3 py-2 text-xs"/></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{filtered.map(e=>{const active=inIds.has(e.id)&&!outIds.has(e.id),isLate=late.some(x=>x.employeeId===e.id);return <article key={e.id} className="rounded-xl border border-border/60 p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2 min-w-0"><Dot status={isLate?"bad":active?"ok":"warn"}/><div className="min-w-0"><div className="font-bold truncate">{e.name}</div><div className="mono text-[10px] text-muted-foreground">{e.jobNumber}</div></div></div><span className="text-[10px] font-bold">{isLate?"متأخر":active?"حاضر":"غائب"}</span></div><div className="mt-2 text-[10px] text-muted-foreground">{e.scheduleType==="ROTATION"?"مناوبة تناوبية":`${e.workStartTime||"08:00"} → ${e.workEndTime||"16:00"}`}</div></article>})}</div></section><section className="hud-card p-5"><div className="flex items-center gap-2"><Dot status="warn"/><h2 className="font-black">التنبيهات الحية</h2></div><div className="space-y-2 mt-4">{late.slice(0,8).map(x=><div key={x.id} className="rounded-xl border border-border/60 p-3"><div className="text-xs font-bold text-destructive">تأخير موظف</div><div className="text-xs text-muted-foreground mt-1">{employees.find(e=>e.id===x.employeeId)?.name||x.employeeName} · {normalizeDigits(String(x.minutes))} دقيقة</div></div>)}{absent.slice(0,8).map(e=><div key={e.id} className="rounded-xl border border-border/60 p-3"><div className="text-xs font-bold">لم يسجل حضورًا</div><div className="text-xs text-muted-foreground mt-1">{e.name}</div></div>)}{!late.length&&!absent.length&&<div className="py-8 text-center text-sm text-muted-foreground">لا توجد تنبيهات.</div>}</div></section></div>
  <section className="hud-card p-5"><h2 className="font-black">المخالفات المرصودة اليوم</h2><div className="overflow-x-auto mt-3"><table className="w-full text-xs"><thead><tr className="border-b border-border/60"><th className="text-right p-2">الموظف</th><th className="text-right p-2">النوع</th><th className="text-right p-2">المدة</th></tr></thead><tbody>{late.map(x=><tr key={x.id} className="border-b border-border/40"><td className="p-2 font-bold">{employees.find(e=>e.id===x.employeeId)?.name||x.employeeName}</td><td className="p-2">تأخير</td><td className="p-2 mono text-destructive">{normalizeDigits(String(x.minutes))} دقيقة</td></tr>)}{!late.length&&<tr><td colSpan={3} className="p-6 text-center text-muted-foreground">لا توجد مخالفات تأخير اليوم.</td></tr>}</tbody></table></div></section>
 </div></ManagerLayout>;
}
