import { useCallback, useEffect, useMemo, useState } from "react";
import ManagerLayout from "@/components/layout/ManagerLayout";

type Employee = { id:string; jobNumber:string; name:string; status:string; scheduleType:string; rotationStartDate?:string|null; rotationDaysOn?:number|null; rotationDaysOff?:number|null; workStartTime?:string|null; workEndTime?:string|null; workDays?:number[]; isVip:boolean; autoCheckIn:boolean; autoCheckOut:boolean };
const API=String(import.meta.env.VITE_API_URL||"https://hadir-api.abunizar963.workers.dev").replace(/\/$/,"");
const token=()=>localStorage.getItem("hadir.api.token.admin")||"";
async function call<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("content-type","application/json");headers.set("authorization",`Bearer ${token()}`);const r=await fetch(`${API}${path}`,{...init,headers,credentials:"include",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(d.error||"تعذر تنفيذ العملية"));return d as T;}
function schedule(e:Employee){if(e.scheduleType==="ROTATION")return `${e.rotationDaysOn||0} عمل / ${e.rotationDaysOff||0} راحة`;return `${e.workStartTime||"--:--"} → ${e.workEndTime||"--:--"}`;}
export default function ManagerWorkforceControls(){
 const [rows,setRows]=useState<Employee[]>([]);const [role,setRole]=useState("manager");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setRows(await call<Employee[]>("/api/manager/workforce-controls"));setError("");}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل التحكم");}finally{setLoading(false);}},[]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("hadir.manager_session")||"null");if(s?.role)setRole(String(s.role));}catch{};void load();},[load]);
 const owner=role==="owner";const active=useMemo(()=>rows.filter(e=>e.status==="active"),[rows]);
 const update=async(id:string,body:Partial<Pick<Employee,"isVip"|"autoCheckIn"|"autoCheckOut">>)=>{try{setBusy(id);await call("/api/workforce/live",{method:"PATCH",body:JSON.stringify({employeeId:id,...body})});setRows(v=>v.map(e=>e.id===id?{...e,...body}:e));}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");}finally{setBusy(null);}};
 const direct=async(id:string,type:"check-in"|"check-out")=>{try{setBusy(`${id}:${type}`);await call("/api/workforce/live",{method:"POST",body:JSON.stringify({employeeId:id,type})});await load();}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ العملية");}finally{setBusy(null);}};
 return <ManagerLayout title="التحكم المتقدم" subtitle="VIP والمناوبات والتحضير والانصراف والتلقائي — صلاحيات الخادم هي المرجع النهائي."><div className="space-y-5">
  <section className="hud-card border-primary/25 bg-primary/[.025] p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><div className="mono text-xs font-bold text-primary">WORKFORCE CONTROL</div><h1 className="mt-1 text-xl font-black">دورة المناوبة والتحضير الذكي</h1><p className="mt-1 text-xs leading-6 text-muted-foreground">{owner?"أنت المالك: يمكنك تغيير VIP والتلقائي وتنفيذ الإجراءات المباشرة.":"للقراءة والمراقبة فقط. التحضير والانصراف والتلقائي محجوزة للمالك."}</p></div><div className="rounded-xl border border-border/60 px-3 py-2 text-xs"><b>{active.length}</b> موظف فعال</div></div></section>
  {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
  {loading?<div className="hud-card p-6 text-sm text-muted-foreground">جارٍ تحميل الموظفين…</div>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{active.map(e=><article key={e.id} className="rounded-2xl border border-border/70 bg-card/60 p-4 shadow-sm">
    <div className="flex items-start justify-between gap-3"><div><div className="text-sm font-black">{e.name}</div><div className="mono mt-1 text-[11px] text-muted-foreground">{e.jobNumber}</div></div>{e.isVip&&<span className="rounded-full border border-amber-400/40 bg-amber-400/10 px-2 py-1 text-[10px] font-black text-amber-500">★ VIP</span>}</div>
    <div className="mt-3 grid grid-cols-2 gap-2 text-[11px]"><div className="rounded-xl border border-border/60 p-2"><span className="text-muted-foreground">المناوبة</span><div className="mt-1 font-bold">{schedule(e)}</div></div><div className="rounded-xl border border-border/60 p-2"><span className="text-muted-foreground">النوع</span><div className="mt-1 font-bold">{e.scheduleType==="ROTATION"?"تناوبي":"إداري"}</div></div></div>
    <div className="mt-3 space-y-2 text-xs"><label className="flex items-center justify-between gap-2 rounded-xl border border-border/60 p-2.5"><span>VIP</span><input type="checkbox" checked={e.isVip} disabled={!owner||busy===e.id} onChange={x=>void update(e.id,{isVip:x.target.checked})}/></label><label className="flex items-center justify-between gap-2 rounded-xl border border-border/60 p-2.5"><span>التحضير التلقائي</span><input type="checkbox" checked={e.autoCheckIn} disabled={!owner||busy===e.id} onChange={x=>void update(e.id,{autoCheckIn:x.target.checked})}/></label><label className="flex items-center justify-between gap-2 rounded-xl border border-border/60 p-2.5"><span>الانصراف التلقائي</span><input type="checkbox" checked={e.autoCheckOut} disabled={!owner||busy===e.id} onChange={x=>void update(e.id,{autoCheckOut:x.target.checked})}/></label></div>
    {owner&&<div className="mt-3 flex flex-wrap gap-2"><button className="btn-primary text-[11px]" disabled={busy===`${e.id}:check-in`} onClick={()=>void direct(e.id,"check-in")}>تحضير مباشر</button><button className="btn-secondary text-[11px]" disabled={busy===`${e.id}:check-out`} onClick={()=>void direct(e.id,"check-out")}>انصراف مباشر</button></div>}
  </article>)}</div>}
 </div></ManagerLayout>;
}
