import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Brand from "@/components/Brand";
import { getBackendRequests, updateBackendRequest } from "@/lib/backend";

const typeLabel=(type:string)=>type==="permission"?"استئذان":type==="leave"?"إجازة":"انصراف";
const statusLabel=(status:string)=>status==="pending"?"قيد المراجعة":status==="approved"?"موافق عليه":status==="rejected"?"مرفوض":status==="confirmed"?"تم التأكيد":status;

export default function ManagerRequests(){
 const [requests,setRequests]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState("");
 const load=async()=>{try{setError("");const rows=await getBackendRequests("admin");setRequests(Array.isArray(rows)?rows:[]);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الطلبات");}finally{setLoading(false)}};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(timer)},[]);
 const pending=useMemo(()=>requests.filter(r=>r.status==="pending"),[requests]); const history=useMemo(()=>requests.filter(r=>r.status!=="pending"),[requests]);
 const review=async(id:string,status:"approved"|"rejected")=>{setBusy(id);try{await updateBackendRequest(id,status);await load();}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث الطلب")}finally{setBusy(null)}};
 return <div className="min-h-screen"><header className="max-w-4xl mx-auto px-4 py-5 flex items-center justify-between"><Brand/><Link to="/manager" className="btn-ghost text-xs">العودة للوحة التحكم</Link></header><main className="max-w-4xl mx-auto px-4 pb-12 space-y-4"><section className="hud-card p-5 border-primary/25"><div className="flex items-center justify-between gap-3"><div><h1 className="text-xl font-extrabold">طلبات الموظفين</h1><p className="text-xs text-muted-foreground mt-1">إجازات واستئذان وانصراف · تتم المزامنة من الخادم تلقائيًا.</p></div><button onClick={()=>void load()} className="btn-secondary text-xs">تحديث</button></div></section>{error&&<div className="hud-card p-4 text-sm border-destructive/30"><b className="text-destructive">تعذر المزامنة:</b><span className="text-muted-foreground"> {error}</span></div>}{loading?<div className="hud-card p-5 text-center">جاري تحميل الطلبات…</div>:<>{pending.length===0?<div className="hud-card p-5 text-center text-sm text-muted-foreground">لا توجد طلبات بانتظار المراجعة.</div>:<section><div className="text-sm font-bold mb-2">طلبات بانتظار المراجعة <span className="badge bg-destructive/15 text-destructive">{pending.length}</span></div><div className="space-y-3">{pending.map(r=><RequestCard key={r.id} request={r} busy={busy===r.id} review={review}/>)}</div></section>}{history.length>0&&<section className="pt-3"><div className="text-sm font-bold mb-2">السجل السابق</div><div className="space-y-2">{history.slice(0,50).map(r=><section key={r.id} className="hud-card p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-bold">{r.employeeName} · {r.jobNumber}</div><div className="text-xs text-muted-foreground mt-1">طلب {typeLabel(r.type)} · {r.reason||"بدون سبب"}</div></div><span className="badge">{statusLabel(r.status)}</span></div></section>)}</div></section>}</>}</main></div>;
}
function RequestCard({request,busy,review}:{request:any;busy:boolean;review:(id:string,status:"approved"|"rejected")=>Promise<void>}){return <section className="hud-card p-4 border-primary/20"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-extrabold">{request.employeeName} <span className="text-muted-foreground font-normal">· {request.jobNumber}</span></div><div className="text-sm font-semibold text-primary mt-1">طلب {typeLabel(request.type)}</div><div className="text-xs text-muted-foreground mt-1">{request.reason||"بدون سبب"}</div><div className="text-[11px] text-muted-foreground mt-1">{new Date(request.createdAt).toLocaleString("ar-SA")}</div></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void review(request.id,"approved")} className="rounded-xl bg-primary text-primary-foreground px-4 py-2 text-xs font-bold disabled:opacity-50">{busy?"جاري…":"موافقة"}</button><button disabled={busy} onClick={()=>void review(request.id,"rejected")} className="rounded-xl border border-destructive/30 text-destructive px-4 py-2 text-xs font-bold disabled:opacity-50">رفض</button></div></div></section>}
