import { useEffect, useMemo, useState } from "react";
import ManagerLayout from "@/components/layout/ManagerLayout";
import { getBackendAttendance, getBackendEmployees } from "@/lib/backend";
import { getAttendance, getEmployees } from "@/lib/storage";
import { normalizeDigits, todayKey } from "@/lib/utils";
import type { AttendanceRecord, Employee } from "@/types";
import { Link } from "react-router-dom";

function Dot({ status }: { status: "ok" | "warn" | "bad" | "info" }) { return <span className="live-status-dot" data-status={status === "ok" ? "info" : status === "warn" ? "warning" : status === "bad" ? "danger" : "info"} />; }
function Metric({ label, value, status }: { label: string; value: string | number; status?: "ok" | "warn" | "bad" }) { return <div className="rounded-2xl border border-border/60 bg-background/30 p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground">{status && <Dot status={status}/>} {label}</div><div className="live-value mono mt-1 text-2xl font-black">{value}</div></div>; }

type LiveBundle = { summary?: { total:number;active:number;checkedIn:number;checkedOut:number}; notifications?: any[]; violations?: any[]; leaveRequests?: any[]; tasks?: any[]; performance?: any[]; payroll?: any[]; anomalies?: any[]; insights?: any[]; escapes?: any[]; generatedAt?: string };
async function api(path: string, init?: RequestInit) { const r=await fetch(path,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers||{})}}); if(!r.ok) throw new Error(await r.text().catch(()=>"Request failed")); return r.json(); }

export default function ManagerWorkforce() {
 const [employees,setEmployees]=useState<Employee[]>([]),[attendance,setAttendance]=useState<AttendanceRecord[]>([]),[bundle,setBundle]=useState<LiveBundle>({}),[query,setQuery]=useState(""),[sync,setSync]=useState(new Date()),[tab,setTab]=useState("live"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const [e,a,b]=await Promise.allSettled([getBackendEmployees(),getBackendAttendance(5000),api("/api/workforce/live")]);setEmployees(e.status==="fulfilled"?e.value:getEmployees());setAttendance(a.status==="fulfilled"?a.value:getAttendance());if(b.status==="fulfilled")setBundle(b.value);setSync(new Date())};
 useEffect(()=>{let live=true;void load();const t=window.setInterval(()=>{if(live)void load()},10000);return()=>{live=false;window.clearInterval(t)}},[]);
 const today=todayKey(), todayRows=useMemo(()=>attendance.filter(x=>x.timestamp.startsWith(today)),[attendance,today]);
 const inIds=useMemo(()=>new Set(todayRows.filter(x=>x.type==="check-in").map(x=>x.employeeId)),[todayRows]); const outIds=useMemo(()=>new Set(todayRows.filter(x=>x.type==="check-out").map(x=>x.employeeId)),[todayRows]);
 const present=employees.filter(e=>inIds.has(e.id)&&!outIds.has(e.id)), absent=employees.filter(e=>e.status==="active"&&!inIds.has(e.id));
 const late=useMemo(()=>todayRows.filter(x=>x.type==="check-in").map(x=>{const e=employees.find(y=>y.id===x.employeeId);const [h,m]=(e?.workStartTime||"08:00").split(":").map(Number);const d=new Date(x.timestamp);const scheduled=new Date(d);scheduled.setHours(h||0,m||0,0,0);const minutes=Math.max(0,Math.round((d.getTime()-scheduled.getTime())/60000)-(e?.gracePeriodMinutes||0));return minutes?{...x,minutes}:null}).filter(Boolean) as Array<AttendanceRecord&{minutes:number}>,[todayRows,employees]);
 const filtered=employees.filter(e=>`${e.name} ${e.jobNumber}`.toLowerCase().includes(query.toLowerCase()));
 const runAI=async()=>{setBusy(true);setMessage("");try{await api("/api/ai/insights/generate",{method:"POST",body:"{}"});await load();setMessage("تم تحديث التحليل الذكي")}catch(e){setMessage(e instanceof Error?e.message:"تعذر تنفيذ التحليل")}finally{setBusy(false)}};
 const scan=async()=>{setBusy(true);try{await api("/api/anomalies/scan",{method:"POST",body:"{}"});await load();setMessage("تم فحص الأنماط غير الطبيعية")}catch(e){setMessage(e instanceof Error?e.message:"تعذر الفحص")}finally{setBusy(false)}};
 const tabs=["live","violations","requests","tasks","performance","payroll","ai","escapes"];
 return <ManagerLayout title="مركز القوى العاملة" subtitle="منصة تشغيل حية للموظفين والحضور والمخالفات والطلبات والتحليلات بدون إعادة تحميل الواجهة." actions={<Link to="/manager" className="btn-secondary text-xs">لوحة القيادة</Link>}><div className="space-y-5">
  <section className="hud-card p-5 border-primary/25"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="mono text-xs font-bold text-primary">LIVE WORKFORCE CENTER</div><h1 className="text-2xl font-black mt-1">مركز المراقبة الحية</h1></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Dot status="ok"/> متصل · {normalizeDigits(sync.toLocaleTimeString("en-US",{hour12:false}))}</div></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-5"><Metric label="الموظفون" value={employees.length}/><Metric label="حاضر الآن" value={present.length} status="ok"/><Metric label="لم يحضر" value={absent.length} status="warn"/><Metric label="متأخر" value={late.length} status="bad"/><Metric label="نسبة الحضور" value={`${employees.length?Math.round(present.length/employees.length*100):0}%`}/></div></section>
  <div className="flex flex-wrap gap-2">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${tab===x?"border-primary bg-primary/10":"border-border/60"}`}>{({live:"الحالة الحية",violations:"المخالفات",requests:"الإجازات",tasks:"المهام",performance:"الأداء",payroll:"الرواتب",ai:"الذكاء الاصطناعي",escapes:"الهروب"} as any)[x]}</button>)}</div>
  {message&&<div className="rounded-xl border border-primary/30 bg-primary/5 p-3 text-xs">{message}</div>}
  {tab==="live"&&<div className="grid xl:grid-cols-[1.5fr_1fr] gap-5"><section className="hud-card p-5"><div className="flex justify-between gap-3 items-center"><h2 className="font-black">حالة الموظفين</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالاسم أو الرقم" className="rounded-lg border bg-background/40 px-3 py-2 text-xs"/></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{filtered.map(e=>{const active=inIds.has(e.id)&&!outIds.has(e.id),isLate=late.some(x=>x.employeeId===e.id);return <article key={e.id} className="rounded-xl border border-border/60 p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2 min-w-0"><Dot status={isLate?"bad":active?"ok":"warn"}/><div className="min-w-0"><div className="font-bold truncate">{e.name}</div><div className="mono text-[10px] text-muted-foreground">{e.jobNumber}</div></div></div><span className="text-[10px] font-bold">{isLate?"متأخر":active?"حاضر":"غائب"}</span></div><div className="mt-2 text-[10px] text-muted-foreground">{e.scheduleType==="ROTATION"?"مناوبة تناوبية":`${e.workStartTime||"08:00"} → ${e.workEndTime||"16:00"}`}</div></article>})}</div></section><section className="hud-card p-5"><div className="flex items-center gap-2"><Dot status="warn"/><h2 className="font-black">التنبيهات</h2></div><div className="space-y-2 mt-4">{late.slice(0,8).map(x=><div key={x.id} className="rounded-xl border border-border/60 p-3"><div className="text-xs font-bold text-destructive">تأخير موظف</div><div className="text-xs text-muted-foreground mt-1">{employees.find(e=>e.id===x.employeeId)?.name||x.employeeName} · {normalizeDigits(String(x.minutes))} دقيقة</div></div>)}{absent.slice(0,8).map(e=><div key={e.id} className="rounded-xl border border-border/60 p-3"><div className="text-xs font-bold">لم يسجل حضورًا</div><div className="text-xs text-muted-foreground mt-1">{e.name}</div></div>)}</div></section></div>}
  {tab!=="live"&&<section className="hud-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black">{{violations:"المخالفات",requests:"طلبات الإجازة",tasks:"المهام",performance:"تقييم الأداء",payroll:"كشف الرواتب",ai:"التحليلات الذكية",escapes:"سجل الهروب والعودة"}[tab]}</h2>{tab==="ai"&&<div className="flex gap-2"><button disabled={busy} onClick={runAI} className="btn-primary text-xs">✨ تحليل ذكي</button><button disabled={busy} onClick={scan} className="btn-secondary text-xs">فحص الأنماط</button></div>}</div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{((tab==="violations"?bundle.violations:tab==="requests"?bundle.leaveRequests:tab==="tasks"?bundle.tasks:tab==="performance"?bundle.performance:tab==="payroll"?bundle.payroll:tab==="ai"?bundle.insights:bundle.escapes)||[]).slice(0,30).map((x:any,i)=><div key={x.id||i} className="rounded-xl border border-border/60 p-3"><div className="flex items-center gap-2 text-xs font-bold"><Dot status={x.status==="rejected"||x.status==="dismissed"||x.severity==="danger"?"bad":x.status==="approved"||x.status==="resolved"?"ok":"info"}/>{x.employeeName||x.title||x.type||x.kind||"سجل"}</div><pre className="mt-2 whitespace-pre-wrap text-[10px] text-muted-foreground font-sans">{JSON.stringify(x,null,2)}</pre></div>)}{!((tab==="violations"?bundle.violations:tab==="requests"?bundle.leaveRequests:tab==="tasks"?bundle.tasks:tab==="performance"?bundle.performance:tab==="payroll"?bundle.payroll:tab==="ai"?bundle.insights:bundle.escapes)||[]).length&&<div className="col-span-full py-10 text-center text-sm text-muted-foreground">لا توجد بيانات بعد.</div>}</div></section>}
 </div></ManagerLayout>;
}