import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Compass, LocateFixed, MapPin, Navigation, RefreshCw, Share2 } from "lucide-react";
import { getPrayerTimes, qiblaBearing, distanceToKaabaKm, bearingLabel, type PrayerResponse } from "@/lib/prayerTimes";

type PrayerKey="fajr"|"sunrise"|"dhuhr"|"asr"|"maghrib"|"isha";
const PRAYERS:{key:PrayerKey;name:string;icon:string}[]=[{key:"fajr",name:"الفجر",icon:"🌙"},{key:"sunrise",name:"الشروق",icon:"🌅"},{key:"dhuhr",name:"الظهر",icon:"☀️"},{key:"asr",name:"العصر",icon:"🌤️"},{key:"maghrib",name:"المغرب",icon:"🌇"},{key:"isha",name:"العشاء",icon:"🌙"}];
function minutes(hhmm:string){const [h,m]=hhmm.split(":").map(Number);return h*60+m;}
function fmtCountdown(ms:number){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor((s%3600)/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
function greeting(){const h=new Date().getHours();return h<5?"ليل سعيد":h<12?"صباح الخير":h<18?"نهار سعيد":"مساء الخير";}

export default function PrayerPage(){
 const navigate=useNavigate(); const [pos,setPos]=useState<GeolocationPosition|null>(null); const [data,setData]=useState<PrayerResponse|null>(null); const [bearing,setBearing]=useState<number|null>(null); const [heading,setHeading]=useState<number|null>(null); const [sensorEnabled,setSensorEnabled]=useState(false); const [error,setError]=useState(""); const [now,setNow]=useState(new Date()); const [city,setCity]=useState("موقعك الحالي");
 const locate=useCallback(()=>{if(!navigator.geolocation){setError("الموقع غير متاح على هذا الجهاز");return;}setError("");navigator.geolocation.getCurrentPosition(async p=>{setPos(p);setBearing(qiblaBearing(p.coords.latitude,p.coords.longitude));try{const geo=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&localityLanguage=ar`).then(r=>r.json()) as {city?:string;locality?:string;principalSubdivision?:string};const name=geo.city||geo.locality||geo.principalSubdivision||"موقعك الحالي";setCity(name);const result=await getPrayerTimes({latitude:p.coords.latitude,longitude:p.coords.longitude,city:name});setData(result);}catch{setError("تعذر جلب بيانات الصلاة للموقع الحالي");}},()=>setError("اسمح بالوصول إلى الموقع لعرض المواقيت والقبلة"),{enableHighAccuracy:true,timeout:10000,maximumAge:300000});},[]);
 useEffect(()=>{locate();},[locate]); useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id);},[]);
 const readOrientation=useCallback((event:DeviceOrientationEvent)=>{const e=event as DeviceOrientationEvent & {webkitCompassHeading?:number};let h:number|undefined;if(typeof e.webkitCompassHeading==="number")h=e.webkitCompassHeading;else if(typeof event.alpha==="number")h=(360-event.alpha)%360;if(h!=null)setHeading((h+360)%360);},[]);
 const enableCompass=async()=>{const req=(DeviceOrientationEvent as typeof DeviceOrientationEvent & {requestPermission?:()=>Promise<string>}).requestPermission;if(req){try{if(await req()!=="granted")return;}catch{return;}}window.addEventListener("deviceorientationabsolute",readOrientation,true);window.addEventListener("deviceorientation",readOrientation,true);setSensorEnabled(true);};
 useEffect(()=>()=>{window.removeEventListener("deviceorientationabsolute",readOrientation,true);window.removeEventListener("deviceorientation",readOrientation,true);},[readOrientation]);
 const next=useMemo(()=>{if(!data)return null;const current=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;const today=PRAYERS.map(p=>({p,t:minutes(data.times[p.key])}));return today.find(x=>x.t>current)||{p:PRAYERS[0],t:today[0].t+1440};},[data,now]);
 const countdown=useMemo(()=>{if(!data||!next)return "--:--:--";const target=new Date(now);target.setHours(Math.floor(next.t/60),next.t%60,0,0);if(next.t>=1440)target.setDate(target.getDate()+1);return fmtCountdown(target.getTime()-now.getTime());},[data,next,now]);
 const relative=heading==null?(bearing??0):((bearing??0)-heading+360)%360; const distance=pos?distanceToKaabaKm(pos.coords.latitude,pos.coords.longitude):null;
 const share=async()=>{const text=`اتجاه القبلة من ${city}: ${bearing==null?"--":Math.round(bearing)+"°"} • المسافة إلى مكة: ${distance==null?"--":distance.toFixed(1)+" كم"}`;if(navigator.share)await navigator.share({title:"اتجاه القبلة",text});else await navigator.clipboard?.writeText(text);};
 return <main dir="rtl" className="min-h-screen bg-[#07111f] p-3 text-white sm:p-6"><div className="mx-auto max-w-5xl space-y-4"><button onClick={()=>navigate(-1)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold"><ArrowRight className="h-4 w-4"/>العودة</button>
 <section className="overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#102746] to-[#07111f] shadow-2xl"><div className="p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-sm text-sky-200/80">{greeting()} 👋</div><h1 className="mt-1 text-2xl font-black sm:text-3xl">الصلاة القادمة بعد {next?.p.name||"—"}</h1><p className="mt-1 text-sm text-slate-300"><MapPin className="mr-1 inline h-4 w-4"/>{city} • {data?.meta.gregorian||"جارٍ تحديد التاريخ"}{data?.meta.hijri&&` • ${data.meta.hijri}`}</p></div><div className="rounded-2xl border border-sky-300/20 bg-sky-300/10 px-5 py-3 text-center"><div className="text-xs text-sky-100/70">المتبقي</div><div className="font-mono text-3xl font-black tracking-wider text-sky-100">{countdown}</div></div></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-3xl border border-white/10 bg-black/10 p-5"><div className="mb-4 flex items-center justify-between"><div className="font-black">بوصلة القبلة</div><div className="rounded-full bg-sky-400/10 px-3 py-1 text-xs text-sky-200">{sensorEnabled&&heading!=null?"حساس مباشر":"موقع الجهاز"}</div></div><div className="flex flex-col items-center"><div className="relative grid h-64 w-64 place-items-center rounded-full border-[10px] border-[#15365d] bg-[#0a1c31] shadow-[inset_0_0_50px_rgba(0,0,0,.45),0_15px_45px_rgba(0,0,0,.25)]"><div className="absolute inset-4 rounded-full border border-sky-300/20"/><span className="absolute top-3 text-xs font-black text-slate-300">N</span><span className="absolute bottom-3 text-xs text-slate-400">S</span><span className="absolute right-4 text-xs text-slate-400">E</span><span className="absolute left-4 text-xs text-slate-400">W</span><div className="absolute h-[102px] w-[5px] origin-bottom rounded-full bg-gradient-to-t from-sky-400 to-white shadow-[0_0_18px_rgba(56,189,248,.65)] transition-transform duration-150" style={{transform:`translateY(-50%) rotate(${relative}deg)`}}/><div className="relative z-10 grid h-16 w-16 place-items-center rounded-full border border-sky-200/20 bg-[#102746] text-3xl shadow-xl">🕋</div></div><div className="mt-4 text-center"><div className="font-mono text-4xl font-black text-sky-200">{bearing==null?"--":`${Math.round(bearing)}°`}</div><div className="text-sm text-slate-300">{bearing==null?"جارٍ تحديد الاتجاه":`${bearingLabel(bearing)} نحو مكة`}</div><div className="mt-2 text-xs text-slate-400">اتجاه الجهاز: {heading==null?"--":`${Math.round(heading)}°`}</div></div><div className="mt-4 flex flex-wrap justify-center gap-2"><button onClick={share} className="inline-flex items-center gap-2 rounded-xl bg-sky-500 px-4 py-2 text-sm font-bold text-slate-950"><Share2 className="h-4 w-4"/>مشاركة اتجاه مدينتي</button><button onClick={locate} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>إعادة تحديد الموقع</button>{!sensorEnabled&&<button onClick={enableCompass} className="rounded-xl border border-sky-300/20 bg-sky-300/10 px-4 py-2 text-sm font-bold text-sky-100">تفعيل البوصلة الحية</button>}</div></div></div>
 <div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-black">مواقيت الصلاة</h2><span className="text-xs text-slate-400">رابطة العالم الإسلامي</span></div><div className="space-y-2">{PRAYERS.map(p=>{const active=next?.p.key===p.key;return <div key={p.key} className={`flex items-center justify-between rounded-2xl px-4 py-3 ${active?"bg-sky-400/15 ring-1 ring-sky-300/30":"bg-white/[.03]"}`}><div className="flex items-center gap-3"><span className="text-xl">{p.icon}</span><span className={active?"font-black text-sky-200":"text-slate-200"}>{p.name}</span></div><span className="font-mono text-lg font-black">{data?.times[p.key]||"--:--"}</span></div>})}</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[.04] p-3"><div className="text-xs text-slate-400">المسافة إلى الكعبة</div><div className="mt-1 font-mono font-black">{distance==null?"--":`${distance.toFixed(1)} كم`}</div></div><div className="rounded-2xl bg-white/[.04] p-3"><div className="text-xs text-slate-400">طريقة الحساب</div><div className="mt-1 font-black">MWL · 3</div></div></div></div></div></div></section>{error&&<div className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-100">{error}</div>}</div></main>;
}
