import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, MapPin, RefreshCw, Share2 } from "lucide-react";
import { getPrayerTimes, qiblaBearing, distanceToKaabaKm, bearingLabel, type PrayerResponse } from "@/lib/prayerTimes";

type PrayerKey="fajr"|"sunrise"|"dhuhr"|"asr"|"maghrib"|"isha";
const PRAYERS:{key:PrayerKey;name:string;icon:string}[]=[{key:"fajr",name:"الفجر",icon:"🌙"},{key:"sunrise",name:"الشروق",icon:"🌅"},{key:"dhuhr",name:"الظهر",icon:"☀️"},{key:"asr",name:"العصر",icon:"🌤️"},{key:"maghrib",name:"المغرب",icon:"🌇"},{key:"isha",name:"العشاء",icon:"🌙"}];
function minutes(hhmm:string){const [h,m]=hhmm.split(":").map(Number);return h*60+m;}
function fmtCountdown(ms:number){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor((s%3600)/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
function greeting(){const h=new Date().getHours();return h<5?"ليل سعيد":h<12?"صباح الخير":h<18?"نهار سعيد":"مساء الخير";}
function normalize(deg:number){return (deg%360+360)%360;}
function shortestDelta(target:number,current:number){return ((target-current+540)%360)-180;}
type OrientationEventWithIOS=DeviceOrientationEvent & { webkitCompassHeading?:number; webkitCompassAccuracy?:number };
type OrientationCtor=typeof DeviceOrientationEvent & { requestPermission?:()=>Promise<"granted"|"denied"|"default"> };

export default function PrayerPage(){
 const navigate=useNavigate();
 const [pos,setPos]=useState<GeolocationPosition|null>(null); const [data,setData]=useState<PrayerResponse|null>(null); const [bearing,setBearing]=useState<number|null>(null);
 const [heading,setHeading]=useState(0); const [sensorEnabled,setSensorEnabled]=useState(false); const [permissionNeeded,setPermissionNeeded]=useState(false); const [sensorMessage,setSensorMessage]=useState(""); const [error,setError]=useState(""); const [now,setNow]=useState(new Date()); const [city,setCity]=useState("موقعك الحالي");
 const rawHeadingRef=useRef(0); const animatedHeadingRef=useRef(0); const frameRef=useRef<number|undefined>();
 const locate=useCallback(()=>{if(!navigator.geolocation){setError("الموقع غير متاح على هذا الجهاز");return;}setError("");navigator.geolocation.getCurrentPosition(async p=>{setPos(p);setBearing(qiblaBearing(p.coords.latitude,p.coords.longitude));try{const geo=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&localityLanguage=ar`).then(r=>r.json()) as {city?:string;locality?:string;principalSubdivision?:string};const name=geo.city||geo.locality||geo.principalSubdivision||"موقعك الحالي";setCity(name);setData(await getPrayerTimes({latitude:p.coords.latitude,longitude:p.coords.longitude,city:name}));}catch{setError("تعذر جلب بيانات الصلاة للموقع الحالي");}},()=>setError("اسمح بالوصول إلى الموقع لعرض المواقيت والقبلة"),{enableHighAccuracy:true,timeout:10000,maximumAge:300000});},[]);
 useEffect(()=>{locate();},[locate]); useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id);},[]);
 const readOrientation=useCallback((event:DeviceOrientationEvent)=>{const e=event as OrientationEventWithIOS;let next:number|undefined;if(typeof e.webkitCompassHeading==="number"&&Number.isFinite(e.webkitCompassHeading)){next=e.webkitCompassHeading;}else if(typeof event.alpha==="number"&&Number.isFinite(event.alpha)){next=normalize(360-event.alpha);}if(next==null)return;rawHeadingRef.current=normalize(next);setSensorEnabled(true);setSensorMessage("");},[]);
 const enableCompass=useCallback(async()=>{try{if(!window.isSecureContext){setSensorMessage("البوصلة الحية تحتاج إلى HTTPS أو localhost.");return;}const ctor=(window.DeviceOrientationEvent as unknown as OrientationCtor|undefined);const request=ctor?.requestPermission;if(request){const result=await request();if(result!=="granted"){setSensorMessage("تم رفض الوصول إلى حساس البوصلة. اسمح بالحركة والاتجاه من إعدادات الجهاز.");return;}}window.removeEventListener("deviceorientationabsolute",readOrientation,true);window.removeEventListener("deviceorientation",readOrientation,true);window.addEventListener("deviceorientationabsolute",readOrientation,true);window.addEventListener("deviceorientation",readOrientation,true);setPermissionNeeded(false);setSensorMessage("حرّك الهاتف ببطء؛ السهم الأخضر سيبقى متجهاً نحو القبلة.");}catch{setSensorMessage("تعذر الوصول إلى حساس الاتجاه. تأكد من HTTPS ودعم المتصفح للحساسات.");}},[readOrientation]);
 const resetCompass=useCallback(()=>{rawHeadingRef.current=0;animatedHeadingRef.current=0;setHeading(0);setSensorEnabled(false);setSensorMessage("");setPermissionNeeded(false);if(!window.isSecureContext){setSensorMessage("البوصلة الحية تحتاج إلى HTTPS أو localhost.");return;}const ctor=(window.DeviceOrientationEvent as unknown as OrientationCtor|undefined);if(ctor?.requestPermission)setPermissionNeeded(true);else{window.removeEventListener("deviceorientationabsolute",readOrientation,true);window.removeEventListener("deviceorientation",readOrientation,true);window.addEventListener("deviceorientationabsolute",readOrientation,true);window.addEventListener("deviceorientation",readOrientation,true);setSensorMessage("أعيدت معايرة القراءة. حرّك الهاتف ببطء.");}},[readOrientation]);
 useEffect(()=>{if(!window.isSecureContext){setSensorMessage("البوصلة الحية تحتاج إلى HTTPS أو localhost.");return;}const ctor=(window.DeviceOrientationEvent as unknown as OrientationCtor|undefined);if(ctor?.requestPermission)setPermissionNeeded(true);else{window.addEventListener("deviceorientationabsolute",readOrientation,true);window.addEventListener("deviceorientation",readOrientation,true);}return()=>{window.removeEventListener("deviceorientationabsolute",readOrientation,true);window.removeEventListener("deviceorientation",readOrientation,true);if(frameRef.current)cancelAnimationFrame(frameRef.current);};},[readOrientation]);
 useEffect(()=>{const animate=()=>{const delta=shortestDelta(rawHeadingRef.current,animatedHeadingRef.current);animatedHeadingRef.current=normalize(animatedHeadingRef.current+delta*.18);setHeading(animatedHeadingRef.current);frameRef.current=requestAnimationFrame(animate);};frameRef.current=requestAnimationFrame(animate);return()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);};},[]);
 const next=useMemo(()=>{if(!data)return null;const current=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;const today=PRAYERS.map(p=>({p,t:minutes(data.times[p.key])}));return today.find(x=>x.t>current)||{p:PRAYERS[0],t:today[0].t+1440};},[data,now]);
 const countdown=useMemo(()=>{if(!data||!next)return "--:--:--";const target=new Date(now);target.setHours(Math.floor(next.t/60),next.t%60,0,0);if(next.t>=1440)target.setDate(target.getDate()+1);return fmtCountdown(target.getTime()-now.getTime());},[data,next,now]);
 const distance=pos?distanceToKaabaKm(pos.coords.latitude,pos.coords.longitude):null;
 const share=async()=>{const text=`اتجاه القبلة من ${city}: ${bearing==null?"--":Math.round(bearing)+"°"} • المسافة إلى مكة: ${distance==null?"--":distance.toFixed(1)+" كم"}`;if(navigator.share)await navigator.share({title:"اتجاه القبلة",text});else await navigator.clipboard?.writeText(text);};
 const relativeQibla=bearing==null?0:normalize(bearing-heading);
 const aligned=bearing!=null&&Math.abs(shortestDelta(bearing,heading))<=5;
 return <main dir="rtl" className="min-h-screen bg-[#07111f] p-3 text-white sm:p-6"><div className="mx-auto max-w-5xl space-y-4"><button onClick={()=>navigate(-1)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold"><ArrowRight className="h-4 w-4"/>العودة</button>
 <section className="overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#102746] to-[#07111f] shadow-2xl"><div className="p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-sm text-sky-200/80">{greeting()} 👋</div><h1 className="mt-1 text-2xl font-black sm:text-3xl">الصلاة القادمة بعد {next?.p.name||"—"}</h1><p className="mt-1 text-sm text-slate-300"><MapPin className="mr-1 inline h-4 w-4"/>{city} • {data?.meta.gregorian||"جارٍ تحديد التاريخ"}{data?.meta.hijri&&` • ${data.meta.hijri}`}</p></div><div className="rounded-2xl border border-sky-300/20 bg-sky-300/10 px-5 py-3 text-center"><div className="text-xs text-sky-100/70">المتبقي</div><div className="font-mono text-3xl font-black tracking-wider text-sky-100">{countdown}</div></div></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-3xl border border-white/10 bg-black/10 p-5"><div className="mb-4 flex items-center justify-between"><div className="font-black">بوصلة القبلة</div><div className={`rounded-full px-3 py-1 text-xs ${sensorEnabled?"bg-emerald-400/10 text-emerald-300":"bg-sky-400/10 text-sky-200"}`}>{sensorEnabled?"حساس مباشر":"بانتظار الحساس"}</div></div>
 <div className="flex flex-col items-center"><div className="relative grid h-72 w-72 place-items-center rounded-full border-[10px] border-emerald-400/40 bg-[#071a2e] shadow-[inset_0_0_55px_rgba(0,0,0,.55),0_0_35px_rgba(52,211,153,.16)]"><div className="absolute inset-3 rounded-full border border-emerald-300/15"/><div className="absolute inset-6 rounded-full border border-dashed border-emerald-300/10"/><div className="absolute inset-0" style={{transform:`rotate(${-heading}deg)`,transition:"transform 70ms linear"}}>{Array.from({length:36},(_,i)=><span key={i} className="absolute left-1/2 top-1/2 block h-1/2 w-[1px] origin-bottom bg-slate-400/30" style={{transform:`translate(-50%,-100%) rotate(${i*10}deg)`}}/>)}<span className="absolute inset-x-0 top-4 text-center text-xs font-black text-slate-200">شمال</span><span className="absolute bottom-4 inset-x-0 text-center text-xs text-slate-400">جنوب</span><span className="absolute right-4 top-1/2 -translate-y-1/2 text-xs text-slate-400">شرق</span><span className="absolute left-4 top-1/2 -translate-y-1/2 text-xs text-slate-400">غرب</span></div><div className="absolute inset-0 grid place-items-center"><div className="absolute h-[43%] w-[7px] origin-bottom rounded-full bg-gradient-to-t from-emerald-600 via-emerald-300 to-white shadow-[0_0_24px_rgba(52,211,153,.9)]" style={{transform:`translateY(-50%) rotate(${relativeQibla}deg)`,transition:"transform 70ms linear"}}/><div className="absolute -translate-y-[126px] text-emerald-300 text-2xl">▲</div><div className="absolute grid h-20 w-20 place-items-center rounded-full border border-emerald-300/40 bg-[#102746] text-3xl shadow-2xl">🕋</div></div></div>
 <div className="mt-4 text-center"><div className="font-mono text-4xl font-black text-emerald-300">{bearing==null?"--":`${Math.round(bearing)}°`}</div><div className="text-sm text-slate-300">{aligned?"أنت تواجه القبلة ✓":bearing==null?"جارٍ تحديد الاتجاه":`${bearingLabel(bearing)} نحو مكة`}</div><div className="mt-2 text-xs text-slate-400">اتجاه الجهاز: {Math.round(heading)}° • زاوية الدوران للقبلة: {bearing==null?"--":`${Math.round(relativeQibla)}°`}</div></div>
 <div className="mt-4 flex flex-wrap justify-center gap-2"><button onClick={share} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-2 text-sm font-bold text-slate-950"><Share2 className="h-4 w-4"/>مشاركة اتجاه مدينتي</button><button onClick={locate} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>إعادة تحديد الموقع</button><button onClick={resetCompass} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold">إعادة ضبط البوصلة</button>{permissionNeeded&&<button onClick={enableCompass} className="rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-2 text-sm font-bold text-emerald-100">تفعيل البوصلة الحية</button>}</div>{sensorMessage&&<p className="mt-3 max-w-md text-center text-xs text-amber-200">{sensorMessage}</p>}</div></div>
 <div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-black">مواقيت الصلاة</h2><span className="text-xs text-slate-400">رابطة العالم الإسلامي</span></div><div className="space-y-2">{PRAYERS.map(p=>{const active=next?.p.key===p.key;return <div key={p.key} className={`flex items-center justify-between rounded-2xl px-4 py-3 ${active?"bg-emerald-400/15 ring-1 ring-emerald-300/30":"bg-white/[.03]"}`}><div className="flex items-center gap-3"><span className="text-xl">{p.icon}</span><span className={active?"font-black text-emerald-200":"text-slate-200"}>{p.name}</span></div><span className="font-mono text-lg font-black">{data?.times[p.key]||"--:--"}</span></div>})}</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[.04] p-3"><div className="text-xs text-slate-400">المسافة إلى الكعبة</div><div className="mt-1 font-mono font-black">{distance==null?"--":`${distance.toFixed(1)} كم`}</div></div><div className="rounded-2xl bg-white/[.04] p-3"><div className="text-xs text-slate-400">طريقة الحساب</div><div className="mt-1 font-black">MWL · 3</div></div></div></div></div></div></section>{error&&<div className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-100">{error}</div>}</div></main>;
}
