import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Compass, LocateFixed } from "lucide-react";
import { getPrayerTimes, qiblaBearing, bearingLabel, type PrayerTimes } from "@/lib/prayerTimes";

export default function PrayerPage(){
 const navigate=useNavigate(); const [pos,setPos]=useState<GeolocationPosition|null>(null); const [times,setTimes]=useState<PrayerTimes|null>(null); const [bearing,setBearing]=useState<number|null>(null); const [error,setError]=useState("");
 useEffect(()=>{if(!navigator.geolocation){setError("الموقع غير متاح على هذا الجهاز");return;} navigator.geolocation.getCurrentPosition(p=>{setPos(p);setBearing(qiblaBearing(p.coords.latitude,p.coords.longitude));getPrayerTimes({latitude:p.coords.latitude,longitude:p.coords.longitude}).then(setTimes).catch(()=>setError("تعذر جلب مواقيت الصلاة"));},()=>setError("اسمح بالوصول إلى الموقع لعرض المواقيت واتجاه القبلة"),{enableHighAccuracy:true,timeout:10000});},[]);
 const cards=[['الفجر',times?.fajr,'🌙'],['الشروق',times?.sunrise,'🌅'],['الظهر',times?.dhuhr,'☀️'],['العصر',times?.asr,'🌤️'],['المغرب',times?.maghrib,'🌇'],['العشاء',times?.isha,'🌙']];
 return <main dir="rtl" className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-5xl space-y-5"><button onClick={()=>navigate(-1)} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2 text-sm font-bold"><ArrowRight className="h-4 w-4"/>العودة</button><section className="rounded-3xl border border-border bg-card p-6 shadow-xl"><div className="flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-primary/10 text-2xl">🕌</div><div><h1 className="text-2xl font-black">مواقيت الصلاة والقبلة</h1><p className="text-sm text-muted-foreground">حسب موقعك الحالي • تحديث يومي تلقائي</p></div></div>{error?<div className="mt-6 rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm">{error}</div>:<><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{cards.map(([name,time,icon])=><div key={name} className="rounded-2xl border border-border bg-secondary/40 p-4 text-center"><div className="text-2xl">{icon}</div><div className="mt-2 text-xs text-muted-foreground">{name}</div><div className="mt-1 text-xl font-black mono">{time||'--:--'}</div></div>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-border bg-secondary/30 p-5"><div className="flex items-center gap-2 font-black"><Compass className="h-5 w-5 text-primary"/>اتجاه القبلة</div><div className="mt-4 flex items-center gap-5"><div className="relative grid h-28 w-28 place-items-center rounded-full border-2 border-primary/30"><div className="absolute bottom-1/2 left-1/2 h-12 w-1 origin-bottom rounded-full bg-primary" style={{transform:`translateX(-50%) rotate(${bearing||0}deg)`}}/><span className="text-2xl">🕋</span></div><div><div className="text-3xl font-black mono">{bearing==null?'--':`${Math.round(bearing)}°`}</div><div className="text-sm text-muted-foreground">{bearing==null?'جارٍ تحديد الاتجاه':bearingLabel(bearing)} نحو مكة</div></div></div></div><div className="rounded-2xl border border-border bg-secondary/30 p-5"><div className="font-black">الموقع</div><div className="mt-4 flex items-center gap-3 text-sm"><LocateFixed className="h-5 w-5 text-primary"/><span>{pos?`${pos.coords.latitude.toFixed(4)}, ${pos.coords.longitude.toFixed(4)}`:'جارٍ تحديد الموقع'}</span></div><p className="mt-3 text-xs text-muted-foreground">يتم استخدام موقع الجهاز لحساب المواقيت والقبلة فقط.</p></div></div></>}</section></div></main>;
}
