import 'package:flutter/material.dart';
import '../core/api.dart';
import '../core/session.dart';
import '../services/requests_service.dart';

class RequestsPage extends StatefulWidget { const RequestsPage({super.key}); @override State<RequestsPage> createState() => _RequestsPageState(); }
class _RequestsPageState extends State<RequestsPage> {
  late final RequestsService service; Future<List<Map<String,dynamic>>>? future;
  @override void initState(){ super.initState(); _load(); }
  Future<void> _load() async { final token=await HadirSession().token(); service=RequestsService(HadirApi(token: token)); setState(()=>future=service.list()); }
  String label(String type)=>{'leave':'إجازة','permission':'استئذان','early-leave':'انصراف مبكر'}[type]??type;
  Color statusColor(String s)=>s=='approved'?Colors.green:s=='rejected'?Colors.red:Colors.orange;
  @override Widget build(BuildContext context)=>Scaffold(appBar: AppBar(title:const Text('الطلبات')),floatingActionButton:FloatingActionButton.extended(onPressed:_newRequest,label:const Text('طلب جديد'),icon:const Icon(Icons.add)),body:future==null?const Center(child:CircularProgressIndicator()):FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text(HadirApi.errorMessage(s.error!)));final rows=s.data??[];if(rows.isEmpty)return const Center(child:Text('لا توجد طلبات'));return RefreshIndicator(onRefresh:_load,child:ListView.builder(padding:const EdgeInsets.all(12),itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];final st='${r['status']??'pending'}';return Card(child:ListTile(leading:CircleAvatar(child:Icon(st=='approved'?Icons.check:st=='rejected'?Icons.close:Icons.hourglass_empty)),title:Text(label('${r['type']??''}')),subtitle:Text('${r['reason']??''}\n${r['startDate']??''} ${r['endDate']??''}'),isThreeLine:true,trailing:Text(st,style:TextStyle(color:statusColor(st),fontWeight:FontWeight.bold)));}));}),);
  Future<void> _newRequest() async { final type=ValueNotifier('leave'); final reason=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('طلب جديد'),content:Column(mainAxisSize:MainAxisSize.min,children:[ValueListenableBuilder<String>(valueListenable:type,builder:(_,v,__)=>(DropdownButtonFormField<String>(value:v,items:const [DropdownMenuItem(value:'leave',child:Text('إجازة')),DropdownMenuItem(value:'permission',child:Text('استئذان')),DropdownMenuItem(value:'early-leave',child:Text('انصراف مبكر'))],onChanged:(x)=>type.value=x!))),TextField(controller:reason,maxLines:4,decoration:const InputDecoration(labelText:'السبب'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('إرسال'))]));if(ok==true&&reason.text.trim().isNotEmpty){try{await service.create(type:type.value,reason:reason.text.trim());if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم إرسال الطلب')));setState(()=>future=service.list());}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(HadirApi.errorMessage(e))));}}reason.dispose();type.dispose();}
}
