import { useEffect, useState } from "react";

type WeatherState={temp:number;apparent:number;code:number;wind:number;city:string;loading:boolean;error?:string};
const labels=(code:number)=>code===0?"صافي":code<=3?"غائم جزئيًا":code<=48?"ضباب":code<=67?"أمطار":code<=77?"ثلوج":code<=82?"زخات مطر":code<=86?"زخات ثلج":"عاصفة";
const icon=(code:number)=>code===0?"☀️":code<=3?"⛅":code<=48?"🌫️":code<=67?"🌧️":code<=77?"❄️":code<=82?"🌦️":code<=86?"🌨️":"⛈️";
export default function WeatherCard({compact=false}:{compact?:boolean}){
 const [w,setW]=useState<WeatherState>({temp:0,apparent:0,code:0,wind:0,city:"موقعك الحالي",loading:true});
 useEffect(()=>{let cancelled=false;const load=()=>navigator.geolocation.getCurrentPosition(async p=>{try{const {latitude,longitude}=p.coords;const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`,{cache:"no-store"});if(!r.ok)throw new Error("weather");const d=await r.json();if(!cancelled)setW({temp:d.current.temperature_2m,apparent:d.current.apparent_temperature,code:d.current.weather_code,wind:d.current.wind_speed_10m,city:"موقعك الحالي",loading:false});}catch{if(!cancelled)setW(x=>({...x,loading:false,error:"تعذر جلب الطقس"}));}},()=>{if(!cancelled)setW(x=>({...x,loading:false,error:"فعّل الموقع لعرض الطقس"}));},{enableHighAccuracy:false,timeout:8000,maximumAge:300000});load();const id=window.setInterval(load,600000);return()=>{cancelled=true;window.clearInterval(id)}},[]);
 return <section className={`hud-card ${compact?"p-3":"p-4"}`} aria-label="الطقس المحلي"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] text-muted-foreground">الطقس حسب موقعك</div><div className="font-black mt-0.5">{w.loading?"جاري تحديد الموقع…":w.error||w.city}</div></div><div className="text-3xl" aria-hidden="true">{w.loading?"🌍":icon(w.code)}</div></div>{!w.loading&&!w.error&&<div className="mt-3 flex items-end justify-between gap-3"><div className="mono text-2xl font-black">{Math.round(w.temp)}°C</div><div className="text-xs text-muted-foreground text-left">{labels(w.code)}<br/>إحساس {Math.round(w.apparent)}° · رياح {Math.round(w.wind)} كم/س</div></div>}</section>;
}