import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Brand from "@/components/Brand";
import { backendEnabled, backendEmployeeLogin } from "@/lib/backend";
import { getDeviceLabel } from "@/lib/device";
import { setSession } from "@/lib/storage";
import { persistPwaSession } from "@/lib/pwaSession";
import type { Employee } from "@/types";

const API_URL = String(import.meta.env.VITE_API_URL || "https://hadir-api.abunizar963.workers.dev").replace(/\/$/, "");
const EMPLOYEE_TOKEN_KEY = "hadir.api.token.employee";
function getDeviceId(){const key="hadir.device.id";const existing=localStorage.getItem(key)?.trim();const id=existing&&existing.length>=8?existing:`dev-${crypto.randomUUID()}`;localStorage.setItem(key,id);return id;}
async function requestRebind(username:string,password:string){const response=await fetch(`${API_URL}/api/workforce/live`,{method:"POST",headers:{"content-type":"application/json"},cache:"no-store",body:JSON.stringify({action:"device-rebind-request",jobNumber:username.trim(),password,deviceId:getDeviceId(),deviceLabel:getDeviceLabel()})});const data=await response.json().catch(()=>({})) as {error?:string;message?:string};if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"تعذر إرسال الطلب");return data.message||"تم إرسال طلب إعادة ربط الهاتف، راجع الإدارة أو تواصل مع الإداريين.";}
export default function EmployeeLogin(){const navigate=useNavigate();const [jobNumber,setJobNumber]=useState("");const [pin,setPin]=useState("");const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [rebindVisible,setRebindVisible]=useState(false);const [welcomeName,setWelcomeName]=useState<string|null>(null);const finishLogin=(employee:Employee)=>{setSession({employeeId:employee.id,jobNumber:employee.jobNumber,name:employee.name,loginAt:new Date().toISOString(),role:employee.role});const token=localStorage.getItem(EMPLOYEE_TOKEN_KEY);if(token)persistPwaSession(token);window.dispatchEvent(new Event("hadir:session-changed"));setWelcomeName(employee.name);window.setTimeout(()=>navigate("/employee",{replace:true}),1800);};const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(loading)return;setLoading(true);setError(null);setSuccess(null);setRebindVisible(false);try{if(!backendEnabled)throw new Error("خدمة تسجيل دخول الموظفين غير مفعلة. تحقق من إعداد Cloudflare Worker.");finishLogin(await backendEmployeeLogin(jobNumber.trim(),pin));}catch(err){const message=err instanceof Error?err.message:"تعذر تسجيل الدخول";setError(message);setRebindVisible(message.includes("مرتبط بجهاز آخر")||message.includes("هاتف آخر"));setLoading(false);}};const rebind=async()=>{if(loading)return;setLoading(true);setError(null);setSuccess(null);try{setSuccess(await requestRebind(jobNumber.trim(),pin));}catch(err){setError(err instanceof Error?err.message:"تعذر إرسال طلب إعادة الربط");}finally{setLoading(false);}};
if(welcomeName){return <div dir="rtl" className="min-h-screen grid place-items-center bg-background px-5"><section className="w-full max-w-lg rounded-3xl border-2 border-green-500/70 bg-card p-8 text-center shadow-2xl shadow-green-500/10 sm:p-10" role="status" aria-live="polite"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full border border-green-500/40 bg-green-500/10 text-4xl">✓</div><div className="mono mt-6 text-xs font-bold tracking-widest text-green-600 dark:text-green-400">HADIR · EMPLOYEE ACCESS</div><h1 className="mt-2 text-3xl font-black">مرحبًا بك</h1><p className="mt-3 text-lg font-bold text-foreground">{welcomeName}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">تم تسجيل دخولك بنجاح، نتمنى لك يوم عمل موفقًا.</p><div className="mx-auto mt-6 h-1 w-24 overflow-hidden rounded-full bg-green-500/15"><div className="h-full w-full origin-right animate-[scale-x_1.8s_linear] rounded-full bg-green-500" /></div></section></div>}
return <div className="min-h-screen flex flex-col"><header className="p-5"><Brand/></header><main className="flex-1 grid place-items-center px-5 pb-10"><div className="w-full max-w-md"><div className="hud-card p-7"><div className="text-xs mono text-muted-foreground">EMPLOYEE · حاضِر</div><h1 className="text-2xl font-extrabold mt-1">دخول الموظفين</h1><p className="text-sm text-muted-foreground mt-1">أدخل الرقم الوظيفي ورمز الدخول الخاص بك.</p><form onSubmit={submit} className="mt-5 space-y-4"><div><label className="block text-sm text-semibold mb-1.5" htmlFor="employee-job-number">الرقم الوظيفي</label><input id="employee-job-number" name="username" className="input w-full" value={jobNumber} onChange={e=>setJobNumber(e.target.value)} autoComplete="username" inputMode="text" required disabled={loading}/></div><div><label className="block text-sm font-semibold mb-1.5" htmlFor="employee-pin">رمز الدخول</label><input id="employee-pin" name="password" className="input w-full" type="password" value={pin} onChange={e=>setPin(e.target.value)} autoComplete="current-password" inputMode="numeric" required disabled={loading}/></div>{error&&<div className="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm" role="alert">{error}</div>}{success&&<div className="rounded-xl border border-primary/30 bg-primary/10 p-3 text-sm text-primary" role="status">{success}</div>}{rebindVisible&&<button type="button" onClick={rebind} className="w-full py-2.5 rounded-xl border border-primary/40 text-primary font-semibold" disabled={loading}>📱 إرسال طلب للإدارة لفك الجهاز</button>}<button type="submit" className="btn-primary w-full py-3" disabled={loading} aria-busy={loading}>{loading?"جاري التحقق...":"دخول الموظف"}</button></form><div className="mt-5 text-xs text-center flex justify-between"><Link to="/">← العودة للرئيسية</Link><Link to="/manager/login">دخول الإدارة</Link></div></div></div></main></div>;
}