import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Brand from "@/components/Brand";
import WeatherCard from "@/components/WeatherCard";
import { backendEnabled, backendEmployeeLogin } from "@/lib/backend";
import { getDeviceLabel } from "@/lib/device";
import { getSettings, setSession } from "@/lib/storage";
import type { Employee } from "@/types";

const API_URL = String(import.meta.env.VITE_API_URL || "https://hadir-api.abunizar963.workers.dev").replace(/\/$/, "");
function getDeviceId(){const key="hadir.device.id";const existing=localStorage.getItem(key)?.trim();const id=existing&&existing.length>=8?existing:`dev-${crypto.randomUUID()}`;localStorage.setItem(key,id);return id;}
async function rebindEmployee(username:string,password:string):Promise<Employee>{const response=await fetch(`${API_URL}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},credentials:"include",cache:"no-store",body:JSON.stringify({username:username.trim(),password,deviceId:getDeviceId(),deviceLabel:getDeviceLabel(),rebindDevice:true})});const data=await response.json().catch(()=>({})) as {token?:string;user?:Employee;kind?:string;error?:string};if(!response.ok)throw new Error(typeof data.error==="string"?data.error:`فشل تسجيل الدخول (${response.status})`);if(data.kind!=="employee"||!data.token||!data.user?.id||!data.user?.jobNumber)throw new Error("تعذر إنشاء جلسة الموظف.");localStorage.setItem("hadir.api.token.employee",data.token);return data.user;}
async function requestRebind(username:string,password:string){const response=await fetch(`${API_URL}/api/workforce/live`,{method:"POST",headers:{"content-type":"application/json"},cache:"no-store",body:JSON.stringify({action:"device-rebind-request",jobNumber:username.trim(),password,deviceId:getDeviceId(),deviceLabel:getDeviceLabel()})});const data=await response.json().catch(()=>({})) as {error?:string;message?:string};if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"تعذر إرسال الطلب");return data.message||"تم إرسال طلب إعادة ربط الهاتف إلى الإدارة.";}
export default function EmployeeLogin(){const navigate=useNavigate();const settings=getSettings();const [jobNumber,setJobNumber]=useState("");const [pin,setPin]=useState("");const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [rebindVisible,setRebindVisible]=useState(false);const finishLogin=(employee:Employee)=>{setSession({employeeId:employee.id,jobNumber:employee.jobNumber,name:employee.name,loginAt:new Date().toISOString(),role:employee.role});window.dispatchEvent(new Event("hadir:session-changed"));navigate("/employee",{replace:true});};const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(loading)return;setLoading(true);setError(null);setSuccess(null);setRebindVisible(false);try{if(!backendEnabled)throw new Error("خدمة تسجيل دخول الموظفين غير مفعلة. تحقق من إعداد Cloudflare Worker.");finishLogin(await backendEmployeeLogin(jobNumber.trim(),pin));}catch(err){const message=err instanceof Error?err.message:"تعذر تسجيل الدخول";setError(message);setRebindVisible(message.includes("مرتبط بجهاز آخر")||message.includes("هاتف آخر"));}finally{setLoading(false);}};const rebind=async()=>{if(loading)return;setLoading(true);setError(null);setSuccess(null);try{setSuccess(await requestRebind(jobNumber.trim(),pin));}catch(err){setError(err instanceof Error?err.message:"تعذر إرسال طلب إعادة الربط");}finally{setLoading(false);}};
return <div className="min-h-screen flex flex-col"><header className="p-5"><Brand/></header><main className="flex-1 grid place-items-center px-5 pb-10"><div className="w-full max-w-md"><div className="hud-card p-7">
 <div className="text-xs mono text-muted-foreground">EMPLOYEE · حاضِر</div><h1 className="text-2xl font-extrabold mt-1">دخول الموظفين</h1><p className="text-sm text-muted-foreground mt-1">أدخل الرقم الوظيفي ورمز الدخول الخاص بك.</p>
 <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-2" aria-label="حالة الطقس"><WeatherCard compact title="طقس موقعك" className="weather-strip-live"/><WeatherCard compact title="طقس موقع العمل" latitude={settings.workSiteLat} longitude={settings.workSiteLng} hideWhenWithinKm={10} referenceLatitude={settings.workSiteLat} referenceLongitude={settings.workSiteLng} className="weather-strip-live"/></div>
 <form onSubmit={submit} className="mt-5 space-y-4"><div><label className="block text-sm text-semibold mb-1.5" htmlFor="employee-job-number">الرقم الوظيفي</label><input id="employee-job-number" name="username" className="input w-full" value={jobNumber} onChange={e=>setJobNumber(e.target.value)} autoComplete="username" inputMode="text" required disabled={loading}/></div><div><label className="block text-sm font-semibold mb-1.5" htmlFor="employee-pin">رمز الدخول</label><input id="employee-pin" name="password" className="input w-full" type="password" value={pin} onChange={e=>setPin(e.target.value)} autoComplete="current-password" inputMode="numeric" required disabled={loading}/></div>{error&&<div className="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm" role="alert">{error}</div>}{success&&<div className="rounded-xl border border-primary/30 bg-primary/10 p-3 text-sm text-primary" role="status">{success}</div>}{rebindVisible&&<button type="button" onClick={rebind} className="w-full py-2.5 rounded-xl border border-primary/40 text-primary font-semibold" disabled={loading}>📱 إرسال طلب للإدارة لفك الجهاز</button>}<button type="submit" className="btn-primary w-full py-3" disabled={loading} aria-busy={loading}>{loading?"جاري التحقق...":"دخول الموظف"}</button></form><div className="mt-5 text-xs text-center flex justify-between"><Link to="/">← العودة للرئيسية</Link><Link to="/manager/login">دخول الإدارة</Link></div>
 </div></div></main></div>;
}